/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ModelToolsSearchReq } from "../v1/ModelToolsSearchReq";
import type { V1ModelToolsSearchRes } from "../v1/ModelToolsSearchRes";

export type ModelToolsSearch200 = V1ModelToolsSearchRes;

export type ModelToolsSearchMutationRequest = V1ModelToolsSearchReq;

export type ModelToolsSearchMutationResponse = ModelToolsSearch200;

export type ModelToolsSearchMutation = {
    Response: ModelToolsSearch200;
    Request: ModelToolsSearchMutationRequest;
    Errors: any;
};