/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { NotificationMarkReadMutationRequest, NotificationMarkReadMutationResponse } from "../../types/notificationTypes/NotificationMarkRead";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const notificationMarkReadSuspenseQueryKey = (data: NotificationMarkReadMutationRequest) => [{ url: '/api/notification/mark_read' }, ...(data ? [data] : [])] as const

export type NotificationMarkReadSuspenseQueryKey = ReturnType<typeof notificationMarkReadSuspenseQueryKey>

/**
 * @summary 标记通知已读
 * {@link /api/notification/mark_read}
 */
export async function notificationMarkReadSuspense(data: NotificationMarkReadMutationRequest, config: Partial<RequestConfig<NotificationMarkReadMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<NotificationMarkReadMutationResponse, ResponseErrorConfig<Error>, NotificationMarkReadMutationRequest>({ method : "POST", url : `/api/notification/mark_read`, data : requestData, ... requestConfig })  
  return res.data
}

export function notificationMarkReadSuspenseQueryOptions(data: NotificationMarkReadMutationRequest, config: Partial<RequestConfig<NotificationMarkReadMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = notificationMarkReadSuspenseQueryKey(data)
  return queryOptions<NotificationMarkReadMutationResponse, ResponseErrorConfig<Error>, NotificationMarkReadMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return notificationMarkReadSuspense(data, config)
   },
  })
}

/**
 * @summary 标记通知已读
 * {@link /api/notification/mark_read}
 */
export function useNotificationMarkReadSuspense<TData = NotificationMarkReadMutationResponse, TQueryKey extends QueryKey = NotificationMarkReadSuspenseQueryKey>(data: NotificationMarkReadMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<NotificationMarkReadMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<NotificationMarkReadMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? notificationMarkReadSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...notificationMarkReadSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}