/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { NotificationListMutationRequest, NotificationListMutationResponse } from "../../types/notificationTypes/NotificationList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const notificationListQueryKey = (data: NotificationListMutationRequest) => [{ url: '/api/notification/list' }, ...(data ? [data] : [])] as const

export type NotificationListQueryKey = ReturnType<typeof notificationListQueryKey>

/**
 * @summary 通知列表
 * {@link /api/notification/list}
 */
export async function notificationList(data: NotificationListMutationRequest, config: Partial<RequestConfig<NotificationListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<NotificationListMutationResponse, ResponseErrorConfig<Error>, NotificationListMutationRequest>({ method : "POST", url : `/api/notification/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function notificationListQueryOptions(data: NotificationListMutationRequest, config: Partial<RequestConfig<NotificationListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = notificationListQueryKey(data)
  return queryOptions<NotificationListMutationResponse, ResponseErrorConfig<Error>, NotificationListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return notificationList(data, config)
   },
  })
}

/**
 * @summary 通知列表
 * {@link /api/notification/list}
 */
export function useNotificationList<TData = NotificationListMutationResponse, TQueryData = NotificationListMutationResponse, TQueryKey extends QueryKey = NotificationListQueryKey>(data: NotificationListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<NotificationListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<NotificationListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? notificationListQueryKey(data)

  const query = useQuery({
   ...notificationListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}