/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { NotificationListMutationRequest, NotificationListMutationResponse } from "../../types/notificationTypes/NotificationList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const notificationListSuspenseQueryKey = (data: NotificationListMutationRequest) => [{ url: '/api/notification/list' }, ...(data ? [data] : [])] as const

export type NotificationListSuspenseQueryKey = ReturnType<typeof notificationListSuspenseQueryKey>

/**
 * @summary 通知列表
 * {@link /api/notification/list}
 */
export async function notificationListSuspense(data: NotificationListMutationRequest, config: Partial<RequestConfig<NotificationListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<NotificationListMutationResponse, ResponseErrorConfig<Error>, NotificationListMutationRequest>({ method : "POST", url : `/api/notification/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function notificationListSuspenseQueryOptions(data: NotificationListMutationRequest, config: Partial<RequestConfig<NotificationListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = notificationListSuspenseQueryKey(data)
  return queryOptions<NotificationListMutationResponse, ResponseErrorConfig<Error>, NotificationListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return notificationListSuspense(data, config)
   },
  })
}

/**
 * @summary 通知列表
 * {@link /api/notification/list}
 */
export function useNotificationListSuspense<TData = NotificationListMutationResponse, TQueryKey extends QueryKey = NotificationListSuspenseQueryKey>(data: NotificationListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<NotificationListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<NotificationListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? notificationListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...notificationListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}