/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { NotificationMarkReadMutationRequest, NotificationMarkReadMutationResponse } from "../../types/notificationTypes/NotificationMarkRead";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const notificationMarkReadQueryKey = (data: NotificationMarkReadMutationRequest) => [{ url: '/api/notification/mark_read' }, ...(data ? [data] : [])] as const

export type NotificationMarkReadQueryKey = ReturnType<typeof notificationMarkReadQueryKey>

/**
 * @summary 标记通知已读
 * {@link /api/notification/mark_read}
 */
export async function notificationMarkRead(data: NotificationMarkReadMutationRequest, config: Partial<RequestConfig<NotificationMarkReadMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<NotificationMarkReadMutationResponse, ResponseErrorConfig<Error>, NotificationMarkReadMutationRequest>({ method : "POST", url : `/api/notification/mark_read`, data : requestData, ... requestConfig })  
  return res.data
}

export function notificationMarkReadQueryOptions(data: NotificationMarkReadMutationRequest, config: Partial<RequestConfig<NotificationMarkReadMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = notificationMarkReadQueryKey(data)
  return queryOptions<NotificationMarkReadMutationResponse, ResponseErrorConfig<Error>, NotificationMarkReadMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return notificationMarkRead(data, config)
   },
  })
}

/**
 * @summary 标记通知已读
 * {@link /api/notification/mark_read}
 */
export function useNotificationMarkRead<TData = NotificationMarkReadMutationResponse, TQueryData = NotificationMarkReadMutationResponse, TQueryKey extends QueryKey = NotificationMarkReadQueryKey>(data: NotificationMarkReadMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<NotificationMarkReadMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<NotificationMarkReadMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? notificationMarkReadQueryKey(data)

  const query = useQuery({
   ...notificationMarkReadQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}