/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatSearchLimitStatusMutationRequest, ChatSearchLimitStatusMutationResponse } from "../../types/chatTypes/ChatSearchLimitStatus";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatSearchLimitStatusQueryKey = (data?: ChatSearchLimitStatusMutationRequest) => [{ url: '/api/chat/search_limit_status' }, ...(data ? [data] : [])] as const

export type ChatSearchLimitStatusQueryKey = ReturnType<typeof chatSearchLimitStatusQueryKey>

/**
 * @summary 检测当天能否使用搜索状态
 * {@link /api/chat/search_limit_status}
 */
export async function chatSearchLimitStatus(data?: ChatSearchLimitStatusMutationRequest, config: Partial<RequestConfig<ChatSearchLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatSearchLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatSearchLimitStatusMutationRequest>({ method : "POST", url : `/api/chat/search_limit_status`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatSearchLimitStatusQueryOptions(data?: ChatSearchLimitStatusMutationRequest, config: Partial<RequestConfig<ChatSearchLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatSearchLimitStatusQueryKey(data)
  return queryOptions<ChatSearchLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatSearchLimitStatusMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatSearchLimitStatus(data, config)
   },
  })
}

/**
 * @summary 检测当天能否使用搜索状态
 * {@link /api/chat/search_limit_status}
 */
export function useChatSearchLimitStatus<TData = ChatSearchLimitStatusMutationResponse, TQueryData = ChatSearchLimitStatusMutationResponse, TQueryKey extends QueryKey = ChatSearchLimitStatusQueryKey>(data?: ChatSearchLimitStatusMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ChatSearchLimitStatusMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatSearchLimitStatusMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatSearchLimitStatusQueryKey(data)

  const query = useQuery({
   ...chatSearchLimitStatusQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}