/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatCompletionsMutationRequest, ChatCompletionsMutationResponse } from "../../types/chatTypes/ChatCompletions";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatCompletionsQueryKey = (data: ChatCompletionsMutationRequest) => [{ url: '/api/chat/completions' }, ...(data ? [data] : [])] as const

export type ChatCompletionsQueryKey = ReturnType<typeof chatCompletionsQueryKey>

/**
 * @summary 对话
 * {@link /api/chat/completions}
 */
export async function chatCompletions(data: ChatCompletionsMutationRequest, config: Partial<RequestConfig<ChatCompletionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatCompletionsMutationResponse, ResponseErrorConfig<Error>, ChatCompletionsMutationRequest>({ method : "POST", url : `/api/chat/completions`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatCompletionsQueryOptions(data: ChatCompletionsMutationRequest, config: Partial<RequestConfig<ChatCompletionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatCompletionsQueryKey(data)
  return queryOptions<ChatCompletionsMutationResponse, ResponseErrorConfig<Error>, ChatCompletionsMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatCompletions(data, config)
   },
  })
}

/**
 * @summary 对话
 * {@link /api/chat/completions}
 */
export function useChatCompletions<TData = ChatCompletionsMutationResponse, TQueryData = ChatCompletionsMutationResponse, TQueryKey extends QueryKey = ChatCompletionsQueryKey>(data: ChatCompletionsMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ChatCompletionsMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatCompletionsMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatCompletionsQueryKey(data)

  const query = useQuery({
   ...chatCompletionsQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}