/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatImageLimitStatusMutationRequest, ChatImageLimitStatusMutationResponse } from "../../types/chatTypes/ChatImageLimitStatus";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatImageLimitStatusQueryKey = (data?: ChatImageLimitStatusMutationRequest) => [{ url: '/api/chat/image_limit_status' }, ...(data ? [data] : [])] as const

export type ChatImageLimitStatusQueryKey = ReturnType<typeof chatImageLimitStatusQueryKey>

/**
 * @summary 检测当天能否生成图片状态
 * {@link /api/chat/image_limit_status}
 */
export async function chatImageLimitStatus(data?: ChatImageLimitStatusMutationRequest, config: Partial<RequestConfig<ChatImageLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatImageLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatImageLimitStatusMutationRequest>({ method : "POST", url : `/api/chat/image_limit_status`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatImageLimitStatusQueryOptions(data?: ChatImageLimitStatusMutationRequest, config: Partial<RequestConfig<ChatImageLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatImageLimitStatusQueryKey(data)
  return queryOptions<ChatImageLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatImageLimitStatusMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatImageLimitStatus(data, config)
   },
  })
}

/**
 * @summary 检测当天能否生成图片状态
 * {@link /api/chat/image_limit_status}
 */
export function useChatImageLimitStatus<TData = ChatImageLimitStatusMutationResponse, TQueryData = ChatImageLimitStatusMutationResponse, TQueryKey extends QueryKey = ChatImageLimitStatusQueryKey>(data?: ChatImageLimitStatusMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ChatImageLimitStatusMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatImageLimitStatusMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatImageLimitStatusQueryKey(data)

  const query = useQuery({
   ...chatImageLimitStatusQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}