/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatTokenLimitStatusMutationRequest, ChatTokenLimitStatusMutationResponse } from "../../types/chatTypes/ChatTokenLimitStatus";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const chatTokenLimitStatusSuspenseQueryKey = (data?: ChatTokenLimitStatusMutationRequest) => [{ url: '/api/chat/token_limit_status' }, ...(data ? [data] : [])] as const

export type ChatTokenLimitStatusSuspenseQueryKey = ReturnType<typeof chatTokenLimitStatusSuspenseQueryKey>

/**
 * @summary 检测当月能否使用token状态
 * {@link /api/chat/token_limit_status}
 */
export async function chatTokenLimitStatusSuspense(data?: ChatTokenLimitStatusMutationRequest, config: Partial<RequestConfig<ChatTokenLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatTokenLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatTokenLimitStatusMutationRequest>({ method : "POST", url : `/api/chat/token_limit_status`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatTokenLimitStatusSuspenseQueryOptions(data?: ChatTokenLimitStatusMutationRequest, config: Partial<RequestConfig<ChatTokenLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatTokenLimitStatusSuspenseQueryKey(data)
  return queryOptions<ChatTokenLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatTokenLimitStatusMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatTokenLimitStatusSuspense(data, config)
   },
  })
}

/**
 * @summary 检测当月能否使用token状态
 * {@link /api/chat/token_limit_status}
 */
export function useChatTokenLimitStatusSuspense<TData = ChatTokenLimitStatusMutationResponse, TQueryKey extends QueryKey = ChatTokenLimitStatusSuspenseQueryKey>(data?: ChatTokenLimitStatusMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ChatTokenLimitStatusMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatTokenLimitStatusMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatTokenLimitStatusSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...chatTokenLimitStatusSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}