/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatImageLimitStatusMutationRequest, ChatImageLimitStatusMutationResponse } from "../../types/chatTypes/ChatImageLimitStatus";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const chatImageLimitStatusSuspenseQueryKey = (data?: ChatImageLimitStatusMutationRequest) => [{ url: '/api/chat/image_limit_status' }, ...(data ? [data] : [])] as const

export type ChatImageLimitStatusSuspenseQueryKey = ReturnType<typeof chatImageLimitStatusSuspenseQueryKey>

/**
 * @summary 检测当天能否生成图片状态
 * {@link /api/chat/image_limit_status}
 */
export async function chatImageLimitStatusSuspense(data?: ChatImageLimitStatusMutationRequest, config: Partial<RequestConfig<ChatImageLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatImageLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatImageLimitStatusMutationRequest>({ method : "POST", url : `/api/chat/image_limit_status`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatImageLimitStatusSuspenseQueryOptions(data?: ChatImageLimitStatusMutationRequest, config: Partial<RequestConfig<ChatImageLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatImageLimitStatusSuspenseQueryKey(data)
  return queryOptions<ChatImageLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatImageLimitStatusMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatImageLimitStatusSuspense(data, config)
   },
  })
}

/**
 * @summary 检测当天能否生成图片状态
 * {@link /api/chat/image_limit_status}
 */
export function useChatImageLimitStatusSuspense<TData = ChatImageLimitStatusMutationResponse, TQueryKey extends QueryKey = ChatImageLimitStatusSuspenseQueryKey>(data?: ChatImageLimitStatusMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ChatImageLimitStatusMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatImageLimitStatusMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatImageLimitStatusSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...chatImageLimitStatusSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}