/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatSearchLimitStatusMutationRequest, ChatSearchLimitStatusMutationResponse } from "../../types/chatTypes/ChatSearchLimitStatus";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const chatSearchLimitStatusSuspenseQueryKey = (data?: ChatSearchLimitStatusMutationRequest) => [{ url: '/api/chat/search_limit_status' }, ...(data ? [data] : [])] as const

export type ChatSearchLimitStatusSuspenseQueryKey = ReturnType<typeof chatSearchLimitStatusSuspenseQueryKey>

/**
 * @summary 检测当天能否使用搜索状态
 * {@link /api/chat/search_limit_status}
 */
export async function chatSearchLimitStatusSuspense(data?: ChatSearchLimitStatusMutationRequest, config: Partial<RequestConfig<ChatSearchLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatSearchLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatSearchLimitStatusMutationRequest>({ method : "POST", url : `/api/chat/search_limit_status`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatSearchLimitStatusSuspenseQueryOptions(data?: ChatSearchLimitStatusMutationRequest, config: Partial<RequestConfig<ChatSearchLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatSearchLimitStatusSuspenseQueryKey(data)
  return queryOptions<ChatSearchLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatSearchLimitStatusMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatSearchLimitStatusSuspense(data, config)
   },
  })
}

/**
 * @summary 检测当天能否使用搜索状态
 * {@link /api/chat/search_limit_status}
 */
export function useChatSearchLimitStatusSuspense<TData = ChatSearchLimitStatusMutationResponse, TQueryKey extends QueryKey = ChatSearchLimitStatusSuspenseQueryKey>(data?: ChatSearchLimitStatusMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ChatSearchLimitStatusMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatSearchLimitStatusMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatSearchLimitStatusSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...chatSearchLimitStatusSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}