/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatTokenLimitStatusMutationRequest, ChatTokenLimitStatusMutationResponse } from "../../types/chatTypes/ChatTokenLimitStatus";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatTokenLimitStatusQueryKey = (data?: ChatTokenLimitStatusMutationRequest) => [{ url: '/api/chat/token_limit_status' }, ...(data ? [data] : [])] as const

export type ChatTokenLimitStatusQueryKey = ReturnType<typeof chatTokenLimitStatusQueryKey>

/**
 * @summary 检测当月能否使用token状态
 * {@link /api/chat/token_limit_status}
 */
export async function chatTokenLimitStatus(data?: ChatTokenLimitStatusMutationRequest, config: Partial<RequestConfig<ChatTokenLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatTokenLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatTokenLimitStatusMutationRequest>({ method : "POST", url : `/api/chat/token_limit_status`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatTokenLimitStatusQueryOptions(data?: ChatTokenLimitStatusMutationRequest, config: Partial<RequestConfig<ChatTokenLimitStatusMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatTokenLimitStatusQueryKey(data)
  return queryOptions<ChatTokenLimitStatusMutationResponse, ResponseErrorConfig<Error>, ChatTokenLimitStatusMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatTokenLimitStatus(data, config)
   },
  })
}

/**
 * @summary 检测当月能否使用token状态
 * {@link /api/chat/token_limit_status}
 */
export function useChatTokenLimitStatus<TData = ChatTokenLimitStatusMutationResponse, TQueryData = ChatTokenLimitStatusMutationResponse, TQueryKey extends QueryKey = ChatTokenLimitStatusQueryKey>(data?: ChatTokenLimitStatusMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ChatTokenLimitStatusMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatTokenLimitStatusMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatTokenLimitStatusQueryKey(data)

  const query = useQuery({
   ...chatTokenLimitStatusQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}