/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatStopMutationRequest, ChatStopMutationResponse } from "../../types/chatTypes/ChatStop";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const chatStopSuspenseQueryKey = (data: ChatStopMutationRequest) => [{ url: '/api/chat/stop' }, ...(data ? [data] : [])] as const

export type ChatStopSuspenseQueryKey = ReturnType<typeof chatStopSuspenseQueryKey>

/**
 * @summary 对话停止
 * {@link /api/chat/stop}
 */
export async function chatStopSuspense(data: ChatStopMutationRequest, config: Partial<RequestConfig<ChatStopMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatStopMutationResponse, ResponseErrorConfig<Error>, ChatStopMutationRequest>({ method : "POST", url : `/api/chat/stop`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatStopSuspenseQueryOptions(data: ChatStopMutationRequest, config: Partial<RequestConfig<ChatStopMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatStopSuspenseQueryKey(data)
  return queryOptions<ChatStopMutationResponse, ResponseErrorConfig<Error>, ChatStopMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatStopSuspense(data, config)
   },
  })
}

/**
 * @summary 对话停止
 * {@link /api/chat/stop}
 */
export function useChatStopSuspense<TData = ChatStopMutationResponse, TQueryKey extends QueryKey = ChatStopSuspenseQueryKey>(data: ChatStopMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ChatStopMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatStopMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatStopSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...chatStopSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}