/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatListMutationRequest, ChatListMutationResponse } from "../../types/chatTypes/ChatList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatListQueryKey = (data: ChatListMutationRequest) => [{ url: '/api/chat/list' }, ...(data ? [data] : [])] as const

export type ChatListQueryKey = ReturnType<typeof chatListQueryKey>

/**
 * @summary 对话历史
 * {@link /api/chat/list}
 */
export async function chatList(data: ChatListMutationRequest, config: Partial<RequestConfig<ChatListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatListMutationResponse, ResponseErrorConfig<Error>, ChatListMutationRequest>({ method : "POST", url : `/api/chat/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatListQueryOptions(data: ChatListMutationRequest, config: Partial<RequestConfig<ChatListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatListQueryKey(data)
  return queryOptions<ChatListMutationResponse, ResponseErrorConfig<Error>, ChatListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatList(data, config)
   },
  })
}

/**
 * @summary 对话历史
 * {@link /api/chat/list}
 */
export function useChatList<TData = ChatListMutationResponse, TQueryData = ChatListMutationResponse, TQueryKey extends QueryKey = ChatListQueryKey>(data: ChatListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ChatListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatListQueryKey(data)

  const query = useQuery({
   ...chatListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}