/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatListMutationRequest, ChatListMutationResponse } from "../../types/chatTypes/ChatList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const chatListSuspenseQueryKey = (data: ChatListMutationRequest) => [{ url: '/api/chat/list' }, ...(data ? [data] : [])] as const

export type ChatListSuspenseQueryKey = ReturnType<typeof chatListSuspenseQueryKey>

/**
 * @summary 对话历史
 * {@link /api/chat/list}
 */
export async function chatListSuspense(data: ChatListMutationRequest, config: Partial<RequestConfig<ChatListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatListMutationResponse, ResponseErrorConfig<Error>, ChatListMutationRequest>({ method : "POST", url : `/api/chat/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatListSuspenseQueryOptions(data: ChatListMutationRequest, config: Partial<RequestConfig<ChatListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatListSuspenseQueryKey(data)
  return queryOptions<ChatListMutationResponse, ResponseErrorConfig<Error>, ChatListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatListSuspense(data, config)
   },
  })
}

/**
 * @summary 对话历史
 * {@link /api/chat/list}
 */
export function useChatListSuspense<TData = ChatListMutationResponse, TQueryKey extends QueryKey = ChatListSuspenseQueryKey>(data: ChatListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ChatListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...chatListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}