/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatCompletionsMutationRequest, ChatCompletionsMutationResponse } from "../../types/chatTypes/ChatCompletions";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const chatCompletionsSuspenseQueryKey = (data: ChatCompletionsMutationRequest) => [{ url: '/api/chat/completions' }, ...(data ? [data] : [])] as const

export type ChatCompletionsSuspenseQueryKey = ReturnType<typeof chatCompletionsSuspenseQueryKey>

/**
 * @summary 对话
 * {@link /api/chat/completions}
 */
export async function chatCompletionsSuspense(data: ChatCompletionsMutationRequest, config: Partial<RequestConfig<ChatCompletionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatCompletionsMutationResponse, ResponseErrorConfig<Error>, ChatCompletionsMutationRequest>({ method : "POST", url : `/api/chat/completions`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatCompletionsSuspenseQueryOptions(data: ChatCompletionsMutationRequest, config: Partial<RequestConfig<ChatCompletionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatCompletionsSuspenseQueryKey(data)
  return queryOptions<ChatCompletionsMutationResponse, ResponseErrorConfig<Error>, ChatCompletionsMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatCompletionsSuspense(data, config)
   },
  })
}

/**
 * @summary 对话
 * {@link /api/chat/completions}
 */
export function useChatCompletionsSuspense<TData = ChatCompletionsMutationResponse, TQueryKey extends QueryKey = ChatCompletionsSuspenseQueryKey>(data: ChatCompletionsMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ChatCompletionsMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatCompletionsMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatCompletionsSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...chatCompletionsSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}