/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatSynchronizeTokenMutationRequest, ChatSynchronizeTokenMutationResponse } from "../../types/chatTypes/ChatSynchronizeToken";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatSynchronizeTokenQueryKey = (data: ChatSynchronizeTokenMutationRequest) => [{ url: '/api/chat/synchronize_token' }, ...(data ? [data] : [])] as const

export type ChatSynchronizeTokenQueryKey = ReturnType<typeof chatSynchronizeTokenQueryKey>

/**
 * @summary 同步token使用量
 * {@link /api/chat/synchronize_token}
 */
export async function chatSynchronizeToken(data: ChatSynchronizeTokenMutationRequest, config: Partial<RequestConfig<ChatSynchronizeTokenMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatSynchronizeTokenMutationResponse, ResponseErrorConfig<Error>, ChatSynchronizeTokenMutationRequest>({ method : "POST", url : `/api/chat/synchronize_token`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatSynchronizeTokenQueryOptions(data: ChatSynchronizeTokenMutationRequest, config: Partial<RequestConfig<ChatSynchronizeTokenMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatSynchronizeTokenQueryKey(data)
  return queryOptions<ChatSynchronizeTokenMutationResponse, ResponseErrorConfig<Error>, ChatSynchronizeTokenMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatSynchronizeToken(data, config)
   },
  })
}

/**
 * @summary 同步token使用量
 * {@link /api/chat/synchronize_token}
 */
export function useChatSynchronizeToken<TData = ChatSynchronizeTokenMutationResponse, TQueryData = ChatSynchronizeTokenMutationResponse, TQueryKey extends QueryKey = ChatSynchronizeTokenQueryKey>(data: ChatSynchronizeTokenMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ChatSynchronizeTokenMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatSynchronizeTokenMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatSynchronizeTokenQueryKey(data)

  const query = useQuery({
   ...chatSynchronizeTokenQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}