/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ChatStopMutationRequest, ChatStopMutationResponse } from "../../types/chatTypes/ChatStop";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatStopQueryKey = (data: ChatStopMutationRequest) => [{ url: '/api/chat/stop' }, ...(data ? [data] : [])] as const

export type ChatStopQueryKey = ReturnType<typeof chatStopQueryKey>

/**
 * @summary 对话停止
 * {@link /api/chat/stop}
 */
export async function chatStop(data: ChatStopMutationRequest, config: Partial<RequestConfig<ChatStopMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatStopMutationResponse, ResponseErrorConfig<Error>, ChatStopMutationRequest>({ method : "POST", url : `/api/chat/stop`, data : requestData, ... requestConfig })  
  return res.data
}

export function chatStopQueryOptions(data: ChatStopMutationRequest, config: Partial<RequestConfig<ChatStopMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = chatStopQueryKey(data)
  return queryOptions<ChatStopMutationResponse, ResponseErrorConfig<Error>, ChatStopMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return chatStop(data, config)
   },
  })
}

/**
 * @summary 对话停止
 * {@link /api/chat/stop}
 */
export function useChatStop<TData = ChatStopMutationResponse, TQueryData = ChatStopMutationResponse, TQueryKey extends QueryKey = ChatStopQueryKey>(data: ChatStopMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ChatStopMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ChatStopMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? chatStopQueryKey(data)

  const query = useQuery({
   ...chatStopQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}