/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsFindAccountPointAndLevelMutationRequest, PointsFindAccountPointAndLevelMutationResponse } from "../../types/pointsTypes/PointsFindAccountPointAndLevel";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const pointsFindAccountPointAndLevelSuspenseQueryKey = (data?: PointsFindAccountPointAndLevelMutationRequest) => [{ url: '/api/points/findAccountPointAndLevel' }, ...(data ? [data] : [])] as const

export type PointsFindAccountPointAndLevelSuspenseQueryKey = ReturnType<typeof pointsFindAccountPointAndLevelSuspenseQueryKey>

/**
 * @summary 查询账户积分等级详情
 * {@link /api/points/findAccountPointAndLevel}
 */
export async function pointsFindAccountPointAndLevelSuspense(data?: PointsFindAccountPointAndLevelMutationRequest, config: Partial<RequestConfig<PointsFindAccountPointAndLevelMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsFindAccountPointAndLevelMutationResponse, ResponseErrorConfig<Error>, PointsFindAccountPointAndLevelMutationRequest>({ method : "POST", url : `/api/points/findAccountPointAndLevel`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsFindAccountPointAndLevelSuspenseQueryOptions(data?: PointsFindAccountPointAndLevelMutationRequest, config: Partial<RequestConfig<PointsFindAccountPointAndLevelMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsFindAccountPointAndLevelSuspenseQueryKey(data)
  return queryOptions<PointsFindAccountPointAndLevelMutationResponse, ResponseErrorConfig<Error>, PointsFindAccountPointAndLevelMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsFindAccountPointAndLevelSuspense(data, config)
   },
  })
}

/**
 * @summary 查询账户积分等级详情
 * {@link /api/points/findAccountPointAndLevel}
 */
export function usePointsFindAccountPointAndLevelSuspense<TData = PointsFindAccountPointAndLevelMutationResponse, TQueryKey extends QueryKey = PointsFindAccountPointAndLevelSuspenseQueryKey>(data?: PointsFindAccountPointAndLevelMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<PointsFindAccountPointAndLevelMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsFindAccountPointAndLevelMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsFindAccountPointAndLevelSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...pointsFindAccountPointAndLevelSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}