/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsFindPointDetailListMutationRequest, PointsFindPointDetailListMutationResponse } from "../../types/pointsTypes/PointsFindPointDetailList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const pointsFindPointDetailListSuspenseQueryKey = (data?: PointsFindPointDetailListMutationRequest) => [{ url: '/api/points/findPointDetailList' }, ...(data ? [data] : [])] as const

export type PointsFindPointDetailListSuspenseQueryKey = ReturnType<typeof pointsFindPointDetailListSuspenseQueryKey>

/**
 * @summary 查询积分明细列表
 * {@link /api/points/findPointDetailList}
 */
export async function pointsFindPointDetailListSuspense(data?: PointsFindPointDetailListMutationRequest, config: Partial<RequestConfig<PointsFindPointDetailListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsFindPointDetailListMutationResponse, ResponseErrorConfig<Error>, PointsFindPointDetailListMutationRequest>({ method : "POST", url : `/api/points/findPointDetailList`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsFindPointDetailListSuspenseQueryOptions(data?: PointsFindPointDetailListMutationRequest, config: Partial<RequestConfig<PointsFindPointDetailListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsFindPointDetailListSuspenseQueryKey(data)
  return queryOptions<PointsFindPointDetailListMutationResponse, ResponseErrorConfig<Error>, PointsFindPointDetailListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsFindPointDetailListSuspense(data, config)
   },
  })
}

/**
 * @summary 查询积分明细列表
 * {@link /api/points/findPointDetailList}
 */
export function usePointsFindPointDetailListSuspense<TData = PointsFindPointDetailListMutationResponse, TQueryKey extends QueryKey = PointsFindPointDetailListSuspenseQueryKey>(data?: PointsFindPointDetailListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<PointsFindPointDetailListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsFindPointDetailListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsFindPointDetailListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...pointsFindPointDetailListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}