/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsCreatePointTypeMutationRequest, PointsCreatePointTypeMutationResponse } from "../../types/pointsTypes/PointsCreatePointType";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const pointsCreatePointTypeQueryKey = (data?: PointsCreatePointTypeMutationRequest) => [{ url: '/api/points/createPointType' }, ...(data ? [data] : [])] as const

export type PointsCreatePointTypeQueryKey = ReturnType<typeof pointsCreatePointTypeQueryKey>

/**
 * @summary 创建积分类型
 * {@link /api/points/createPointType}
 */
export async function pointsCreatePointType(data?: PointsCreatePointTypeMutationRequest, config: Partial<RequestConfig<PointsCreatePointTypeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsCreatePointTypeMutationResponse, ResponseErrorConfig<Error>, PointsCreatePointTypeMutationRequest>({ method : "POST", url : `/api/points/createPointType`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsCreatePointTypeQueryOptions(data?: PointsCreatePointTypeMutationRequest, config: Partial<RequestConfig<PointsCreatePointTypeMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsCreatePointTypeQueryKey(data)
  return queryOptions<PointsCreatePointTypeMutationResponse, ResponseErrorConfig<Error>, PointsCreatePointTypeMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsCreatePointType(data, config)
   },
  })
}

/**
 * @summary 创建积分类型
 * {@link /api/points/createPointType}
 */
export function usePointsCreatePointType<TData = PointsCreatePointTypeMutationResponse, TQueryData = PointsCreatePointTypeMutationResponse, TQueryKey extends QueryKey = PointsCreatePointTypeQueryKey>(data?: PointsCreatePointTypeMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<PointsCreatePointTypeMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsCreatePointTypeMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsCreatePointTypeQueryKey(data)

  const query = useQuery({
   ...pointsCreatePointTypeQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}