/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsCreatePointDetailMutationRequest, PointsCreatePointDetailMutationResponse } from "../../types/pointsTypes/PointsCreatePointDetail";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const pointsCreatePointDetailQueryKey = (data?: PointsCreatePointDetailMutationRequest) => [{ url: '/api/points/createPointDetail' }, ...(data ? [data] : [])] as const

export type PointsCreatePointDetailQueryKey = ReturnType<typeof pointsCreatePointDetailQueryKey>

/**
 * @summary 新增积分
 * {@link /api/points/createPointDetail}
 */
export async function pointsCreatePointDetail(data?: PointsCreatePointDetailMutationRequest, config: Partial<RequestConfig<PointsCreatePointDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsCreatePointDetailMutationResponse, ResponseErrorConfig<Error>, PointsCreatePointDetailMutationRequest>({ method : "POST", url : `/api/points/createPointDetail`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsCreatePointDetailQueryOptions(data?: PointsCreatePointDetailMutationRequest, config: Partial<RequestConfig<PointsCreatePointDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsCreatePointDetailQueryKey(data)
  return queryOptions<PointsCreatePointDetailMutationResponse, ResponseErrorConfig<Error>, PointsCreatePointDetailMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsCreatePointDetail(data, config)
   },
  })
}

/**
 * @summary 新增积分
 * {@link /api/points/createPointDetail}
 */
export function usePointsCreatePointDetail<TData = PointsCreatePointDetailMutationResponse, TQueryData = PointsCreatePointDetailMutationResponse, TQueryKey extends QueryKey = PointsCreatePointDetailQueryKey>(data?: PointsCreatePointDetailMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<PointsCreatePointDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsCreatePointDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsCreatePointDetailQueryKey(data)

  const query = useQuery({
   ...pointsCreatePointDetailQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}