/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsCreateLevelTypeMutationRequest, PointsCreateLevelTypeMutationResponse } from "../../types/pointsTypes/PointsCreateLevelType";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const pointsCreateLevelTypeQueryKey = (data?: PointsCreateLevelTypeMutationRequest) => [{ url: '/api/points/createLevelType' }, ...(data ? [data] : [])] as const

export type PointsCreateLevelTypeQueryKey = ReturnType<typeof pointsCreateLevelTypeQueryKey>

/**
 * @summary 创建等级类型
 * {@link /api/points/createLevelType}
 */
export async function pointsCreateLevelType(data?: PointsCreateLevelTypeMutationRequest, config: Partial<RequestConfig<PointsCreateLevelTypeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsCreateLevelTypeMutationResponse, ResponseErrorConfig<Error>, PointsCreateLevelTypeMutationRequest>({ method : "POST", url : `/api/points/createLevelType`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsCreateLevelTypeQueryOptions(data?: PointsCreateLevelTypeMutationRequest, config: Partial<RequestConfig<PointsCreateLevelTypeMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsCreateLevelTypeQueryKey(data)
  return queryOptions<PointsCreateLevelTypeMutationResponse, ResponseErrorConfig<Error>, PointsCreateLevelTypeMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsCreateLevelType(data, config)
   },
  })
}

/**
 * @summary 创建等级类型
 * {@link /api/points/createLevelType}
 */
export function usePointsCreateLevelType<TData = PointsCreateLevelTypeMutationResponse, TQueryData = PointsCreateLevelTypeMutationResponse, TQueryKey extends QueryKey = PointsCreateLevelTypeQueryKey>(data?: PointsCreateLevelTypeMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<PointsCreateLevelTypeMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsCreateLevelTypeMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsCreateLevelTypeQueryKey(data)

  const query = useQuery({
   ...pointsCreateLevelTypeQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}