/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsFindAccountPointAndLevelMutationRequest, PointsFindAccountPointAndLevelMutationResponse } from "../../types/pointsTypes/PointsFindAccountPointAndLevel";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const pointsFindAccountPointAndLevelQueryKey = (data?: PointsFindAccountPointAndLevelMutationRequest) => [{ url: '/api/points/findAccountPointAndLevel' }, ...(data ? [data] : [])] as const

export type PointsFindAccountPointAndLevelQueryKey = ReturnType<typeof pointsFindAccountPointAndLevelQueryKey>

/**
 * @summary 查询账户积分等级详情
 * {@link /api/points/findAccountPointAndLevel}
 */
export async function pointsFindAccountPointAndLevel(data?: PointsFindAccountPointAndLevelMutationRequest, config: Partial<RequestConfig<PointsFindAccountPointAndLevelMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsFindAccountPointAndLevelMutationResponse, ResponseErrorConfig<Error>, PointsFindAccountPointAndLevelMutationRequest>({ method : "POST", url : `/api/points/findAccountPointAndLevel`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsFindAccountPointAndLevelQueryOptions(data?: PointsFindAccountPointAndLevelMutationRequest, config: Partial<RequestConfig<PointsFindAccountPointAndLevelMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsFindAccountPointAndLevelQueryKey(data)
  return queryOptions<PointsFindAccountPointAndLevelMutationResponse, ResponseErrorConfig<Error>, PointsFindAccountPointAndLevelMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsFindAccountPointAndLevel(data, config)
   },
  })
}

/**
 * @summary 查询账户积分等级详情
 * {@link /api/points/findAccountPointAndLevel}
 */
export function usePointsFindAccountPointAndLevel<TData = PointsFindAccountPointAndLevelMutationResponse, TQueryData = PointsFindAccountPointAndLevelMutationResponse, TQueryKey extends QueryKey = PointsFindAccountPointAndLevelQueryKey>(data?: PointsFindAccountPointAndLevelMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<PointsFindAccountPointAndLevelMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsFindAccountPointAndLevelMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsFindAccountPointAndLevelQueryKey(data)

  const query = useQuery({
   ...pointsFindAccountPointAndLevelQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}