/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsFindPointTypeListMutationRequest, PointsFindPointTypeListMutationResponse } from "../../types/pointsTypes/PointsFindPointTypeList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const pointsFindPointTypeListSuspenseQueryKey = (data?: PointsFindPointTypeListMutationRequest) => [{ url: '/api/points/findPointTypeList' }, ...(data ? [data] : [])] as const

export type PointsFindPointTypeListSuspenseQueryKey = ReturnType<typeof pointsFindPointTypeListSuspenseQueryKey>

/**
 * @summary 查找积分类型
 * {@link /api/points/findPointTypeList}
 */
export async function pointsFindPointTypeListSuspense(data?: PointsFindPointTypeListMutationRequest, config: Partial<RequestConfig<PointsFindPointTypeListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsFindPointTypeListMutationResponse, ResponseErrorConfig<Error>, PointsFindPointTypeListMutationRequest>({ method : "POST", url : `/api/points/findPointTypeList`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsFindPointTypeListSuspenseQueryOptions(data?: PointsFindPointTypeListMutationRequest, config: Partial<RequestConfig<PointsFindPointTypeListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsFindPointTypeListSuspenseQueryKey(data)
  return queryOptions<PointsFindPointTypeListMutationResponse, ResponseErrorConfig<Error>, PointsFindPointTypeListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsFindPointTypeListSuspense(data, config)
   },
  })
}

/**
 * @summary 查找积分类型
 * {@link /api/points/findPointTypeList}
 */
export function usePointsFindPointTypeListSuspense<TData = PointsFindPointTypeListMutationResponse, TQueryKey extends QueryKey = PointsFindPointTypeListSuspenseQueryKey>(data?: PointsFindPointTypeListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<PointsFindPointTypeListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsFindPointTypeListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsFindPointTypeListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...pointsFindPointTypeListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}