/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsFindLevelTypeListMutationRequest, PointsFindLevelTypeListMutationResponse } from "../../types/pointsTypes/PointsFindLevelTypeList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const pointsFindLevelTypeListSuspenseQueryKey = (data?: PointsFindLevelTypeListMutationRequest) => [{ url: '/api/points/findLevelTypeList' }, ...(data ? [data] : [])] as const

export type PointsFindLevelTypeListSuspenseQueryKey = ReturnType<typeof pointsFindLevelTypeListSuspenseQueryKey>

/**
 * @summary 查询等级类型列表
 * {@link /api/points/findLevelTypeList}
 */
export async function pointsFindLevelTypeListSuspense(data?: PointsFindLevelTypeListMutationRequest, config: Partial<RequestConfig<PointsFindLevelTypeListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsFindLevelTypeListMutationResponse, ResponseErrorConfig<Error>, PointsFindLevelTypeListMutationRequest>({ method : "POST", url : `/api/points/findLevelTypeList`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsFindLevelTypeListSuspenseQueryOptions(data?: PointsFindLevelTypeListMutationRequest, config: Partial<RequestConfig<PointsFindLevelTypeListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsFindLevelTypeListSuspenseQueryKey(data)
  return queryOptions<PointsFindLevelTypeListMutationResponse, ResponseErrorConfig<Error>, PointsFindLevelTypeListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsFindLevelTypeListSuspense(data, config)
   },
  })
}

/**
 * @summary 查询等级类型列表
 * {@link /api/points/findLevelTypeList}
 */
export function usePointsFindLevelTypeListSuspense<TData = PointsFindLevelTypeListMutationResponse, TQueryKey extends QueryKey = PointsFindLevelTypeListSuspenseQueryKey>(data?: PointsFindLevelTypeListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<PointsFindLevelTypeListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsFindLevelTypeListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsFindLevelTypeListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...pointsFindLevelTypeListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}