/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsFindPointDetailListMutationRequest, PointsFindPointDetailListMutationResponse } from "../../types/pointsTypes/PointsFindPointDetailList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const pointsFindPointDetailListQueryKey = (data?: PointsFindPointDetailListMutationRequest) => [{ url: '/api/points/findPointDetailList' }, ...(data ? [data] : [])] as const

export type PointsFindPointDetailListQueryKey = ReturnType<typeof pointsFindPointDetailListQueryKey>

/**
 * @summary 查询积分明细列表
 * {@link /api/points/findPointDetailList}
 */
export async function pointsFindPointDetailList(data?: PointsFindPointDetailListMutationRequest, config: Partial<RequestConfig<PointsFindPointDetailListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsFindPointDetailListMutationResponse, ResponseErrorConfig<Error>, PointsFindPointDetailListMutationRequest>({ method : "POST", url : `/api/points/findPointDetailList`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsFindPointDetailListQueryOptions(data?: PointsFindPointDetailListMutationRequest, config: Partial<RequestConfig<PointsFindPointDetailListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsFindPointDetailListQueryKey(data)
  return queryOptions<PointsFindPointDetailListMutationResponse, ResponseErrorConfig<Error>, PointsFindPointDetailListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsFindPointDetailList(data, config)
   },
  })
}

/**
 * @summary 查询积分明细列表
 * {@link /api/points/findPointDetailList}
 */
export function usePointsFindPointDetailList<TData = PointsFindPointDetailListMutationResponse, TQueryData = PointsFindPointDetailListMutationResponse, TQueryKey extends QueryKey = PointsFindPointDetailListQueryKey>(data?: PointsFindPointDetailListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<PointsFindPointDetailListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsFindPointDetailListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsFindPointDetailListQueryKey(data)

  const query = useQuery({
   ...pointsFindPointDetailListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}