/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsFindLevelTypeListMutationRequest, PointsFindLevelTypeListMutationResponse } from "../../types/pointsTypes/PointsFindLevelTypeList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const pointsFindLevelTypeListQueryKey = (data?: PointsFindLevelTypeListMutationRequest) => [{ url: '/api/points/findLevelTypeList' }, ...(data ? [data] : [])] as const

export type PointsFindLevelTypeListQueryKey = ReturnType<typeof pointsFindLevelTypeListQueryKey>

/**
 * @summary 查询等级类型列表
 * {@link /api/points/findLevelTypeList}
 */
export async function pointsFindLevelTypeList(data?: PointsFindLevelTypeListMutationRequest, config: Partial<RequestConfig<PointsFindLevelTypeListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsFindLevelTypeListMutationResponse, ResponseErrorConfig<Error>, PointsFindLevelTypeListMutationRequest>({ method : "POST", url : `/api/points/findLevelTypeList`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsFindLevelTypeListQueryOptions(data?: PointsFindLevelTypeListMutationRequest, config: Partial<RequestConfig<PointsFindLevelTypeListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsFindLevelTypeListQueryKey(data)
  return queryOptions<PointsFindLevelTypeListMutationResponse, ResponseErrorConfig<Error>, PointsFindLevelTypeListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsFindLevelTypeList(data, config)
   },
  })
}

/**
 * @summary 查询等级类型列表
 * {@link /api/points/findLevelTypeList}
 */
export function usePointsFindLevelTypeList<TData = PointsFindLevelTypeListMutationResponse, TQueryData = PointsFindLevelTypeListMutationResponse, TQueryKey extends QueryKey = PointsFindLevelTypeListQueryKey>(data?: PointsFindLevelTypeListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<PointsFindLevelTypeListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsFindLevelTypeListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsFindLevelTypeListQueryKey(data)

  const query = useQuery({
   ...pointsFindLevelTypeListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}