/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { PointsCreatePointTypeMutationRequest, PointsCreatePointTypeMutationResponse } from "../../types/pointsTypes/PointsCreatePointType";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const pointsCreatePointTypeSuspenseQueryKey = (data?: PointsCreatePointTypeMutationRequest) => [{ url: '/api/points/createPointType' }, ...(data ? [data] : [])] as const

export type PointsCreatePointTypeSuspenseQueryKey = ReturnType<typeof pointsCreatePointTypeSuspenseQueryKey>

/**
 * @summary 创建积分类型
 * {@link /api/points/createPointType}
 */
export async function pointsCreatePointTypeSuspense(data?: PointsCreatePointTypeMutationRequest, config: Partial<RequestConfig<PointsCreatePointTypeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PointsCreatePointTypeMutationResponse, ResponseErrorConfig<Error>, PointsCreatePointTypeMutationRequest>({ method : "POST", url : `/api/points/createPointType`, data : requestData, ... requestConfig })  
  return res.data
}

export function pointsCreatePointTypeSuspenseQueryOptions(data?: PointsCreatePointTypeMutationRequest, config: Partial<RequestConfig<PointsCreatePointTypeMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = pointsCreatePointTypeSuspenseQueryKey(data)
  return queryOptions<PointsCreatePointTypeMutationResponse, ResponseErrorConfig<Error>, PointsCreatePointTypeMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return pointsCreatePointTypeSuspense(data, config)
   },
  })
}

/**
 * @summary 创建积分类型
 * {@link /api/points/createPointType}
 */
export function usePointsCreatePointTypeSuspense<TData = PointsCreatePointTypeMutationResponse, TQueryKey extends QueryKey = PointsCreatePointTypeSuspenseQueryKey>(data?: PointsCreatePointTypeMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<PointsCreatePointTypeMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<PointsCreatePointTypeMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? pointsCreatePointTypeSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...pointsCreatePointTypeSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}