/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TopicCommentAddReq } from "../v1/TopicCommentAddReq";
import type { V1TopicCommentAddRes } from "../v1/TopicCommentAddRes";

export type TopicCommentAdd200 = V1TopicCommentAddRes;

export type TopicCommentAddMutationRequest = V1TopicCommentAddReq;

export type TopicCommentAddMutationResponse = TopicCommentAdd200;

export type TopicCommentAddMutation = {
    Response: TopicCommentAdd200;
    Request: TopicCommentAddMutationRequest;
    Errors: any;
};