/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TopicCommentSubListReq } from "../v1/TopicCommentSubListReq";
import type { V1TopicCommentSubListRes } from "../v1/TopicCommentSubListRes";

export type TopicCommentSubList200 = V1TopicCommentSubListRes;

export type TopicCommentSubListMutationRequest = V1TopicCommentSubListReq;

export type TopicCommentSubListMutationResponse = TopicCommentSubList200;

export type TopicCommentSubListMutation = {
    Response: TopicCommentSubList200;
    Request: TopicCommentSubListMutationRequest;
    Errors: any;
};