/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommentLikeLikeMutationRequest, CommentLikeLikeMutationResponse } from "../../types/comment_likeTypes/CommentLikeLike";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const commentLikeLikeQueryKey = (data: CommentLikeLikeMutationRequest) => [{ url: '/api/comment_like/like' }, ...(data ? [data] : [])] as const

export type CommentLikeLikeQueryKey = ReturnType<typeof commentLikeLikeQueryKey>

/**
 * @summary 主题点赞
 * {@link /api/comment_like/like}
 */
export async function commentLikeLike(data: CommentLikeLikeMutationRequest, config: Partial<RequestConfig<CommentLikeLikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommentLikeLikeMutationResponse, ResponseErrorConfig<Error>, CommentLikeLikeMutationRequest>({ method : "POST", url : `/api/comment_like/like`, data : requestData, ... requestConfig })  
  return res.data
}

export function commentLikeLikeQueryOptions(data: CommentLikeLikeMutationRequest, config: Partial<RequestConfig<CommentLikeLikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commentLikeLikeQueryKey(data)
  return queryOptions<CommentLikeLikeMutationResponse, ResponseErrorConfig<Error>, CommentLikeLikeMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commentLikeLike(data, config)
   },
  })
}

/**
 * @summary 主题点赞
 * {@link /api/comment_like/like}
 */
export function useCommentLikeLike<TData = CommentLikeLikeMutationResponse, TQueryData = CommentLikeLikeMutationResponse, TQueryKey extends QueryKey = CommentLikeLikeQueryKey>(data: CommentLikeLikeMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<CommentLikeLikeMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommentLikeLikeMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commentLikeLikeQueryKey(data)

  const query = useQuery({
   ...commentLikeLikeQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}