/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommentLikeUnlikeMutationRequest, CommentLikeUnlikeMutationResponse } from "../../types/comment_likeTypes/CommentLikeUnlike";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const commentLikeUnlikeSuspenseQueryKey = (data: CommentLikeUnlikeMutationRequest) => [{ url: '/api/comment_like/unlike' }, ...(data ? [data] : [])] as const

export type CommentLikeUnlikeSuspenseQueryKey = ReturnType<typeof commentLikeUnlikeSuspenseQueryKey>

/**
 * @summary 主题取消点赞
 * {@link /api/comment_like/unlike}
 */
export async function commentLikeUnlikeSuspense(data: CommentLikeUnlikeMutationRequest, config: Partial<RequestConfig<CommentLikeUnlikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommentLikeUnlikeMutationResponse, ResponseErrorConfig<Error>, CommentLikeUnlikeMutationRequest>({ method : "POST", url : `/api/comment_like/unlike`, data : requestData, ... requestConfig })  
  return res.data
}

export function commentLikeUnlikeSuspenseQueryOptions(data: CommentLikeUnlikeMutationRequest, config: Partial<RequestConfig<CommentLikeUnlikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commentLikeUnlikeSuspenseQueryKey(data)
  return queryOptions<CommentLikeUnlikeMutationResponse, ResponseErrorConfig<Error>, CommentLikeUnlikeMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commentLikeUnlikeSuspense(data, config)
   },
  })
}

/**
 * @summary 主题取消点赞
 * {@link /api/comment_like/unlike}
 */
export function useCommentLikeUnlikeSuspense<TData = CommentLikeUnlikeMutationResponse, TQueryKey extends QueryKey = CommentLikeUnlikeSuspenseQueryKey>(data: CommentLikeUnlikeMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<CommentLikeUnlikeMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommentLikeUnlikeMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commentLikeUnlikeSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...commentLikeUnlikeSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}