/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsCreatePointTypeReq } from "../v1/PointsCreatePointTypeReq";
import type { V1PointsCreatePointTypeRes } from "../v1/PointsCreatePointTypeRes";

export type PointsCreatePointType200 = V1PointsCreatePointTypeRes;

export type PointsCreatePointTypeMutationRequest = V1PointsCreatePointTypeReq;

export type PointsCreatePointTypeMutationResponse = PointsCreatePointType200;

export type PointsCreatePointTypeMutation = {
    Response: PointsCreatePointType200;
    Request: PointsCreatePointTypeMutationRequest;
    Errors: any;
};