/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsFindPointDetailListReq } from "../v1/PointsFindPointDetailListReq";
import type { V1PointsFindPointDetailListRes } from "../v1/PointsFindPointDetailListRes";

export type PointsFindPointDetailList200 = V1PointsFindPointDetailListRes;

export type PointsFindPointDetailListMutationRequest = V1PointsFindPointDetailListReq;

export type PointsFindPointDetailListMutationResponse = PointsFindPointDetailList200;

export type PointsFindPointDetailListMutation = {
    Response: PointsFindPointDetailList200;
    Request: PointsFindPointDetailListMutationRequest;
    Errors: any;
};