/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsCreatePointDetailReq } from "../v1/PointsCreatePointDetailReq";
import type { V1PointsCreatePointDetailRes } from "../v1/PointsCreatePointDetailRes";

export type PointsCreatePointDetail200 = V1PointsCreatePointDetailRes;

export type PointsCreatePointDetailMutationRequest = V1PointsCreatePointDetailReq;

export type PointsCreatePointDetailMutationResponse = PointsCreatePointDetail200;

export type PointsCreatePointDetailMutation = {
    Response: PointsCreatePointDetail200;
    Request: PointsCreatePointDetailMutationRequest;
    Errors: any;
};