/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ModelListMutationRequest, ModelListMutationResponse } from "../../types/modelTypes/ModelList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const modelListSuspenseQueryKey = (data?: ModelListMutationRequest) => [{ url: '/api/model/list' }, ...(data ? [data] : [])] as const

export type ModelListSuspenseQueryKey = ReturnType<typeof modelListSuspenseQueryKey>

/**
 * @summary 模型列表
 * {@link /api/model/list}
 */
export async function modelListSuspense(data?: ModelListMutationRequest, config: Partial<RequestConfig<ModelListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ModelListMutationResponse, ResponseErrorConfig<Error>, ModelListMutationRequest>({ method : "POST", url : `/api/model/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function modelListSuspenseQueryOptions(data?: ModelListMutationRequest, config: Partial<RequestConfig<ModelListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = modelListSuspenseQueryKey(data)
  return queryOptions<ModelListMutationResponse, ResponseErrorConfig<Error>, ModelListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return modelListSuspense(data, config)
   },
  })
}

/**
 * @summary 模型列表
 * {@link /api/model/list}
 */
export function useModelListSuspense<TData = ModelListMutationResponse, TQueryKey extends QueryKey = ModelListSuspenseQueryKey>(data?: ModelListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ModelListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ModelListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? modelListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...modelListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}