/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ModelListMutationRequest, ModelListMutationResponse } from "../../types/modelTypes/ModelList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const modelListQueryKey = (data?: ModelListMutationRequest) => [{ url: '/api/model/list' }, ...(data ? [data] : [])] as const

export type ModelListQueryKey = ReturnType<typeof modelListQueryKey>

/**
 * @summary 模型列表
 * {@link /api/model/list}
 */
export async function modelList(data?: ModelListMutationRequest, config: Partial<RequestConfig<ModelListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ModelListMutationResponse, ResponseErrorConfig<Error>, ModelListMutationRequest>({ method : "POST", url : `/api/model/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function modelListQueryOptions(data?: ModelListMutationRequest, config: Partial<RequestConfig<ModelListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = modelListQueryKey(data)
  return queryOptions<ModelListMutationResponse, ResponseErrorConfig<Error>, ModelListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return modelList(data, config)
   },
  })
}

/**
 * @summary 模型列表
 * {@link /api/model/list}
 */
export function useModelList<TData = ModelListMutationResponse, TQueryData = ModelListMutationResponse, TQueryKey extends QueryKey = ModelListQueryKey>(data?: ModelListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ModelListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ModelListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? modelListQueryKey(data)

  const query = useQuery({
   ...modelListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}