/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatSynchronizeToken200, ChatSynchronizeTokenMutationRequest, ChatSynchronizeTokenMutationResponse } from "../../types/chatTypes/ChatSynchronizeToken";
import { v1ChatSynchronizeTokenReqSchema } from "../v1/chatSynchronizeTokenReqSchema";
import { v1ChatSynchronizeTokenResSchema } from "../v1/chatSynchronizeTokenResSchema";
import { z } from "zod/v4";

export const chatSynchronizeToken200Schema = v1ChatSynchronizeTokenResSchema as unknown as z.ZodType<ChatSynchronizeToken200>

export const chatSynchronizeTokenMutationRequestSchema = v1ChatSynchronizeTokenReqSchema as unknown as z.ZodType<ChatSynchronizeTokenMutationRequest>

export const chatSynchronizeTokenMutationResponseSchema = chatSynchronizeToken200Schema as unknown as z.ZodType<ChatSynchronizeTokenMutationResponse>