/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatTokenLimitStatus200, ChatTokenLimitStatusMutationRequest, ChatTokenLimitStatusMutationResponse } from "../../types/chatTypes/ChatTokenLimitStatus";
import { v1ChatTokenLimitStatusReqSchema } from "../v1/chatTokenLimitStatusReqSchema";
import { v1ChatTokenLimitStatusResSchema } from "../v1/chatTokenLimitStatusResSchema";
import { z } from "zod/v4";

export const chatTokenLimitStatus200Schema = v1ChatTokenLimitStatusResSchema as unknown as z.ZodType<ChatTokenLimitStatus200>

export const chatTokenLimitStatusMutationRequestSchema = v1ChatTokenLimitStatusReqSchema as unknown as z.ZodType<ChatTokenLimitStatusMutationRequest>

export const chatTokenLimitStatusMutationResponseSchema = chatTokenLimitStatus200Schema as unknown as z.ZodType<ChatTokenLimitStatusMutationResponse>