/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatImageLimitStatus200, ChatImageLimitStatusMutationRequest, ChatImageLimitStatusMutationResponse } from "../../types/chatTypes/ChatImageLimitStatus";
import { v1ChatImageLimitStatusReqSchema } from "../v1/chatImageLimitStatusReqSchema";
import { v1ChatImageLimitStatusResSchema } from "../v1/chatImageLimitStatusResSchema";
import { z } from "zod/v4";

export const chatImageLimitStatus200Schema = v1ChatImageLimitStatusResSchema as unknown as z.ZodType<ChatImageLimitStatus200>

export const chatImageLimitStatusMutationRequestSchema = v1ChatImageLimitStatusReqSchema as unknown as z.ZodType<ChatImageLimitStatusMutationRequest>

export const chatImageLimitStatusMutationResponseSchema = chatImageLimitStatus200Schema as unknown as z.ZodType<ChatImageLimitStatusMutationResponse>