/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskUserDone200, TaskUserDoneMutationRequest, TaskUserDoneMutationResponse } from "../../types/task_userTypes/TaskUserDone";
import { v1TaskUserDoneReqSchema } from "../v1/taskUserDoneReqSchema";
import { v1TaskUserDoneResSchema } from "../v1/taskUserDoneResSchema";
import { z } from "zod/v4";

export const taskUserDone200Schema = v1TaskUserDoneResSchema as unknown as z.ZodType<TaskUserDone200>

export const taskUserDoneMutationRequestSchema = v1TaskUserDoneReqSchema as unknown as z.ZodType<TaskUserDoneMutationRequest>

export const taskUserDoneMutationResponseSchema = taskUserDone200Schema as unknown as z.ZodType<TaskUserDoneMutationResponse>