/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { SessionDeleteMutationRequest, SessionDeleteMutationResponse } from "../../types/sessionTypes/SessionDelete";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const sessionDeleteQueryKey = (data: SessionDeleteMutationRequest) => [{ url: '/api/session/delete' }, ...(data ? [data] : [])] as const

export type SessionDeleteQueryKey = ReturnType<typeof sessionDeleteQueryKey>

/**
 * @summary 删除会话
 * {@link /api/session/delete}
 */
export async function sessionDelete(data: SessionDeleteMutationRequest, config: Partial<RequestConfig<SessionDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SessionDeleteMutationResponse, ResponseErrorConfig<Error>, SessionDeleteMutationRequest>({ method : "POST", url : `/api/session/delete`, data : requestData, ... requestConfig })  
  return res.data
}

export function sessionDeleteQueryOptions(data: SessionDeleteMutationRequest, config: Partial<RequestConfig<SessionDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = sessionDeleteQueryKey(data)
  return queryOptions<SessionDeleteMutationResponse, ResponseErrorConfig<Error>, SessionDeleteMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return sessionDelete(data, config)
   },
  })
}

/**
 * @summary 删除会话
 * {@link /api/session/delete}
 */
export function useSessionDelete<TData = SessionDeleteMutationResponse, TQueryData = SessionDeleteMutationResponse, TQueryKey extends QueryKey = SessionDeleteQueryKey>(data: SessionDeleteMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<SessionDeleteMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<SessionDeleteMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? sessionDeleteQueryKey(data)

  const query = useQuery({
   ...sessionDeleteQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}