/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { SessionListMutationRequest, SessionListMutationResponse } from "../../types/sessionTypes/SessionList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const sessionListSuspenseQueryKey = (data: SessionListMutationRequest) => [{ url: '/api/session/list' }, ...(data ? [data] : [])] as const

export type SessionListSuspenseQueryKey = ReturnType<typeof sessionListSuspenseQueryKey>

/**
 * @summary 获取会话列表
 * {@link /api/session/list}
 */
export async function sessionListSuspense(data: SessionListMutationRequest, config: Partial<RequestConfig<SessionListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SessionListMutationResponse, ResponseErrorConfig<Error>, SessionListMutationRequest>({ method : "POST", url : `/api/session/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function sessionListSuspenseQueryOptions(data: SessionListMutationRequest, config: Partial<RequestConfig<SessionListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = sessionListSuspenseQueryKey(data)
  return queryOptions<SessionListMutationResponse, ResponseErrorConfig<Error>, SessionListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return sessionListSuspense(data, config)
   },
  })
}

/**
 * @summary 获取会话列表
 * {@link /api/session/list}
 */
export function useSessionListSuspense<TData = SessionListMutationResponse, TQueryKey extends QueryKey = SessionListSuspenseQueryKey>(data: SessionListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<SessionListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<SessionListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? sessionListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...sessionListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}