/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { SessionCreateMutationRequest, SessionCreateMutationResponse } from "../../types/sessionTypes/SessionCreate";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const sessionCreateQueryKey = (data?: SessionCreateMutationRequest) => [{ url: '/api/session/create' }, ...(data ? [data] : [])] as const

export type SessionCreateQueryKey = ReturnType<typeof sessionCreateQueryKey>

/**
 * @summary 创建会话
 * {@link /api/session/create}
 */
export async function sessionCreate(data?: SessionCreateMutationRequest, config: Partial<RequestConfig<SessionCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SessionCreateMutationResponse, ResponseErrorConfig<Error>, SessionCreateMutationRequest>({ method : "POST", url : `/api/session/create`, data : requestData, ... requestConfig })  
  return res.data
}

export function sessionCreateQueryOptions(data?: SessionCreateMutationRequest, config: Partial<RequestConfig<SessionCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = sessionCreateQueryKey(data)
  return queryOptions<SessionCreateMutationResponse, ResponseErrorConfig<Error>, SessionCreateMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return sessionCreate(data, config)
   },
  })
}

/**
 * @summary 创建会话
 * {@link /api/session/create}
 */
export function useSessionCreate<TData = SessionCreateMutationResponse, TQueryData = SessionCreateMutationResponse, TQueryKey extends QueryKey = SessionCreateQueryKey>(data?: SessionCreateMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<SessionCreateMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<SessionCreateMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? sessionCreateQueryKey(data)

  const query = useQuery({
   ...sessionCreateQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}