/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { SessionDetailMutationRequest, SessionDetailMutationResponse } from "../../types/sessionTypes/SessionDetail";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const sessionDetailQueryKey = (data: SessionDetailMutationRequest) => [{ url: '/api/session/detail' }, ...(data ? [data] : [])] as const

export type SessionDetailQueryKey = ReturnType<typeof sessionDetailQueryKey>

/**
 * @summary 获取会话详情
 * {@link /api/session/detail}
 */
export async function sessionDetail(data: SessionDetailMutationRequest, config: Partial<RequestConfig<SessionDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SessionDetailMutationResponse, ResponseErrorConfig<Error>, SessionDetailMutationRequest>({ method : "POST", url : `/api/session/detail`, data : requestData, ... requestConfig })  
  return res.data
}

export function sessionDetailQueryOptions(data: SessionDetailMutationRequest, config: Partial<RequestConfig<SessionDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = sessionDetailQueryKey(data)
  return queryOptions<SessionDetailMutationResponse, ResponseErrorConfig<Error>, SessionDetailMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return sessionDetail(data, config)
   },
  })
}

/**
 * @summary 获取会话详情
 * {@link /api/session/detail}
 */
export function useSessionDetail<TData = SessionDetailMutationResponse, TQueryData = SessionDetailMutationResponse, TQueryKey extends QueryKey = SessionDetailQueryKey>(data: SessionDetailMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<SessionDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<SessionDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? sessionDetailQueryKey(data)

  const query = useQuery({
   ...sessionDetailQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}