/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { SessionRenameMutationRequest, SessionRenameMutationResponse } from "../../types/sessionTypes/SessionRename";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const sessionRenameQueryKey = (data: SessionRenameMutationRequest) => [{ url: '/api/session/rename' }, ...(data ? [data] : [])] as const

export type SessionRenameQueryKey = ReturnType<typeof sessionRenameQueryKey>

/**
 * @summary 修改会话名称
 * {@link /api/session/rename}
 */
export async function sessionRename(data: SessionRenameMutationRequest, config: Partial<RequestConfig<SessionRenameMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SessionRenameMutationResponse, ResponseErrorConfig<Error>, SessionRenameMutationRequest>({ method : "POST", url : `/api/session/rename`, data : requestData, ... requestConfig })  
  return res.data
}

export function sessionRenameQueryOptions(data: SessionRenameMutationRequest, config: Partial<RequestConfig<SessionRenameMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = sessionRenameQueryKey(data)
  return queryOptions<SessionRenameMutationResponse, ResponseErrorConfig<Error>, SessionRenameMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return sessionRename(data, config)
   },
  })
}

/**
 * @summary 修改会话名称
 * {@link /api/session/rename}
 */
export function useSessionRename<TData = SessionRenameMutationResponse, TQueryData = SessionRenameMutationResponse, TQueryKey extends QueryKey = SessionRenameQueryKey>(data: SessionRenameMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<SessionRenameMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<SessionRenameMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? sessionRenameQueryKey(data)

  const query = useQuery({
   ...sessionRenameQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}