/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { SessionDeleteMutationRequest, SessionDeleteMutationResponse } from "../../types/sessionTypes/SessionDelete";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const sessionDeleteSuspenseQueryKey = (data: SessionDeleteMutationRequest) => [{ url: '/api/session/delete' }, ...(data ? [data] : [])] as const

export type SessionDeleteSuspenseQueryKey = ReturnType<typeof sessionDeleteSuspenseQueryKey>

/**
 * @summary 删除会话
 * {@link /api/session/delete}
 */
export async function sessionDeleteSuspense(data: SessionDeleteMutationRequest, config: Partial<RequestConfig<SessionDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SessionDeleteMutationResponse, ResponseErrorConfig<Error>, SessionDeleteMutationRequest>({ method : "POST", url : `/api/session/delete`, data : requestData, ... requestConfig })  
  return res.data
}

export function sessionDeleteSuspenseQueryOptions(data: SessionDeleteMutationRequest, config: Partial<RequestConfig<SessionDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = sessionDeleteSuspenseQueryKey(data)
  return queryOptions<SessionDeleteMutationResponse, ResponseErrorConfig<Error>, SessionDeleteMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return sessionDeleteSuspense(data, config)
   },
  })
}

/**
 * @summary 删除会话
 * {@link /api/session/delete}
 */
export function useSessionDeleteSuspense<TData = SessionDeleteMutationResponse, TQueryKey extends QueryKey = SessionDeleteSuspenseQueryKey>(data: SessionDeleteMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<SessionDeleteMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<SessionDeleteMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? sessionDeleteSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...sessionDeleteSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}