/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { SessionDetailMutationRequest, SessionDetailMutationResponse } from "../../types/sessionTypes/SessionDetail";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const sessionDetailSuspenseQueryKey = (data: SessionDetailMutationRequest) => [{ url: '/api/session/detail' }, ...(data ? [data] : [])] as const

export type SessionDetailSuspenseQueryKey = ReturnType<typeof sessionDetailSuspenseQueryKey>

/**
 * @summary 获取会话详情
 * {@link /api/session/detail}
 */
export async function sessionDetailSuspense(data: SessionDetailMutationRequest, config: Partial<RequestConfig<SessionDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SessionDetailMutationResponse, ResponseErrorConfig<Error>, SessionDetailMutationRequest>({ method : "POST", url : `/api/session/detail`, data : requestData, ... requestConfig })  
  return res.data
}

export function sessionDetailSuspenseQueryOptions(data: SessionDetailMutationRequest, config: Partial<RequestConfig<SessionDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = sessionDetailSuspenseQueryKey(data)
  return queryOptions<SessionDetailMutationResponse, ResponseErrorConfig<Error>, SessionDetailMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return sessionDetailSuspense(data, config)
   },
  })
}

/**
 * @summary 获取会话详情
 * {@link /api/session/detail}
 */
export function useSessionDetailSuspense<TData = SessionDetailMutationResponse, TQueryKey extends QueryKey = SessionDetailSuspenseQueryKey>(data: SessionDetailMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<SessionDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<SessionDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? sessionDetailSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...sessionDetailSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}