/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { SessionListMutationRequest, SessionListMutationResponse } from "../../types/sessionTypes/SessionList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const sessionListQueryKey = (data: SessionListMutationRequest) => [{ url: '/api/session/list' }, ...(data ? [data] : [])] as const

export type SessionListQueryKey = ReturnType<typeof sessionListQueryKey>

/**
 * @summary 获取会话列表
 * {@link /api/session/list}
 */
export async function sessionList(data: SessionListMutationRequest, config: Partial<RequestConfig<SessionListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SessionListMutationResponse, ResponseErrorConfig<Error>, SessionListMutationRequest>({ method : "POST", url : `/api/session/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function sessionListQueryOptions(data: SessionListMutationRequest, config: Partial<RequestConfig<SessionListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = sessionListQueryKey(data)
  return queryOptions<SessionListMutationResponse, ResponseErrorConfig<Error>, SessionListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return sessionList(data, config)
   },
  })
}

/**
 * @summary 获取会话列表
 * {@link /api/session/list}
 */
export function useSessionList<TData = SessionListMutationResponse, TQueryData = SessionListMutationResponse, TQueryKey extends QueryKey = SessionListQueryKey>(data: SessionListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<SessionListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<SessionListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? sessionListQueryKey(data)

  const query = useQuery({
   ...sessionListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}