/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NotificationList200, NotificationListMutationRequest, NotificationListMutationResponse } from "../../types/notificationTypes/NotificationList";
import { v1NotificationListReqSchema } from "../v1/notificationListReqSchema";
import { v1NotificationListResSchema } from "../v1/notificationListResSchema";
import { z } from "zod/v4";

export const notificationList200Schema = v1NotificationListResSchema as unknown as z.ZodType<NotificationList200>

export const notificationListMutationRequestSchema = v1NotificationListReqSchema as unknown as z.ZodType<NotificationListMutationRequest>

export const notificationListMutationResponseSchema = notificationList200Schema as unknown as z.ZodType<NotificationListMutationResponse>