/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommentLikeUnLikeReq } from "../v1/CommentLikeUnLikeReq";
import type { V1CommentLikeUnLikeRes } from "../v1/CommentLikeUnLikeRes";

export type CommentLikeUnlike200 = V1CommentLikeUnLikeRes;

export type CommentLikeUnlikeMutationRequest = V1CommentLikeUnLikeReq;

export type CommentLikeUnlikeMutationResponse = CommentLikeUnlike200;

export type CommentLikeUnlikeMutation = {
    Response: CommentLikeUnlike200;
    Request: CommentLikeUnlikeMutationRequest;
    Errors: any;
};