/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommentLikeLikeReq } from "../v1/CommentLikeLikeReq";
import type { V1CommentLikeLikeRes } from "../v1/CommentLikeLikeRes";

export type CommentLikeLike200 = V1CommentLikeLikeRes;

export type CommentLikeLikeMutationRequest = V1CommentLikeLikeReq;

export type CommentLikeLikeMutationResponse = CommentLikeLike200;

export type CommentLikeLikeMutation = {
    Response: CommentLikeLike200;
    Request: CommentLikeLikeMutationRequest;
    Errors: any;
};