/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { OuterExportMutationRequest, OuterExportMutationResponse } from "../../types/outerTypes/OuterExport";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const outerExportQueryKey = (data: OuterExportMutationRequest) => [{ url: '/api/outer/export' }, ...(data ? [data] : [])] as const

export type OuterExportQueryKey = ReturnType<typeof outerExportQueryKey>

/**
 * @summary 对话历史导出
 * {@link /api/outer/export}
 */
export async function outerExport(data: OuterExportMutationRequest, config: Partial<RequestConfig<OuterExportMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<OuterExportMutationResponse, ResponseErrorConfig<Error>, OuterExportMutationRequest>({ method : "POST", url : `/api/outer/export`, data : requestData, ... requestConfig })  
  return res.data
}

export function outerExportQueryOptions(data: OuterExportMutationRequest, config: Partial<RequestConfig<OuterExportMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = outerExportQueryKey(data)
  return queryOptions<OuterExportMutationResponse, ResponseErrorConfig<Error>, OuterExportMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return outerExport(data, config)
   },
  })
}

/**
 * @summary 对话历史导出
 * {@link /api/outer/export}
 */
export function useOuterExport<TData = OuterExportMutationResponse, TQueryData = OuterExportMutationResponse, TQueryKey extends QueryKey = OuterExportQueryKey>(data: OuterExportMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<OuterExportMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<OuterExportMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? outerExportQueryKey(data)

  const query = useQuery({
   ...outerExportQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}