/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { OuterExportMutationRequest, OuterExportMutationResponse } from "../../types/outerTypes/OuterExport";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const outerExportSuspenseQueryKey = (data: OuterExportMutationRequest) => [{ url: '/api/outer/export' }, ...(data ? [data] : [])] as const

export type OuterExportSuspenseQueryKey = ReturnType<typeof outerExportSuspenseQueryKey>

/**
 * @summary 对话历史导出
 * {@link /api/outer/export}
 */
export async function outerExportSuspense(data: OuterExportMutationRequest, config: Partial<RequestConfig<OuterExportMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<OuterExportMutationResponse, ResponseErrorConfig<Error>, OuterExportMutationRequest>({ method : "POST", url : `/api/outer/export`, data : requestData, ... requestConfig })  
  return res.data
}

export function outerExportSuspenseQueryOptions(data: OuterExportMutationRequest, config: Partial<RequestConfig<OuterExportMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = outerExportSuspenseQueryKey(data)
  return queryOptions<OuterExportMutationResponse, ResponseErrorConfig<Error>, OuterExportMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return outerExportSuspense(data, config)
   },
  })
}

/**
 * @summary 对话历史导出
 * {@link /api/outer/export}
 */
export function useOuterExportSuspense<TData = OuterExportMutationResponse, TQueryKey extends QueryKey = OuterExportSuspenseQueryKey>(data: OuterExportMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<OuterExportMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<OuterExportMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? outerExportSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...outerExportSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}