/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { OuterAccountExistMutationRequest, OuterAccountExistMutationResponse } from "../../types/outerTypes/OuterAccountExist";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const outerAccountExistQueryKey = (data: OuterAccountExistMutationRequest) => [{ url: '/api/outer/account_exist' }, ...(data ? [data] : [])] as const

export type OuterAccountExistQueryKey = ReturnType<typeof outerAccountExistQueryKey>

/**
 * @summary 检查用户是否存在
 * {@link /api/outer/account_exist}
 */
export async function outerAccountExist(data: OuterAccountExistMutationRequest, config: Partial<RequestConfig<OuterAccountExistMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<OuterAccountExistMutationResponse, ResponseErrorConfig<Error>, OuterAccountExistMutationRequest>({ method : "POST", url : `/api/outer/account_exist`, data : requestData, ... requestConfig })  
  return res.data
}

export function outerAccountExistQueryOptions(data: OuterAccountExistMutationRequest, config: Partial<RequestConfig<OuterAccountExistMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = outerAccountExistQueryKey(data)
  return queryOptions<OuterAccountExistMutationResponse, ResponseErrorConfig<Error>, OuterAccountExistMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return outerAccountExist(data, config)
   },
  })
}

/**
 * @summary 检查用户是否存在
 * {@link /api/outer/account_exist}
 */
export function useOuterAccountExist<TData = OuterAccountExistMutationResponse, TQueryData = OuterAccountExistMutationResponse, TQueryKey extends QueryKey = OuterAccountExistQueryKey>(data: OuterAccountExistMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<OuterAccountExistMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<OuterAccountExistMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? outerAccountExistQueryKey(data)

  const query = useQuery({
   ...outerAccountExistQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}