/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { OuterAccountExistMutationRequest, OuterAccountExistMutationResponse } from "../../types/outerTypes/OuterAccountExist";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const outerAccountExistSuspenseQueryKey = (data: OuterAccountExistMutationRequest) => [{ url: '/api/outer/account_exist' }, ...(data ? [data] : [])] as const

export type OuterAccountExistSuspenseQueryKey = ReturnType<typeof outerAccountExistSuspenseQueryKey>

/**
 * @summary 检查用户是否存在
 * {@link /api/outer/account_exist}
 */
export async function outerAccountExistSuspense(data: OuterAccountExistMutationRequest, config: Partial<RequestConfig<OuterAccountExistMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<OuterAccountExistMutationResponse, ResponseErrorConfig<Error>, OuterAccountExistMutationRequest>({ method : "POST", url : `/api/outer/account_exist`, data : requestData, ... requestConfig })  
  return res.data
}

export function outerAccountExistSuspenseQueryOptions(data: OuterAccountExistMutationRequest, config: Partial<RequestConfig<OuterAccountExistMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = outerAccountExistSuspenseQueryKey(data)
  return queryOptions<OuterAccountExistMutationResponse, ResponseErrorConfig<Error>, OuterAccountExistMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return outerAccountExistSuspense(data, config)
   },
  })
}

/**
 * @summary 检查用户是否存在
 * {@link /api/outer/account_exist}
 */
export function useOuterAccountExistSuspense<TData = OuterAccountExistMutationResponse, TQueryKey extends QueryKey = OuterAccountExistSuspenseQueryKey>(data: OuterAccountExistMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<OuterAccountExistMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<OuterAccountExistMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? outerAccountExistSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...outerAccountExistSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}