/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskUserListReq } from "../v1/TaskUserListReq";
import type { V1TaskUserListRes } from "../v1/TaskUserListRes";

export type TaskUserList200 = V1TaskUserListRes;

export type TaskUserListMutationRequest = V1TaskUserListReq;

export type TaskUserListMutationResponse = TaskUserList200;

export type TaskUserListMutation = {
    Response: TaskUserList200;
    Request: TaskUserListMutationRequest;
    Errors: any;
};