/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskUserUndoneReq } from "../v1/TaskUserUndoneReq";
import type { V1TaskUserUndoneRes } from "../v1/TaskUserUndoneRes";

export type TaskUserUndone200 = V1TaskUserUndoneRes;

export type TaskUserUndoneMutationRequest = V1TaskUserUndoneReq;

export type TaskUserUndoneMutationResponse = TaskUserUndone200;

export type TaskUserUndoneMutation = {
    Response: TaskUserUndone200;
    Request: TaskUserUndoneMutationRequest;
    Errors: any;
};