/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskUserDoneReq } from "../v1/TaskUserDoneReq";
import type { V1TaskUserDoneRes } from "../v1/TaskUserDoneRes";

export type TaskUserDone200 = V1TaskUserDoneRes;

export type TaskUserDoneMutationRequest = V1TaskUserDoneReq;

export type TaskUserDoneMutationResponse = TaskUserDone200;

export type TaskUserDoneMutation = {
    Response: TaskUserDone200;
    Request: TaskUserDoneMutationRequest;
    Errors: any;
};