/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CommonAddUser200, CommonAddUserMutationRequest, CommonAddUserMutationResponse } from "../../types/commonTypes/CommonAddUser";
import { v1CommonAddUserReqSchema } from "../v1/commonAddUserReqSchema";
import { v1CommonAddUserResSchema } from "../v1/commonAddUserResSchema";
import { z } from "zod/v4";

export const commonAddUser200Schema = v1CommonAddUserResSchema as unknown as z.ZodType<CommonAddUser200>

export const commonAddUserMutationRequestSchema = v1CommonAddUserReqSchema as unknown as z.ZodType<CommonAddUserMutationRequest>

export const commonAddUserMutationResponseSchema = commonAddUser200Schema as unknown as z.ZodType<CommonAddUserMutationResponse>