/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CommonResetPassword200, CommonResetPasswordMutationRequest, CommonResetPasswordMutationResponse } from "../../types/commonTypes/CommonResetPassword";
import { v1CommonResetPasswordReqSchema } from "../v1/commonResetPasswordReqSchema";
import { v1CommonResetPasswordResSchema } from "../v1/commonResetPasswordResSchema";
import { z } from "zod/v4";

export const commonResetPassword200Schema = v1CommonResetPasswordResSchema as unknown as z.ZodType<CommonResetPassword200>

export const commonResetPasswordMutationRequestSchema = v1CommonResetPasswordReqSchema as unknown as z.ZodType<CommonResetPasswordMutationRequest>

export const commonResetPasswordMutationResponseSchema = commonResetPassword200Schema as unknown as z.ZodType<CommonResetPasswordMutationResponse>