/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatStopReq } from "../v1/ChatStopReq";
import type { V1ChatStopRes } from "../v1/ChatStopRes";

export type ChatStop200 = V1ChatStopRes;

export type ChatStopMutationRequest = V1ChatStopReq;

export type ChatStopMutationResponse = ChatStop200;

export type ChatStopMutation = {
    Response: ChatStop200;
    Request: ChatStopMutationRequest;
    Errors: any;
};