/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatCompletionsReq } from "../v1/ChatCompletionsReq";
import type { V1ChatCompletionsRes } from "../v1/ChatCompletionsRes";

export type ChatCompletions200 = V1ChatCompletionsRes;

export type ChatCompletionsMutationRequest = V1ChatCompletionsReq;

export type ChatCompletionsMutationResponse = ChatCompletions200;

export type ChatCompletionsMutation = {
    Response: ChatCompletions200;
    Request: ChatCompletionsMutationRequest;
    Errors: any;
};