/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatImageLimitStatusReq } from "../v1/ChatImageLimitStatusReq";
import type { V1ChatImageLimitStatusRes } from "../v1/ChatImageLimitStatusRes";

export type ChatImageLimitStatus200 = V1ChatImageLimitStatusRes;

export type ChatImageLimitStatusMutationRequest = V1ChatImageLimitStatusReq;

export type ChatImageLimitStatusMutationResponse = ChatImageLimitStatus200;

export type ChatImageLimitStatusMutation = {
    Response: ChatImageLimitStatus200;
    Request: ChatImageLimitStatusMutationRequest;
    Errors: any;
};