/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatSearchLimitStatusReq } from "../v1/ChatSearchLimitStatusReq";
import type { V1ChatSearchLimitStatusRes } from "../v1/ChatSearchLimitStatusRes";

export type ChatSearchLimitStatus200 = V1ChatSearchLimitStatusRes;

export type ChatSearchLimitStatusMutationRequest = V1ChatSearchLimitStatusReq;

export type ChatSearchLimitStatusMutationResponse = ChatSearchLimitStatus200;

export type ChatSearchLimitStatusMutation = {
    Response: ChatSearchLimitStatus200;
    Request: ChatSearchLimitStatusMutationRequest;
    Errors: any;
};