/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskTopicDetailReq } from "../v1/TaskTopicDetailReq";
import type { V1TaskTopicDetailRes } from "../v1/TaskTopicDetailRes";

export type TaskTopicDetail200 = V1TaskTopicDetailRes;

export type TaskTopicDetailMutationRequest = V1TaskTopicDetailReq;

export type TaskTopicDetailMutationResponse = TaskTopicDetail200;

export type TaskTopicDetailMutation = {
    Response: TaskTopicDetail200;
    Request: TaskTopicDetailMutationRequest;
    Errors: any;
};