/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskTopicDeleteReq } from "../v1/TaskTopicDeleteReq";
import type { V1TaskTopicDeleteRes } from "../v1/TaskTopicDeleteRes";

export type TaskTopicDelete200 = V1TaskTopicDeleteRes;

export type TaskTopicDeleteMutationRequest = V1TaskTopicDeleteReq;

export type TaskTopicDeleteMutationResponse = TaskTopicDelete200;

export type TaskTopicDeleteMutation = {
    Response: TaskTopicDelete200;
    Request: TaskTopicDeleteMutationRequest;
    Errors: any;
};