/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountLogout200, AccountLogoutMutationRequest, AccountLogoutMutationResponse } from "../../types/accountTypes/AccountLogout";
import { v1AccountLogoutReqSchema } from "../v1/accountLogoutReqSchema";
import { v1AccountLogoutResSchema } from "../v1/accountLogoutResSchema";
import { z } from "zod/v4";

export const accountLogout200Schema = v1AccountLogoutResSchema as unknown as z.ZodType<AccountLogout200>

export const accountLogoutMutationRequestSchema = v1AccountLogoutReqSchema as unknown as z.ZodType<AccountLogoutMutationRequest>

export const accountLogoutMutationResponseSchema = accountLogout200Schema as unknown as z.ZodType<AccountLogoutMutationResponse>