/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountAvatar200, AccountAvatarMutationRequest, AccountAvatarMutationResponse } from "../../types/accountTypes/AccountAvatar";
import { v1AccountAvatarReqSchema } from "../v1/accountAvatarReqSchema";
import { v1AccountAvatarResSchema } from "../v1/accountAvatarResSchema";
import { z } from "zod/v4";

export const accountAvatar200Schema = v1AccountAvatarResSchema as unknown as z.ZodType<AccountAvatar200>

export const accountAvatarMutationRequestSchema = v1AccountAvatarReqSchema as unknown as z.ZodType<AccountAvatarMutationRequest>

export const accountAvatarMutationResponseSchema = accountAvatar200Schema as unknown as z.ZodType<AccountAvatarMutationResponse>