/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountInfo200, AccountInfoQueryResponse } from "../../types/accountTypes/AccountInfo";
import { v1AccountInfoResSchema } from "../v1/accountInfoResSchema";
import { z } from "zod/v4";

export const accountInfo200Schema = v1AccountInfoResSchema as unknown as z.ZodType<AccountInfo200>

export const accountInfoQueryResponseSchema = accountInfo200Schema as unknown as z.ZodType<AccountInfoQueryResponse>