/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AccountTopicList200, AccountTopicListMutationRequest, AccountTopicListMutationResponse } from "../../types/accountTypes/AccountTopicList";
import { v1AccountTopicListReqSchema } from "../v1/accountTopicListReqSchema";
import { v1AccountTopicListResSchema } from "../v1/accountTopicListResSchema";
import { z } from "zod/v4";

export const accountTopicList200Schema = v1AccountTopicListResSchema as unknown as z.ZodType<AccountTopicList200>

export const accountTopicListMutationRequestSchema = v1AccountTopicListReqSchema as unknown as z.ZodType<AccountTopicListMutationRequest>

export const accountTopicListMutationResponseSchema = accountTopicList200Schema as unknown as z.ZodType<AccountTopicListMutationResponse>