/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountChangeNicknameMutationRequest, AccountChangeNicknameMutationResponse } from "../../types/accountTypes/AccountChangeNickname";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountChangeNicknameSuspenseQueryKey = (data: AccountChangeNicknameMutationRequest) => [{ url: '/api/account/change_nickname' }, ...(data ? [data] : [])] as const

export type AccountChangeNicknameSuspenseQueryKey = ReturnType<typeof accountChangeNicknameSuspenseQueryKey>

/**
 * @summary 修改昵称
 * {@link /api/account/change_nickname}
 */
export async function accountChangeNicknameSuspense(data: AccountChangeNicknameMutationRequest, config: Partial<RequestConfig<AccountChangeNicknameMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountChangeNicknameMutationResponse, ResponseErrorConfig<Error>, AccountChangeNicknameMutationRequest>({ method : "POST", url : `/api/account/change_nickname`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountChangeNicknameSuspenseQueryOptions(data: AccountChangeNicknameMutationRequest, config: Partial<RequestConfig<AccountChangeNicknameMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountChangeNicknameSuspenseQueryKey(data)
  return queryOptions<AccountChangeNicknameMutationResponse, ResponseErrorConfig<Error>, AccountChangeNicknameMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountChangeNicknameSuspense(data, config)
   },
  })
}

/**
 * @summary 修改昵称
 * {@link /api/account/change_nickname}
 */
export function useAccountChangeNicknameSuspense<TData = AccountChangeNicknameMutationResponse, TQueryKey extends QueryKey = AccountChangeNicknameSuspenseQueryKey>(data: AccountChangeNicknameMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountChangeNicknameMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountChangeNicknameMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountChangeNicknameSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...accountChangeNicknameSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}