/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountChangeNicknameMutationRequest, AccountChangeNicknameMutationResponse } from "../../types/accountTypes/AccountChangeNickname";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountChangeNicknameQueryKey = (data: AccountChangeNicknameMutationRequest) => [{ url: '/api/account/change_nickname' }, ...(data ? [data] : [])] as const

export type AccountChangeNicknameQueryKey = ReturnType<typeof accountChangeNicknameQueryKey>

/**
 * @summary 修改昵称
 * {@link /api/account/change_nickname}
 */
export async function accountChangeNickname(data: AccountChangeNicknameMutationRequest, config: Partial<RequestConfig<AccountChangeNicknameMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountChangeNicknameMutationResponse, ResponseErrorConfig<Error>, AccountChangeNicknameMutationRequest>({ method : "POST", url : `/api/account/change_nickname`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountChangeNicknameQueryOptions(data: AccountChangeNicknameMutationRequest, config: Partial<RequestConfig<AccountChangeNicknameMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountChangeNicknameQueryKey(data)
  return queryOptions<AccountChangeNicknameMutationResponse, ResponseErrorConfig<Error>, AccountChangeNicknameMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountChangeNickname(data, config)
   },
  })
}

/**
 * @summary 修改昵称
 * {@link /api/account/change_nickname}
 */
export function useAccountChangeNickname<TData = AccountChangeNicknameMutationResponse, TQueryData = AccountChangeNicknameMutationResponse, TQueryKey extends QueryKey = AccountChangeNicknameQueryKey>(data: AccountChangeNicknameMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<AccountChangeNicknameMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountChangeNicknameMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountChangeNicknameQueryKey(data)

  const query = useQuery({
   ...accountChangeNicknameQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}