/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountInfoQueryResponse } from "../../types/accountTypes/AccountInfo";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountInfoSuspenseQueryKey = () => [{ url: '/api/account/info' }] as const

export type AccountInfoSuspenseQueryKey = ReturnType<typeof accountInfoSuspenseQueryKey>

/**
 * @summary 获取当前登录用户信息
 * {@link /api/account/info}
 */
export async function accountInfoSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AccountInfoQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/account/info`, ... requestConfig })  
  return res.data
}

export function accountInfoSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = accountInfoSuspenseQueryKey()
  return queryOptions<AccountInfoQueryResponse, ResponseErrorConfig<Error>, AccountInfoQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountInfoSuspense(config)
   },
  })
}

/**
 * @summary 获取当前登录用户信息
 * {@link /api/account/info}
 */
export function useAccountInfoSuspense<TData = AccountInfoQueryResponse, TQueryKey extends QueryKey = AccountInfoSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountInfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountInfoSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...accountInfoSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}