/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountLogoutMutationRequest, AccountLogoutMutationResponse } from "../../types/accountTypes/AccountLogout";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountLogoutSuspenseQueryKey = (data?: AccountLogoutMutationRequest) => [{ url: '/api/account/logout' }, ...(data ? [data] : [])] as const

export type AccountLogoutSuspenseQueryKey = ReturnType<typeof accountLogoutSuspenseQueryKey>

/**
 * @summary 登出
 * {@link /api/account/logout}
 */
export async function accountLogoutSuspense(data?: AccountLogoutMutationRequest, config: Partial<RequestConfig<AccountLogoutMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountLogoutMutationResponse, ResponseErrorConfig<Error>, AccountLogoutMutationRequest>({ method : "POST", url : `/api/account/logout`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountLogoutSuspenseQueryOptions(data?: AccountLogoutMutationRequest, config: Partial<RequestConfig<AccountLogoutMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountLogoutSuspenseQueryKey(data)
  return queryOptions<AccountLogoutMutationResponse, ResponseErrorConfig<Error>, AccountLogoutMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountLogoutSuspense(data, config)
   },
  })
}

/**
 * @summary 登出
 * {@link /api/account/logout}
 */
export function useAccountLogoutSuspense<TData = AccountLogoutMutationResponse, TQueryKey extends QueryKey = AccountLogoutSuspenseQueryKey>(data?: AccountLogoutMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountLogoutMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountLogoutMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountLogoutSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...accountLogoutSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}