/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountLoginMutationRequest, AccountLoginMutationResponse } from "../../types/accountTypes/AccountLogin";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountLoginQueryKey = (data: AccountLoginMutationRequest) => [{ url: '/api/account/login' }, ...(data ? [data] : [])] as const

export type AccountLoginQueryKey = ReturnType<typeof accountLoginQueryKey>

/**
 * @summary 登录
 * {@link /api/account/login}
 */
export async function accountLogin(data: AccountLoginMutationRequest, config: Partial<RequestConfig<AccountLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountLoginMutationResponse, ResponseErrorConfig<Error>, AccountLoginMutationRequest>({ method : "POST", url : `/api/account/login`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountLoginQueryOptions(data: AccountLoginMutationRequest, config: Partial<RequestConfig<AccountLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountLoginQueryKey(data)
  return queryOptions<AccountLoginMutationResponse, ResponseErrorConfig<Error>, AccountLoginMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountLogin(data, config)
   },
  })
}

/**
 * @summary 登录
 * {@link /api/account/login}
 */
export function useAccountLogin<TData = AccountLoginMutationResponse, TQueryData = AccountLoginMutationResponse, TQueryKey extends QueryKey = AccountLoginQueryKey>(data: AccountLoginMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<AccountLoginMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountLoginMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountLoginQueryKey(data)

  const query = useQuery({
   ...accountLoginQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}