/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountProfileMutationRequest, AccountProfileMutationResponse } from "../../types/accountTypes/AccountProfile";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountProfileSuspenseQueryKey = (data?: AccountProfileMutationRequest) => [{ url: '/api/account/profile' }, ...(data ? [data] : [])] as const

export type AccountProfileSuspenseQueryKey = ReturnType<typeof accountProfileSuspenseQueryKey>

/**
 * @summary 获取用户详细信息
 * {@link /api/account/profile}
 */
export async function accountProfileSuspense(data?: AccountProfileMutationRequest, config: Partial<RequestConfig<AccountProfileMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountProfileMutationResponse, ResponseErrorConfig<Error>, AccountProfileMutationRequest>({ method : "POST", url : `/api/account/profile`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountProfileSuspenseQueryOptions(data?: AccountProfileMutationRequest, config: Partial<RequestConfig<AccountProfileMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountProfileSuspenseQueryKey(data)
  return queryOptions<AccountProfileMutationResponse, ResponseErrorConfig<Error>, AccountProfileMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountProfileSuspense(data, config)
   },
  })
}

/**
 * @summary 获取用户详细信息
 * {@link /api/account/profile}
 */
export function useAccountProfileSuspense<TData = AccountProfileMutationResponse, TQueryKey extends QueryKey = AccountProfileSuspenseQueryKey>(data?: AccountProfileMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountProfileMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountProfileMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountProfileSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...accountProfileSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}