/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountAvatarMutationRequest, AccountAvatarMutationResponse } from "../../types/accountTypes/AccountAvatar";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountAvatarSuspenseQueryKey = (data: AccountAvatarMutationRequest) => [{ url: '/api/account/avatar' }, ...(data ? [data] : [])] as const

export type AccountAvatarSuspenseQueryKey = ReturnType<typeof accountAvatarSuspenseQueryKey>

/**
 * @summary 上传头像
 * {@link /api/account/avatar}
 */
export async function accountAvatarSuspense(data: AccountAvatarMutationRequest, config: Partial<RequestConfig<AccountAvatarMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  const formData = new FormData()
  if (requestData) {
   Object.keys(requestData).forEach((key) => {
     const value = requestData[key as keyof typeof requestData];
     if (typeof value === 'string' || (value as unknown) instanceof Blob) {
       formData.append(key, value as unknown as string | Blob);
     } else {
       formData.append(key, JSON.stringify(value));
     }
   })
  }  
  const res = await request<AccountAvatarMutationResponse, ResponseErrorConfig<Error>, AccountAvatarMutationRequest>({ method : "POST", url : `/api/account/avatar`, data : formData, ... requestConfig })  
  return res.data
}

export function accountAvatarSuspenseQueryOptions(data: AccountAvatarMutationRequest, config: Partial<RequestConfig<AccountAvatarMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountAvatarSuspenseQueryKey(data)
  return queryOptions<AccountAvatarMutationResponse, ResponseErrorConfig<Error>, AccountAvatarMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountAvatarSuspense(data, config)
   },
  })
}

/**
 * @summary 上传头像
 * {@link /api/account/avatar}
 */
export function useAccountAvatarSuspense<TData = AccountAvatarMutationResponse, TQueryKey extends QueryKey = AccountAvatarSuspenseQueryKey>(data: AccountAvatarMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountAvatarMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountAvatarMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountAvatarSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...accountAvatarSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}