/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountTopicListMutationRequest, AccountTopicListMutationResponse } from "../../types/accountTypes/AccountTopicList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountTopicListQueryKey = (data: AccountTopicListMutationRequest) => [{ url: '/api/account/topic_list' }, ...(data ? [data] : [])] as const

export type AccountTopicListQueryKey = ReturnType<typeof accountTopicListQueryKey>

/**
 * @summary 我的主题列表
 * {@link /api/account/topic_list}
 */
export async function accountTopicList(data: AccountTopicListMutationRequest, config: Partial<RequestConfig<AccountTopicListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountTopicListMutationResponse, ResponseErrorConfig<Error>, AccountTopicListMutationRequest>({ method : "POST", url : `/api/account/topic_list`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountTopicListQueryOptions(data: AccountTopicListMutationRequest, config: Partial<RequestConfig<AccountTopicListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountTopicListQueryKey(data)
  return queryOptions<AccountTopicListMutationResponse, ResponseErrorConfig<Error>, AccountTopicListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountTopicList(data, config)
   },
  })
}

/**
 * @summary 我的主题列表
 * {@link /api/account/topic_list}
 */
export function useAccountTopicList<TData = AccountTopicListMutationResponse, TQueryData = AccountTopicListMutationResponse, TQueryKey extends QueryKey = AccountTopicListQueryKey>(data: AccountTopicListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<AccountTopicListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountTopicListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountTopicListQueryKey(data)

  const query = useQuery({
   ...accountTopicListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}