/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountGetPermissionsQueryResponse } from "../../types/accountTypes/AccountGetPermissions";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountGetPermissionsSuspenseQueryKey = () => [{ url: '/api/account/get_permissions' }] as const

export type AccountGetPermissionsSuspenseQueryKey = ReturnType<typeof accountGetPermissionsSuspenseQueryKey>

/**
 * @summary 获取账号权限
 * {@link /api/account/get_permissions}
 */
export async function accountGetPermissionsSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AccountGetPermissionsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/account/get_permissions`, ... requestConfig })  
  return res.data
}

export function accountGetPermissionsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = accountGetPermissionsSuspenseQueryKey()
  return queryOptions<AccountGetPermissionsQueryResponse, ResponseErrorConfig<Error>, AccountGetPermissionsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountGetPermissionsSuspense(config)
   },
  })
}

/**
 * @summary 获取账号权限
 * {@link /api/account/get_permissions}
 */
export function useAccountGetPermissionsSuspense<TData = AccountGetPermissionsQueryResponse, TQueryKey extends QueryKey = AccountGetPermissionsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountGetPermissionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountGetPermissionsSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...accountGetPermissionsSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}