/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountChangePasswordMutationRequest, AccountChangePasswordMutationResponse } from "../../types/accountTypes/AccountChangePassword";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountChangePasswordSuspenseQueryKey = (data: AccountChangePasswordMutationRequest) => [{ url: '/api/account/change_password' }, ...(data ? [data] : [])] as const

export type AccountChangePasswordSuspenseQueryKey = ReturnType<typeof accountChangePasswordSuspenseQueryKey>

/**
 * @summary 修改密码
 * {@link /api/account/change_password}
 */
export async function accountChangePasswordSuspense(data: AccountChangePasswordMutationRequest, config: Partial<RequestConfig<AccountChangePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountChangePasswordMutationResponse, ResponseErrorConfig<Error>, AccountChangePasswordMutationRequest>({ method : "POST", url : `/api/account/change_password`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountChangePasswordSuspenseQueryOptions(data: AccountChangePasswordMutationRequest, config: Partial<RequestConfig<AccountChangePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountChangePasswordSuspenseQueryKey(data)
  return queryOptions<AccountChangePasswordMutationResponse, ResponseErrorConfig<Error>, AccountChangePasswordMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountChangePasswordSuspense(data, config)
   },
  })
}

/**
 * @summary 修改密码
 * {@link /api/account/change_password}
 */
export function useAccountChangePasswordSuspense<TData = AccountChangePasswordMutationResponse, TQueryKey extends QueryKey = AccountChangePasswordSuspenseQueryKey>(data: AccountChangePasswordMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountChangePasswordMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountChangePasswordMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountChangePasswordSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...accountChangePasswordSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}