/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountTopicListMutationRequest, AccountTopicListMutationResponse } from "../../types/accountTypes/AccountTopicList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountTopicListSuspenseQueryKey = (data: AccountTopicListMutationRequest) => [{ url: '/api/account/topic_list' }, ...(data ? [data] : [])] as const

export type AccountTopicListSuspenseQueryKey = ReturnType<typeof accountTopicListSuspenseQueryKey>

/**
 * @summary 我的主题列表
 * {@link /api/account/topic_list}
 */
export async function accountTopicListSuspense(data: AccountTopicListMutationRequest, config: Partial<RequestConfig<AccountTopicListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountTopicListMutationResponse, ResponseErrorConfig<Error>, AccountTopicListMutationRequest>({ method : "POST", url : `/api/account/topic_list`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountTopicListSuspenseQueryOptions(data: AccountTopicListMutationRequest, config: Partial<RequestConfig<AccountTopicListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountTopicListSuspenseQueryKey(data)
  return queryOptions<AccountTopicListMutationResponse, ResponseErrorConfig<Error>, AccountTopicListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountTopicListSuspense(data, config)
   },
  })
}

/**
 * @summary 我的主题列表
 * {@link /api/account/topic_list}
 */
export function useAccountTopicListSuspense<TData = AccountTopicListMutationResponse, TQueryKey extends QueryKey = AccountTopicListSuspenseQueryKey>(data: AccountTopicListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountTopicListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountTopicListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountTopicListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...accountTopicListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}