/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountDeviceListMutationRequest, AccountDeviceListMutationResponse } from "../../types/accountTypes/AccountDeviceList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountDeviceListQueryKey = (data?: AccountDeviceListMutationRequest) => [{ url: '/api/account/device_list' }, ...(data ? [data] : [])] as const

export type AccountDeviceListQueryKey = ReturnType<typeof accountDeviceListQueryKey>

/**
 * @summary 用户设备列表
 * {@link /api/account/device_list}
 */
export async function accountDeviceList(data?: AccountDeviceListMutationRequest, config: Partial<RequestConfig<AccountDeviceListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountDeviceListMutationResponse, ResponseErrorConfig<Error>, AccountDeviceListMutationRequest>({ method : "POST", url : `/api/account/device_list`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountDeviceListQueryOptions(data?: AccountDeviceListMutationRequest, config: Partial<RequestConfig<AccountDeviceListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountDeviceListQueryKey(data)
  return queryOptions<AccountDeviceListMutationResponse, ResponseErrorConfig<Error>, AccountDeviceListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountDeviceList(data, config)
   },
  })
}

/**
 * @summary 用户设备列表
 * {@link /api/account/device_list}
 */
export function useAccountDeviceList<TData = AccountDeviceListMutationResponse, TQueryData = AccountDeviceListMutationResponse, TQueryKey extends QueryKey = AccountDeviceListQueryKey>(data?: AccountDeviceListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<AccountDeviceListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountDeviceListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountDeviceListQueryKey(data)

  const query = useQuery({
   ...accountDeviceListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}