/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountLoginMutationRequest, AccountLoginMutationResponse } from "../../types/accountTypes/AccountLogin";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const accountLoginSuspenseQueryKey = (data: AccountLoginMutationRequest) => [{ url: '/api/account/login' }, ...(data ? [data] : [])] as const

export type AccountLoginSuspenseQueryKey = ReturnType<typeof accountLoginSuspenseQueryKey>

/**
 * @summary 登录
 * {@link /api/account/login}
 */
export async function accountLoginSuspense(data: AccountLoginMutationRequest, config: Partial<RequestConfig<AccountLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountLoginMutationResponse, ResponseErrorConfig<Error>, AccountLoginMutationRequest>({ method : "POST", url : `/api/account/login`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountLoginSuspenseQueryOptions(data: AccountLoginMutationRequest, config: Partial<RequestConfig<AccountLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountLoginSuspenseQueryKey(data)
  return queryOptions<AccountLoginMutationResponse, ResponseErrorConfig<Error>, AccountLoginMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountLoginSuspense(data, config)
   },
  })
}

/**
 * @summary 登录
 * {@link /api/account/login}
 */
export function useAccountLoginSuspense<TData = AccountLoginMutationResponse, TQueryKey extends QueryKey = AccountLoginSuspenseQueryKey>(data: AccountLoginMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AccountLoginMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountLoginMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountLoginSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...accountLoginSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}