/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountLogoutMutationRequest, AccountLogoutMutationResponse } from "../../types/accountTypes/AccountLogout";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountLogoutQueryKey = (data?: AccountLogoutMutationRequest) => [{ url: '/api/account/logout' }, ...(data ? [data] : [])] as const

export type AccountLogoutQueryKey = ReturnType<typeof accountLogoutQueryKey>

/**
 * @summary 登出
 * {@link /api/account/logout}
 */
export async function accountLogout(data?: AccountLogoutMutationRequest, config: Partial<RequestConfig<AccountLogoutMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountLogoutMutationResponse, ResponseErrorConfig<Error>, AccountLogoutMutationRequest>({ method : "POST", url : `/api/account/logout`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountLogoutQueryOptions(data?: AccountLogoutMutationRequest, config: Partial<RequestConfig<AccountLogoutMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountLogoutQueryKey(data)
  return queryOptions<AccountLogoutMutationResponse, ResponseErrorConfig<Error>, AccountLogoutMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountLogout(data, config)
   },
  })
}

/**
 * @summary 登出
 * {@link /api/account/logout}
 */
export function useAccountLogout<TData = AccountLogoutMutationResponse, TQueryData = AccountLogoutMutationResponse, TQueryKey extends QueryKey = AccountLogoutQueryKey>(data?: AccountLogoutMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<AccountLogoutMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountLogoutMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountLogoutQueryKey(data)

  const query = useQuery({
   ...accountLogoutQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}