/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { AccountChangePasswordMutationRequest, AccountChangePasswordMutationResponse } from "../../types/accountTypes/AccountChangePassword";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const accountChangePasswordQueryKey = (data: AccountChangePasswordMutationRequest) => [{ url: '/api/account/change_password' }, ...(data ? [data] : [])] as const

export type AccountChangePasswordQueryKey = ReturnType<typeof accountChangePasswordQueryKey>

/**
 * @summary 修改密码
 * {@link /api/account/change_password}
 */
export async function accountChangePassword(data: AccountChangePasswordMutationRequest, config: Partial<RequestConfig<AccountChangePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AccountChangePasswordMutationResponse, ResponseErrorConfig<Error>, AccountChangePasswordMutationRequest>({ method : "POST", url : `/api/account/change_password`, data : requestData, ... requestConfig })  
  return res.data
}

export function accountChangePasswordQueryOptions(data: AccountChangePasswordMutationRequest, config: Partial<RequestConfig<AccountChangePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = accountChangePasswordQueryKey(data)
  return queryOptions<AccountChangePasswordMutationResponse, ResponseErrorConfig<Error>, AccountChangePasswordMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return accountChangePassword(data, config)
   },
  })
}

/**
 * @summary 修改密码
 * {@link /api/account/change_password}
 */
export function useAccountChangePassword<TData = AccountChangePasswordMutationResponse, TQueryData = AccountChangePasswordMutationResponse, TQueryKey extends QueryKey = AccountChangePasswordQueryKey>(data: AccountChangePasswordMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<AccountChangePasswordMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<AccountChangePasswordMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? accountChangePasswordQueryKey(data)

  const query = useQuery({
   ...accountChangePasswordQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}