/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1OuterExportReq } from "../v1/OuterExportReq";
import type { V1OuterExportRes } from "../v1/OuterExportRes";

export type OuterExport200 = V1OuterExportRes;

export type OuterExportMutationRequest = V1OuterExportReq;

export type OuterExportMutationResponse = OuterExport200;

export type OuterExportMutation = {
    Response: OuterExport200;
    Request: OuterExportMutationRequest;
    Errors: any;
};