/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommonSignStsReq } from "../v1/CommonSignStsReq";
import type { V1CommonSignStsRes } from "../v1/CommonSignStsRes";

export type CommonSignSts200 = V1CommonSignStsRes;

export type CommonSignStsMutationRequest = V1CommonSignStsReq;

export type CommonSignStsMutationResponse = CommonSignSts200;

export type CommonSignStsMutation = {
    Response: CommonSignSts200;
    Request: CommonSignStsMutationRequest;
    Errors: any;
};