/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskTopicEdit200, TaskTopicEditMutationRequest, TaskTopicEditMutationResponse } from "../../types/task_topicTypes/TaskTopicEdit";
import { v1TaskTopicEditReqSchema } from "../v1/taskTopicEditReqSchema";
import { v1TaskTopicEditResSchema } from "../v1/taskTopicEditResSchema";
import { z } from "zod/v4";

export const taskTopicEdit200Schema = v1TaskTopicEditResSchema as unknown as z.ZodType<TaskTopicEdit200>

export const taskTopicEditMutationRequestSchema = v1TaskTopicEditReqSchema as unknown as z.ZodType<TaskTopicEditMutationRequest>

export const taskTopicEditMutationResponseSchema = taskTopicEdit200Schema as unknown as z.ZodType<TaskTopicEditMutationResponse>