/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskTopicAdd200, TaskTopicAddMutationRequest, TaskTopicAddMutationResponse } from "../../types/task_topicTypes/TaskTopicAdd";
import { v1TaskTopicAddReqSchema } from "../v1/taskTopicAddReqSchema";
import { v1TaskTopicAddResSchema } from "../v1/taskTopicAddResSchema";
import { z } from "zod/v4";

export const taskTopicAdd200Schema = v1TaskTopicAddResSchema as unknown as z.ZodType<TaskTopicAdd200>

export const taskTopicAddMutationRequestSchema = v1TaskTopicAddReqSchema as unknown as z.ZodType<TaskTopicAddMutationRequest>

export const taskTopicAddMutationResponseSchema = taskTopicAdd200Schema as unknown as z.ZodType<TaskTopicAddMutationResponse>