/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskTopicDetail200, TaskTopicDetailMutationRequest, TaskTopicDetailMutationResponse } from "../../types/task_topicTypes/TaskTopicDetail";
import { v1TaskTopicDetailReqSchema } from "../v1/taskTopicDetailReqSchema";
import { v1TaskTopicDetailResSchema } from "../v1/taskTopicDetailResSchema";
import { z } from "zod/v4";

export const taskTopicDetail200Schema = v1TaskTopicDetailResSchema as unknown as z.ZodType<TaskTopicDetail200>

export const taskTopicDetailMutationRequestSchema = v1TaskTopicDetailReqSchema as unknown as z.ZodType<TaskTopicDetailMutationRequest>

export const taskTopicDetailMutationResponseSchema = taskTopicDetail200Schema as unknown as z.ZodType<TaskTopicDetailMutationResponse>