/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskTopicDelete200, TaskTopicDeleteMutationRequest, TaskTopicDeleteMutationResponse } from "../../types/task_topicTypes/TaskTopicDelete";
import { v1TaskTopicDeleteReqSchema } from "../v1/taskTopicDeleteReqSchema";
import { v1TaskTopicDeleteResSchema } from "../v1/taskTopicDeleteResSchema";
import { z } from "zod/v4";

export const taskTopicDelete200Schema = v1TaskTopicDeleteResSchema as unknown as z.ZodType<TaskTopicDelete200>

export const taskTopicDeleteMutationRequestSchema = v1TaskTopicDeleteReqSchema as unknown as z.ZodType<TaskTopicDeleteMutationRequest>

export const taskTopicDeleteMutationResponseSchema = taskTopicDelete200Schema as unknown as z.ZodType<TaskTopicDeleteMutationResponse>