/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicEditMutationRequest, TaskTopicEditMutationResponse } from "../../types/task_topicTypes/TaskTopicEdit";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskTopicEditSuspenseQueryKey = (data: TaskTopicEditMutationRequest) => [{ url: '/api/task_topic/edit' }, ...(data ? [data] : [])] as const

export type TaskTopicEditSuspenseQueryKey = ReturnType<typeof taskTopicEditSuspenseQueryKey>

/**
 * @summary 编辑主题
 * {@link /api/task_topic/edit}
 */
export async function taskTopicEditSuspense(data: TaskTopicEditMutationRequest, config: Partial<RequestConfig<TaskTopicEditMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicEditMutationResponse, ResponseErrorConfig<Error>, TaskTopicEditMutationRequest>({ method : "POST", url : `/api/task_topic/edit`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicEditSuspenseQueryOptions(data: TaskTopicEditMutationRequest, config: Partial<RequestConfig<TaskTopicEditMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicEditSuspenseQueryKey(data)
  return queryOptions<TaskTopicEditMutationResponse, ResponseErrorConfig<Error>, TaskTopicEditMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicEditSuspense(data, config)
   },
  })
}

/**
 * @summary 编辑主题
 * {@link /api/task_topic/edit}
 */
export function useTaskTopicEditSuspense<TData = TaskTopicEditMutationResponse, TQueryKey extends QueryKey = TaskTopicEditSuspenseQueryKey>(data: TaskTopicEditMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskTopicEditMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicEditMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicEditSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskTopicEditSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}