/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicAddMutationRequest, TaskTopicAddMutationResponse } from "../../types/task_topicTypes/TaskTopicAdd";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskTopicAddQueryKey = (data: TaskTopicAddMutationRequest) => [{ url: '/api/task_topic/add' }, ...(data ? [data] : [])] as const

export type TaskTopicAddQueryKey = ReturnType<typeof taskTopicAddQueryKey>

/**
 * @summary 发布主题
 * {@link /api/task_topic/add}
 */
export async function taskTopicAdd(data: TaskTopicAddMutationRequest, config: Partial<RequestConfig<TaskTopicAddMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicAddMutationResponse, ResponseErrorConfig<Error>, TaskTopicAddMutationRequest>({ method : "POST", url : `/api/task_topic/add`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicAddQueryOptions(data: TaskTopicAddMutationRequest, config: Partial<RequestConfig<TaskTopicAddMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicAddQueryKey(data)
  return queryOptions<TaskTopicAddMutationResponse, ResponseErrorConfig<Error>, TaskTopicAddMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicAdd(data, config)
   },
  })
}

/**
 * @summary 发布主题
 * {@link /api/task_topic/add}
 */
export function useTaskTopicAdd<TData = TaskTopicAddMutationResponse, TQueryData = TaskTopicAddMutationResponse, TQueryKey extends QueryKey = TaskTopicAddQueryKey>(data: TaskTopicAddMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskTopicAddMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicAddMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicAddQueryKey(data)

  const query = useQuery({
   ...taskTopicAddQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}