/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicListMutationRequest, TaskTopicListMutationResponse } from "../../types/task_topicTypes/TaskTopicList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskTopicListQueryKey = (data: TaskTopicListMutationRequest) => [{ url: '/api/task_topic/list' }, ...(data ? [data] : [])] as const

export type TaskTopicListQueryKey = ReturnType<typeof taskTopicListQueryKey>

/**
 * @summary 主题列表
 * {@link /api/task_topic/list}
 */
export async function taskTopicList(data: TaskTopicListMutationRequest, config: Partial<RequestConfig<TaskTopicListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicListMutationResponse, ResponseErrorConfig<Error>, TaskTopicListMutationRequest>({ method : "POST", url : `/api/task_topic/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicListQueryOptions(data: TaskTopicListMutationRequest, config: Partial<RequestConfig<TaskTopicListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicListQueryKey(data)
  return queryOptions<TaskTopicListMutationResponse, ResponseErrorConfig<Error>, TaskTopicListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicList(data, config)
   },
  })
}

/**
 * @summary 主题列表
 * {@link /api/task_topic/list}
 */
export function useTaskTopicList<TData = TaskTopicListMutationResponse, TQueryData = TaskTopicListMutationResponse, TQueryKey extends QueryKey = TaskTopicListQueryKey>(data: TaskTopicListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskTopicListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicListQueryKey(data)

  const query = useQuery({
   ...taskTopicListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}