/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicDetailMutationRequest, TaskTopicDetailMutationResponse } from "../../types/task_topicTypes/TaskTopicDetail";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskTopicDetailSuspenseQueryKey = (data: TaskTopicDetailMutationRequest) => [{ url: '/api/task_topic/detail' }, ...(data ? [data] : [])] as const

export type TaskTopicDetailSuspenseQueryKey = ReturnType<typeof taskTopicDetailSuspenseQueryKey>

/**
 * @summary 主题详情
 * {@link /api/task_topic/detail}
 */
export async function taskTopicDetailSuspense(data: TaskTopicDetailMutationRequest, config: Partial<RequestConfig<TaskTopicDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicDetailMutationResponse, ResponseErrorConfig<Error>, TaskTopicDetailMutationRequest>({ method : "POST", url : `/api/task_topic/detail`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicDetailSuspenseQueryOptions(data: TaskTopicDetailMutationRequest, config: Partial<RequestConfig<TaskTopicDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicDetailSuspenseQueryKey(data)
  return queryOptions<TaskTopicDetailMutationResponse, ResponseErrorConfig<Error>, TaskTopicDetailMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicDetailSuspense(data, config)
   },
  })
}

/**
 * @summary 主题详情
 * {@link /api/task_topic/detail}
 */
export function useTaskTopicDetailSuspense<TData = TaskTopicDetailMutationResponse, TQueryKey extends QueryKey = TaskTopicDetailSuspenseQueryKey>(data: TaskTopicDetailMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskTopicDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicDetailSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskTopicDetailSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}