/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicDeleteMutationRequest, TaskTopicDeleteMutationResponse } from "../../types/task_topicTypes/TaskTopicDelete";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskTopicDeleteQueryKey = (data: TaskTopicDeleteMutationRequest) => [{ url: '/api/task_topic/delete' }, ...(data ? [data] : [])] as const

export type TaskTopicDeleteQueryKey = ReturnType<typeof taskTopicDeleteQueryKey>

/**
 * @summary 删除主题
 * {@link /api/task_topic/delete}
 */
export async function taskTopicDelete(data: TaskTopicDeleteMutationRequest, config: Partial<RequestConfig<TaskTopicDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicDeleteMutationResponse, ResponseErrorConfig<Error>, TaskTopicDeleteMutationRequest>({ method : "POST", url : `/api/task_topic/delete`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicDeleteQueryOptions(data: TaskTopicDeleteMutationRequest, config: Partial<RequestConfig<TaskTopicDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicDeleteQueryKey(data)
  return queryOptions<TaskTopicDeleteMutationResponse, ResponseErrorConfig<Error>, TaskTopicDeleteMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicDelete(data, config)
   },
  })
}

/**
 * @summary 删除主题
 * {@link /api/task_topic/delete}
 */
export function useTaskTopicDelete<TData = TaskTopicDeleteMutationResponse, TQueryData = TaskTopicDeleteMutationResponse, TQueryKey extends QueryKey = TaskTopicDeleteQueryKey>(data: TaskTopicDeleteMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskTopicDeleteMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicDeleteMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicDeleteQueryKey(data)

  const query = useQuery({
   ...taskTopicDeleteQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}