/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicAddMutationRequest, TaskTopicAddMutationResponse } from "../../types/task_topicTypes/TaskTopicAdd";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskTopicAddSuspenseQueryKey = (data: TaskTopicAddMutationRequest) => [{ url: '/api/task_topic/add' }, ...(data ? [data] : [])] as const

export type TaskTopicAddSuspenseQueryKey = ReturnType<typeof taskTopicAddSuspenseQueryKey>

/**
 * @summary 发布主题
 * {@link /api/task_topic/add}
 */
export async function taskTopicAddSuspense(data: TaskTopicAddMutationRequest, config: Partial<RequestConfig<TaskTopicAddMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicAddMutationResponse, ResponseErrorConfig<Error>, TaskTopicAddMutationRequest>({ method : "POST", url : `/api/task_topic/add`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicAddSuspenseQueryOptions(data: TaskTopicAddMutationRequest, config: Partial<RequestConfig<TaskTopicAddMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicAddSuspenseQueryKey(data)
  return queryOptions<TaskTopicAddMutationResponse, ResponseErrorConfig<Error>, TaskTopicAddMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicAddSuspense(data, config)
   },
  })
}

/**
 * @summary 发布主题
 * {@link /api/task_topic/add}
 */
export function useTaskTopicAddSuspense<TData = TaskTopicAddMutationResponse, TQueryKey extends QueryKey = TaskTopicAddSuspenseQueryKey>(data: TaskTopicAddMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskTopicAddMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicAddMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicAddSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskTopicAddSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}