/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicListMutationRequest, TaskTopicListMutationResponse } from "../../types/task_topicTypes/TaskTopicList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskTopicListSuspenseQueryKey = (data: TaskTopicListMutationRequest) => [{ url: '/api/task_topic/list' }, ...(data ? [data] : [])] as const

export type TaskTopicListSuspenseQueryKey = ReturnType<typeof taskTopicListSuspenseQueryKey>

/**
 * @summary 主题列表
 * {@link /api/task_topic/list}
 */
export async function taskTopicListSuspense(data: TaskTopicListMutationRequest, config: Partial<RequestConfig<TaskTopicListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicListMutationResponse, ResponseErrorConfig<Error>, TaskTopicListMutationRequest>({ method : "POST", url : `/api/task_topic/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicListSuspenseQueryOptions(data: TaskTopicListMutationRequest, config: Partial<RequestConfig<TaskTopicListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicListSuspenseQueryKey(data)
  return queryOptions<TaskTopicListMutationResponse, ResponseErrorConfig<Error>, TaskTopicListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicListSuspense(data, config)
   },
  })
}

/**
 * @summary 主题列表
 * {@link /api/task_topic/list}
 */
export function useTaskTopicListSuspense<TData = TaskTopicListMutationResponse, TQueryKey extends QueryKey = TaskTopicListSuspenseQueryKey>(data: TaskTopicListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskTopicListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskTopicListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}