/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicDetailMutationRequest, TaskTopicDetailMutationResponse } from "../../types/task_topicTypes/TaskTopicDetail";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskTopicDetailQueryKey = (data: TaskTopicDetailMutationRequest) => [{ url: '/api/task_topic/detail' }, ...(data ? [data] : [])] as const

export type TaskTopicDetailQueryKey = ReturnType<typeof taskTopicDetailQueryKey>

/**
 * @summary 主题详情
 * {@link /api/task_topic/detail}
 */
export async function taskTopicDetail(data: TaskTopicDetailMutationRequest, config: Partial<RequestConfig<TaskTopicDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicDetailMutationResponse, ResponseErrorConfig<Error>, TaskTopicDetailMutationRequest>({ method : "POST", url : `/api/task_topic/detail`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicDetailQueryOptions(data: TaskTopicDetailMutationRequest, config: Partial<RequestConfig<TaskTopicDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicDetailQueryKey(data)
  return queryOptions<TaskTopicDetailMutationResponse, ResponseErrorConfig<Error>, TaskTopicDetailMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicDetail(data, config)
   },
  })
}

/**
 * @summary 主题详情
 * {@link /api/task_topic/detail}
 */
export function useTaskTopicDetail<TData = TaskTopicDetailMutationResponse, TQueryData = TaskTopicDetailMutationResponse, TQueryKey extends QueryKey = TaskTopicDetailQueryKey>(data: TaskTopicDetailMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskTopicDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicDetailQueryKey(data)

  const query = useQuery({
   ...taskTopicDetailQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}