/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicEditMutationRequest, TaskTopicEditMutationResponse } from "../../types/task_topicTypes/TaskTopicEdit";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskTopicEditQueryKey = (data: TaskTopicEditMutationRequest) => [{ url: '/api/task_topic/edit' }, ...(data ? [data] : [])] as const

export type TaskTopicEditQueryKey = ReturnType<typeof taskTopicEditQueryKey>

/**
 * @summary 编辑主题
 * {@link /api/task_topic/edit}
 */
export async function taskTopicEdit(data: TaskTopicEditMutationRequest, config: Partial<RequestConfig<TaskTopicEditMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicEditMutationResponse, ResponseErrorConfig<Error>, TaskTopicEditMutationRequest>({ method : "POST", url : `/api/task_topic/edit`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicEditQueryOptions(data: TaskTopicEditMutationRequest, config: Partial<RequestConfig<TaskTopicEditMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicEditQueryKey(data)
  return queryOptions<TaskTopicEditMutationResponse, ResponseErrorConfig<Error>, TaskTopicEditMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicEdit(data, config)
   },
  })
}

/**
 * @summary 编辑主题
 * {@link /api/task_topic/edit}
 */
export function useTaskTopicEdit<TData = TaskTopicEditMutationResponse, TQueryData = TaskTopicEditMutationResponse, TQueryKey extends QueryKey = TaskTopicEditQueryKey>(data: TaskTopicEditMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskTopicEditMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicEditMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicEditQueryKey(data)

  const query = useQuery({
   ...taskTopicEditQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}