/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskTopicDeleteMutationRequest, TaskTopicDeleteMutationResponse } from "../../types/task_topicTypes/TaskTopicDelete";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskTopicDeleteSuspenseQueryKey = (data: TaskTopicDeleteMutationRequest) => [{ url: '/api/task_topic/delete' }, ...(data ? [data] : [])] as const

export type TaskTopicDeleteSuspenseQueryKey = ReturnType<typeof taskTopicDeleteSuspenseQueryKey>

/**
 * @summary 删除主题
 * {@link /api/task_topic/delete}
 */
export async function taskTopicDeleteSuspense(data: TaskTopicDeleteMutationRequest, config: Partial<RequestConfig<TaskTopicDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskTopicDeleteMutationResponse, ResponseErrorConfig<Error>, TaskTopicDeleteMutationRequest>({ method : "POST", url : `/api/task_topic/delete`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskTopicDeleteSuspenseQueryOptions(data: TaskTopicDeleteMutationRequest, config: Partial<RequestConfig<TaskTopicDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskTopicDeleteSuspenseQueryKey(data)
  return queryOptions<TaskTopicDeleteMutationResponse, ResponseErrorConfig<Error>, TaskTopicDeleteMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskTopicDeleteSuspense(data, config)
   },
  })
}

/**
 * @summary 删除主题
 * {@link /api/task_topic/delete}
 */
export function useTaskTopicDeleteSuspense<TData = TaskTopicDeleteMutationResponse, TQueryKey extends QueryKey = TaskTopicDeleteSuspenseQueryKey>(data: TaskTopicDeleteMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskTopicDeleteMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskTopicDeleteMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskTopicDeleteSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskTopicDeleteSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}