/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TrainList200, TrainListMutationRequest, TrainListMutationResponse } from "../../types/trainTypes/TrainList";
import { v1TrainListReqSchema } from "../v1/trainListReqSchema";
import { v1TrainListResSchema } from "../v1/trainListResSchema";
import { z } from "zod/v4";

export const trainList200Schema = v1TrainListResSchema as unknown as z.ZodType<TrainList200>

export const trainListMutationRequestSchema = v1TrainListReqSchema as unknown as z.ZodType<TrainListMutationRequest>

export const trainListMutationResponseSchema = trainList200Schema as unknown as z.ZodType<TrainListMutationResponse>