/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TrainDelete200, TrainDeleteMutationRequest, TrainDeleteMutationResponse } from "../../types/trainTypes/TrainDelete";
import { v1TrainDeleteReqSchema } from "../v1/trainDeleteReqSchema";
import { v1TrainDeleteResSchema } from "../v1/trainDeleteResSchema";
import { z } from "zod/v4";

export const trainDelete200Schema = v1TrainDeleteResSchema as unknown as z.ZodType<TrainDelete200>

export const trainDeleteMutationRequestSchema = v1TrainDeleteReqSchema as unknown as z.ZodType<TrainDeleteMutationRequest>

export const trainDeleteMutationResponseSchema = trainDelete200Schema as unknown as z.ZodType<TrainDeleteMutationResponse>