/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TrainResult200, TrainResultMutationRequest, TrainResultMutationResponse } from "../../types/trainTypes/TrainResult";
import { v1TrainResultReqSchema } from "../v1/trainResultReqSchema";
import { v1TrainResultResSchema } from "../v1/trainResultResSchema";
import { z } from "zod/v4";

export const trainResult200Schema = v1TrainResultResSchema as unknown as z.ZodType<TrainResult200>

export const trainResultMutationRequestSchema = v1TrainResultReqSchema as unknown as z.ZodType<TrainResultMutationRequest>

export const trainResultMutationResponseSchema = trainResult200Schema as unknown as z.ZodType<TrainResultMutationResponse>