/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TrainCreate200, TrainCreateMutationRequest, TrainCreateMutationResponse } from "../../types/trainTypes/TrainCreate";
import { v1TrainCreateReqSchema } from "../v1/trainCreateReqSchema";
import { v1TrainCreateResSchema } from "../v1/trainCreateResSchema";
import { z } from "zod/v4";

export const trainCreate200Schema = v1TrainCreateResSchema as unknown as z.ZodType<TrainCreate200>

export const trainCreateMutationRequestSchema = v1TrainCreateReqSchema as unknown as z.ZodType<TrainCreateMutationRequest>

export const trainCreateMutationResponseSchema = trainCreate200Schema as unknown as z.ZodType<TrainCreateMutationResponse>