/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TrainSave200, TrainSaveMutationRequest, TrainSaveMutationResponse } from "../../types/trainTypes/TrainSave";
import { v1TrainSaveReqSchema } from "../v1/trainSaveReqSchema";
import { v1TrainSaveResSchema } from "../v1/trainSaveResSchema";
import { z } from "zod/v4";

export const trainSave200Schema = v1TrainSaveResSchema as unknown as z.ZodType<TrainSave200>

export const trainSaveMutationRequestSchema = v1TrainSaveReqSchema as unknown as z.ZodType<TrainSaveMutationRequest>

export const trainSaveMutationResponseSchema = trainSave200Schema as unknown as z.ZodType<TrainSaveMutationResponse>