/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TopicLikeLikeMutationRequest, TopicLikeLikeMutationResponse } from "../../types/topic_likeTypes/TopicLikeLike";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const topicLikeLikeSuspenseQueryKey = (data: TopicLikeLikeMutationRequest) => [{ url: '/api/topic_like/like' }, ...(data ? [data] : [])] as const

export type TopicLikeLikeSuspenseQueryKey = ReturnType<typeof topicLikeLikeSuspenseQueryKey>

/**
 * @summary 主题点赞
 * {@link /api/topic_like/like}
 */
export async function topicLikeLikeSuspense(data: TopicLikeLikeMutationRequest, config: Partial<RequestConfig<TopicLikeLikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TopicLikeLikeMutationResponse, ResponseErrorConfig<Error>, TopicLikeLikeMutationRequest>({ method : "POST", url : `/api/topic_like/like`, data : requestData, ... requestConfig })  
  return res.data
}

export function topicLikeLikeSuspenseQueryOptions(data: TopicLikeLikeMutationRequest, config: Partial<RequestConfig<TopicLikeLikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = topicLikeLikeSuspenseQueryKey(data)
  return queryOptions<TopicLikeLikeMutationResponse, ResponseErrorConfig<Error>, TopicLikeLikeMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return topicLikeLikeSuspense(data, config)
   },
  })
}

/**
 * @summary 主题点赞
 * {@link /api/topic_like/like}
 */
export function useTopicLikeLikeSuspense<TData = TopicLikeLikeMutationResponse, TQueryKey extends QueryKey = TopicLikeLikeSuspenseQueryKey>(data: TopicLikeLikeMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TopicLikeLikeMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TopicLikeLikeMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? topicLikeLikeSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...topicLikeLikeSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}