/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TopicLikeLikeMutationRequest, TopicLikeLikeMutationResponse } from "../../types/topic_likeTypes/TopicLikeLike";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const topicLikeLikeQueryKey = (data: TopicLikeLikeMutationRequest) => [{ url: '/api/topic_like/like' }, ...(data ? [data] : [])] as const

export type TopicLikeLikeQueryKey = ReturnType<typeof topicLikeLikeQueryKey>

/**
 * @summary 主题点赞
 * {@link /api/topic_like/like}
 */
export async function topicLikeLike(data: TopicLikeLikeMutationRequest, config: Partial<RequestConfig<TopicLikeLikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TopicLikeLikeMutationResponse, ResponseErrorConfig<Error>, TopicLikeLikeMutationRequest>({ method : "POST", url : `/api/topic_like/like`, data : requestData, ... requestConfig })  
  return res.data
}

export function topicLikeLikeQueryOptions(data: TopicLikeLikeMutationRequest, config: Partial<RequestConfig<TopicLikeLikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = topicLikeLikeQueryKey(data)
  return queryOptions<TopicLikeLikeMutationResponse, ResponseErrorConfig<Error>, TopicLikeLikeMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return topicLikeLike(data, config)
   },
  })
}

/**
 * @summary 主题点赞
 * {@link /api/topic_like/like}
 */
export function useTopicLikeLike<TData = TopicLikeLikeMutationResponse, TQueryData = TopicLikeLikeMutationResponse, TQueryKey extends QueryKey = TopicLikeLikeQueryKey>(data: TopicLikeLikeMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TopicLikeLikeMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TopicLikeLikeMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? topicLikeLikeQueryKey(data)

  const query = useQuery({
   ...topicLikeLikeQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}