/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TopicLikeUnlikeMutationRequest, TopicLikeUnlikeMutationResponse } from "../../types/topic_likeTypes/TopicLikeUnlike";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const topicLikeUnlikeSuspenseQueryKey = (data: TopicLikeUnlikeMutationRequest) => [{ url: '/api/topic_like/unlike' }, ...(data ? [data] : [])] as const

export type TopicLikeUnlikeSuspenseQueryKey = ReturnType<typeof topicLikeUnlikeSuspenseQueryKey>

/**
 * @summary 主题取消点赞
 * {@link /api/topic_like/unlike}
 */
export async function topicLikeUnlikeSuspense(data: TopicLikeUnlikeMutationRequest, config: Partial<RequestConfig<TopicLikeUnlikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TopicLikeUnlikeMutationResponse, ResponseErrorConfig<Error>, TopicLikeUnlikeMutationRequest>({ method : "POST", url : `/api/topic_like/unlike`, data : requestData, ... requestConfig })  
  return res.data
}

export function topicLikeUnlikeSuspenseQueryOptions(data: TopicLikeUnlikeMutationRequest, config: Partial<RequestConfig<TopicLikeUnlikeMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = topicLikeUnlikeSuspenseQueryKey(data)
  return queryOptions<TopicLikeUnlikeMutationResponse, ResponseErrorConfig<Error>, TopicLikeUnlikeMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return topicLikeUnlikeSuspense(data, config)
   },
  })
}

/**
 * @summary 主题取消点赞
 * {@link /api/topic_like/unlike}
 */
export function useTopicLikeUnlikeSuspense<TData = TopicLikeUnlikeMutationResponse, TQueryKey extends QueryKey = TopicLikeUnlikeSuspenseQueryKey>(data: TopicLikeUnlikeMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TopicLikeUnlikeMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TopicLikeUnlikeMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? topicLikeUnlikeSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...topicLikeUnlikeSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}