export type { TrainCreateQueryKey } from "./useTrainCreate";
export type { TrainCreateSuspenseQueryKey } from "./useTrainCreateSuspense";
export type { TrainDeleteQueryKey } from "./useTrainDelete";
export type { TrainDeleteSuspenseQueryKey } from "./useTrainDeleteSuspense";
export type { TrainDetailQueryKey } from "./useTrainDetail";
export type { TrainDetailSuspenseQueryKey } from "./useTrainDetailSuspense";
export type { TrainListQueryKey } from "./useTrainList";
export type { TrainListSuspenseQueryKey } from "./useTrainListSuspense";
export type { TrainResultQueryKey } from "./useTrainResult";
export type { TrainResultSuspenseQueryKey } from "./useTrainResultSuspense";
export type { TrainSaveQueryKey } from "./useTrainSave";
export type { TrainSaveSuspenseQueryKey } from "./useTrainSaveSuspense";
export { trainCreateQueryKey, trainCreate, trainCreateQueryOptions, useTrainCreate } from "./useTrainCreate";
export { trainCreateSuspenseQueryKey, trainCreateSuspense, trainCreateSuspenseQueryOptions, useTrainCreateSuspense } from "./useTrainCreateSuspense";
export { trainDeleteQueryKey, trainDelete, trainDeleteQueryOptions, useTrainDelete } from "./useTrainDelete";
export { trainDeleteSuspenseQueryKey, trainDeleteSuspense, trainDeleteSuspenseQueryOptions, useTrainDeleteSuspense } from "./useTrainDeleteSuspense";
export { trainDetailQueryKey, trainDetail, trainDetailQueryOptions, useTrainDetail } from "./useTrainDetail";
export { trainDetailSuspenseQueryKey, trainDetailSuspense, trainDetailSuspenseQueryOptions, useTrainDetailSuspense } from "./useTrainDetailSuspense";
export { trainListQueryKey, trainList, trainListQueryOptions, useTrainList } from "./useTrainList";
export { trainListSuspenseQueryKey, trainListSuspense, trainListSuspenseQueryOptions, useTrainListSuspense } from "./useTrainListSuspense";
export { trainResultQueryKey, trainResult, trainResultQueryOptions, useTrainResult } from "./useTrainResult";
export { trainResultSuspenseQueryKey, trainResultSuspense, trainResultSuspenseQueryOptions, useTrainResultSuspense } from "./useTrainResultSuspense";
export { trainSaveQueryKey, trainSave, trainSaveQueryOptions, useTrainSave } from "./useTrainSave";
export { trainSaveSuspenseQueryKey, trainSaveSuspense, trainSaveSuspenseQueryOptions, useTrainSaveSuspense } from "./useTrainSaveSuspense";