/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainResultMutationRequest, TrainResultMutationResponse } from "../../types/trainTypes/TrainResult";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const trainResultSuspenseQueryKey = (data: TrainResultMutationRequest) => [{ url: '/api/train/result' }, ...(data ? [data] : [])] as const

export type TrainResultSuspenseQueryKey = ReturnType<typeof trainResultSuspenseQueryKey>

/**
 * @summary 查询训练结果
 * {@link /api/train/result}
 */
export async function trainResultSuspense(data: TrainResultMutationRequest, config: Partial<RequestConfig<TrainResultMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainResultMutationResponse, ResponseErrorConfig<Error>, TrainResultMutationRequest>({ method : "POST", url : `/api/train/result`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainResultSuspenseQueryOptions(data: TrainResultMutationRequest, config: Partial<RequestConfig<TrainResultMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainResultSuspenseQueryKey(data)
  return queryOptions<TrainResultMutationResponse, ResponseErrorConfig<Error>, TrainResultMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainResultSuspense(data, config)
   },
  })
}

/**
 * @summary 查询训练结果
 * {@link /api/train/result}
 */
export function useTrainResultSuspense<TData = TrainResultMutationResponse, TQueryKey extends QueryKey = TrainResultSuspenseQueryKey>(data: TrainResultMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TrainResultMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainResultMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainResultSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...trainResultSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}