/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainDeleteMutationRequest, TrainDeleteMutationResponse } from "../../types/trainTypes/TrainDelete";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const trainDeleteSuspenseQueryKey = (data: TrainDeleteMutationRequest) => [{ url: '/api/train/delete' }, ...(data ? [data] : [])] as const

export type TrainDeleteSuspenseQueryKey = ReturnType<typeof trainDeleteSuspenseQueryKey>

/**
 * @summary 我的模型删除
 * {@link /api/train/delete}
 */
export async function trainDeleteSuspense(data: TrainDeleteMutationRequest, config: Partial<RequestConfig<TrainDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainDeleteMutationResponse, ResponseErrorConfig<Error>, TrainDeleteMutationRequest>({ method : "POST", url : `/api/train/delete`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainDeleteSuspenseQueryOptions(data: TrainDeleteMutationRequest, config: Partial<RequestConfig<TrainDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainDeleteSuspenseQueryKey(data)
  return queryOptions<TrainDeleteMutationResponse, ResponseErrorConfig<Error>, TrainDeleteMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainDeleteSuspense(data, config)
   },
  })
}

/**
 * @summary 我的模型删除
 * {@link /api/train/delete}
 */
export function useTrainDeleteSuspense<TData = TrainDeleteMutationResponse, TQueryKey extends QueryKey = TrainDeleteSuspenseQueryKey>(data: TrainDeleteMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TrainDeleteMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainDeleteMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainDeleteSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...trainDeleteSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}