/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainDetailMutationRequest, TrainDetailMutationResponse } from "../../types/trainTypes/TrainDetail";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const trainDetailQueryKey = (data: TrainDetailMutationRequest) => [{ url: '/api/train/detail' }, ...(data ? [data] : [])] as const

export type TrainDetailQueryKey = ReturnType<typeof trainDetailQueryKey>

/**
 * @summary 训练详情
 * {@link /api/train/detail}
 */
export async function trainDetail(data: TrainDetailMutationRequest, config: Partial<RequestConfig<TrainDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainDetailMutationResponse, ResponseErrorConfig<Error>, TrainDetailMutationRequest>({ method : "POST", url : `/api/train/detail`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainDetailQueryOptions(data: TrainDetailMutationRequest, config: Partial<RequestConfig<TrainDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainDetailQueryKey(data)
  return queryOptions<TrainDetailMutationResponse, ResponseErrorConfig<Error>, TrainDetailMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainDetail(data, config)
   },
  })
}

/**
 * @summary 训练详情
 * {@link /api/train/detail}
 */
export function useTrainDetail<TData = TrainDetailMutationResponse, TQueryData = TrainDetailMutationResponse, TQueryKey extends QueryKey = TrainDetailQueryKey>(data: TrainDetailMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TrainDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainDetailQueryKey(data)

  const query = useQuery({
   ...trainDetailQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}