/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainCreateMutationRequest, TrainCreateMutationResponse } from "../../types/trainTypes/TrainCreate";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const trainCreateSuspenseQueryKey = (data: TrainCreateMutationRequest) => [{ url: '/api/train/create' }, ...(data ? [data] : [])] as const

export type TrainCreateSuspenseQueryKey = ReturnType<typeof trainCreateSuspenseQueryKey>

/**
 * @summary 创建训练
 * {@link /api/train/create}
 */
export async function trainCreateSuspense(data: TrainCreateMutationRequest, config: Partial<RequestConfig<TrainCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainCreateMutationResponse, ResponseErrorConfig<Error>, TrainCreateMutationRequest>({ method : "POST", url : `/api/train/create`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainCreateSuspenseQueryOptions(data: TrainCreateMutationRequest, config: Partial<RequestConfig<TrainCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainCreateSuspenseQueryKey(data)
  return queryOptions<TrainCreateMutationResponse, ResponseErrorConfig<Error>, TrainCreateMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainCreateSuspense(data, config)
   },
  })
}

/**
 * @summary 创建训练
 * {@link /api/train/create}
 */
export function useTrainCreateSuspense<TData = TrainCreateMutationResponse, TQueryKey extends QueryKey = TrainCreateSuspenseQueryKey>(data: TrainCreateMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TrainCreateMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainCreateMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainCreateSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...trainCreateSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}