/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainListMutationRequest, TrainListMutationResponse } from "../../types/trainTypes/TrainList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const trainListSuspenseQueryKey = (data: TrainListMutationRequest) => [{ url: '/api/train/list' }, ...(data ? [data] : [])] as const

export type TrainListSuspenseQueryKey = ReturnType<typeof trainListSuspenseQueryKey>

/**
 * @summary 我的模型列表
 * {@link /api/train/list}
 */
export async function trainListSuspense(data: TrainListMutationRequest, config: Partial<RequestConfig<TrainListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainListMutationResponse, ResponseErrorConfig<Error>, TrainListMutationRequest>({ method : "POST", url : `/api/train/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainListSuspenseQueryOptions(data: TrainListMutationRequest, config: Partial<RequestConfig<TrainListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainListSuspenseQueryKey(data)
  return queryOptions<TrainListMutationResponse, ResponseErrorConfig<Error>, TrainListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainListSuspense(data, config)
   },
  })
}

/**
 * @summary 我的模型列表
 * {@link /api/train/list}
 */
export function useTrainListSuspense<TData = TrainListMutationResponse, TQueryKey extends QueryKey = TrainListSuspenseQueryKey>(data: TrainListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TrainListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...trainListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}