/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainListMutationRequest, TrainListMutationResponse } from "../../types/trainTypes/TrainList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const trainListQueryKey = (data: TrainListMutationRequest) => [{ url: '/api/train/list' }, ...(data ? [data] : [])] as const

export type TrainListQueryKey = ReturnType<typeof trainListQueryKey>

/**
 * @summary 我的模型列表
 * {@link /api/train/list}
 */
export async function trainList(data: TrainListMutationRequest, config: Partial<RequestConfig<TrainListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainListMutationResponse, ResponseErrorConfig<Error>, TrainListMutationRequest>({ method : "POST", url : `/api/train/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainListQueryOptions(data: TrainListMutationRequest, config: Partial<RequestConfig<TrainListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainListQueryKey(data)
  return queryOptions<TrainListMutationResponse, ResponseErrorConfig<Error>, TrainListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainList(data, config)
   },
  })
}

/**
 * @summary 我的模型列表
 * {@link /api/train/list}
 */
export function useTrainList<TData = TrainListMutationResponse, TQueryData = TrainListMutationResponse, TQueryKey extends QueryKey = TrainListQueryKey>(data: TrainListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TrainListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainListQueryKey(data)

  const query = useQuery({
   ...trainListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}