/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainDetailMutationRequest, TrainDetailMutationResponse } from "../../types/trainTypes/TrainDetail";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const trainDetailSuspenseQueryKey = (data: TrainDetailMutationRequest) => [{ url: '/api/train/detail' }, ...(data ? [data] : [])] as const

export type TrainDetailSuspenseQueryKey = ReturnType<typeof trainDetailSuspenseQueryKey>

/**
 * @summary 训练详情
 * {@link /api/train/detail}
 */
export async function trainDetailSuspense(data: TrainDetailMutationRequest, config: Partial<RequestConfig<TrainDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainDetailMutationResponse, ResponseErrorConfig<Error>, TrainDetailMutationRequest>({ method : "POST", url : `/api/train/detail`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainDetailSuspenseQueryOptions(data: TrainDetailMutationRequest, config: Partial<RequestConfig<TrainDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainDetailSuspenseQueryKey(data)
  return queryOptions<TrainDetailMutationResponse, ResponseErrorConfig<Error>, TrainDetailMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainDetailSuspense(data, config)
   },
  })
}

/**
 * @summary 训练详情
 * {@link /api/train/detail}
 */
export function useTrainDetailSuspense<TData = TrainDetailMutationResponse, TQueryKey extends QueryKey = TrainDetailSuspenseQueryKey>(data: TrainDetailMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TrainDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainDetailSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...trainDetailSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}