/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainCreateMutationRequest, TrainCreateMutationResponse } from "../../types/trainTypes/TrainCreate";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const trainCreateQueryKey = (data: TrainCreateMutationRequest) => [{ url: '/api/train/create' }, ...(data ? [data] : [])] as const

export type TrainCreateQueryKey = ReturnType<typeof trainCreateQueryKey>

/**
 * @summary 创建训练
 * {@link /api/train/create}
 */
export async function trainCreate(data: TrainCreateMutationRequest, config: Partial<RequestConfig<TrainCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainCreateMutationResponse, ResponseErrorConfig<Error>, TrainCreateMutationRequest>({ method : "POST", url : `/api/train/create`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainCreateQueryOptions(data: TrainCreateMutationRequest, config: Partial<RequestConfig<TrainCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainCreateQueryKey(data)
  return queryOptions<TrainCreateMutationResponse, ResponseErrorConfig<Error>, TrainCreateMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainCreate(data, config)
   },
  })
}

/**
 * @summary 创建训练
 * {@link /api/train/create}
 */
export function useTrainCreate<TData = TrainCreateMutationResponse, TQueryData = TrainCreateMutationResponse, TQueryKey extends QueryKey = TrainCreateQueryKey>(data: TrainCreateMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TrainCreateMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainCreateMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainCreateQueryKey(data)

  const query = useQuery({
   ...trainCreateQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}