/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainSaveMutationRequest, TrainSaveMutationResponse } from "../../types/trainTypes/TrainSave";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const trainSaveSuspenseQueryKey = (data: TrainSaveMutationRequest) => [{ url: '/api/train/save' }, ...(data ? [data] : [])] as const

export type TrainSaveSuspenseQueryKey = ReturnType<typeof trainSaveSuspenseQueryKey>

/**
 * @summary 保存训练模型
 * {@link /api/train/save}
 */
export async function trainSaveSuspense(data: TrainSaveMutationRequest, config: Partial<RequestConfig<TrainSaveMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainSaveMutationResponse, ResponseErrorConfig<Error>, TrainSaveMutationRequest>({ method : "POST", url : `/api/train/save`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainSaveSuspenseQueryOptions(data: TrainSaveMutationRequest, config: Partial<RequestConfig<TrainSaveMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainSaveSuspenseQueryKey(data)
  return queryOptions<TrainSaveMutationResponse, ResponseErrorConfig<Error>, TrainSaveMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainSaveSuspense(data, config)
   },
  })
}

/**
 * @summary 保存训练模型
 * {@link /api/train/save}
 */
export function useTrainSaveSuspense<TData = TrainSaveMutationResponse, TQueryKey extends QueryKey = TrainSaveSuspenseQueryKey>(data: TrainSaveMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TrainSaveMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainSaveMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainSaveSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...trainSaveSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}