/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainDeleteMutationRequest, TrainDeleteMutationResponse } from "../../types/trainTypes/TrainDelete";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const trainDeleteQueryKey = (data: TrainDeleteMutationRequest) => [{ url: '/api/train/delete' }, ...(data ? [data] : [])] as const

export type TrainDeleteQueryKey = ReturnType<typeof trainDeleteQueryKey>

/**
 * @summary 我的模型删除
 * {@link /api/train/delete}
 */
export async function trainDelete(data: TrainDeleteMutationRequest, config: Partial<RequestConfig<TrainDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainDeleteMutationResponse, ResponseErrorConfig<Error>, TrainDeleteMutationRequest>({ method : "POST", url : `/api/train/delete`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainDeleteQueryOptions(data: TrainDeleteMutationRequest, config: Partial<RequestConfig<TrainDeleteMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainDeleteQueryKey(data)
  return queryOptions<TrainDeleteMutationResponse, ResponseErrorConfig<Error>, TrainDeleteMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainDelete(data, config)
   },
  })
}

/**
 * @summary 我的模型删除
 * {@link /api/train/delete}
 */
export function useTrainDelete<TData = TrainDeleteMutationResponse, TQueryData = TrainDeleteMutationResponse, TQueryKey extends QueryKey = TrainDeleteQueryKey>(data: TrainDeleteMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TrainDeleteMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainDeleteMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainDeleteQueryKey(data)

  const query = useQuery({
   ...trainDeleteQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}