/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TrainResultMutationRequest, TrainResultMutationResponse } from "../../types/trainTypes/TrainResult";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const trainResultQueryKey = (data: TrainResultMutationRequest) => [{ url: '/api/train/result' }, ...(data ? [data] : [])] as const

export type TrainResultQueryKey = ReturnType<typeof trainResultQueryKey>

/**
 * @summary 查询训练结果
 * {@link /api/train/result}
 */
export async function trainResult(data: TrainResultMutationRequest, config: Partial<RequestConfig<TrainResultMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TrainResultMutationResponse, ResponseErrorConfig<Error>, TrainResultMutationRequest>({ method : "POST", url : `/api/train/result`, data : requestData, ... requestConfig })  
  return res.data
}

export function trainResultQueryOptions(data: TrainResultMutationRequest, config: Partial<RequestConfig<TrainResultMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = trainResultQueryKey(data)
  return queryOptions<TrainResultMutationResponse, ResponseErrorConfig<Error>, TrainResultMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return trainResult(data, config)
   },
  })
}

/**
 * @summary 查询训练结果
 * {@link /api/train/result}
 */
export function useTrainResult<TData = TrainResultMutationResponse, TQueryData = TrainResultMutationResponse, TQueryKey extends QueryKey = TrainResultQueryKey>(data: TrainResultMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TrainResultMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TrainResultMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? trainResultQueryKey(data)

  const query = useQuery({
   ...trainResultQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}