/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ModelToolsSearchMutationRequest, ModelToolsSearchMutationResponse } from "../../types/model_toolsTypes/ModelToolsSearch";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const modelToolsSearchSuspenseQueryKey = (data: ModelToolsSearchMutationRequest) => [{ url: '/api/model_tools/search' }, ...(data ? [data] : [])] as const

export type ModelToolsSearchSuspenseQueryKey = ReturnType<typeof modelToolsSearchSuspenseQueryKey>

/**
 * @summary 搜索
 * {@link /api/model_tools/search}
 */
export async function modelToolsSearchSuspense(data: ModelToolsSearchMutationRequest, config: Partial<RequestConfig<ModelToolsSearchMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ModelToolsSearchMutationResponse, ResponseErrorConfig<Error>, ModelToolsSearchMutationRequest>({ method : "POST", url : `/api/model_tools/search`, data : requestData, ... requestConfig })  
  return res.data
}

export function modelToolsSearchSuspenseQueryOptions(data: ModelToolsSearchMutationRequest, config: Partial<RequestConfig<ModelToolsSearchMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = modelToolsSearchSuspenseQueryKey(data)
  return queryOptions<ModelToolsSearchMutationResponse, ResponseErrorConfig<Error>, ModelToolsSearchMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return modelToolsSearchSuspense(data, config)
   },
  })
}

/**
 * @summary 搜索
 * {@link /api/model_tools/search}
 */
export function useModelToolsSearchSuspense<TData = ModelToolsSearchMutationResponse, TQueryKey extends QueryKey = ModelToolsSearchSuspenseQueryKey>(data: ModelToolsSearchMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ModelToolsSearchMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ModelToolsSearchMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? modelToolsSearchSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...modelToolsSearchSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}