/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { ModelToolsSearchMutationRequest, ModelToolsSearchMutationResponse } from "../../types/model_toolsTypes/ModelToolsSearch";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const modelToolsSearchQueryKey = (data: ModelToolsSearchMutationRequest) => [{ url: '/api/model_tools/search' }, ...(data ? [data] : [])] as const

export type ModelToolsSearchQueryKey = ReturnType<typeof modelToolsSearchQueryKey>

/**
 * @summary 搜索
 * {@link /api/model_tools/search}
 */
export async function modelToolsSearch(data: ModelToolsSearchMutationRequest, config: Partial<RequestConfig<ModelToolsSearchMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ModelToolsSearchMutationResponse, ResponseErrorConfig<Error>, ModelToolsSearchMutationRequest>({ method : "POST", url : `/api/model_tools/search`, data : requestData, ... requestConfig })  
  return res.data
}

export function modelToolsSearchQueryOptions(data: ModelToolsSearchMutationRequest, config: Partial<RequestConfig<ModelToolsSearchMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = modelToolsSearchQueryKey(data)
  return queryOptions<ModelToolsSearchMutationResponse, ResponseErrorConfig<Error>, ModelToolsSearchMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return modelToolsSearch(data, config)
   },
  })
}

/**
 * @summary 搜索
 * {@link /api/model_tools/search}
 */
export function useModelToolsSearch<TData = ModelToolsSearchMutationResponse, TQueryData = ModelToolsSearchMutationResponse, TQueryKey extends QueryKey = ModelToolsSearchQueryKey>(data: ModelToolsSearchMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<ModelToolsSearchMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<ModelToolsSearchMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? modelToolsSearchQueryKey(data)

  const query = useQuery({
   ...modelToolsSearchQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}