/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonUploadMutationRequest, CommonUploadMutationResponse } from "../../types/commonTypes/CommonUpload";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const commonUploadQueryKey = (data: CommonUploadMutationRequest) => [{ url: '/api/common/upload' }, ...(data ? [data] : [])] as const

export type CommonUploadQueryKey = ReturnType<typeof commonUploadQueryKey>

/**
 * @summary 上传文件
 * {@link /api/common/upload}
 */
export async function commonUpload(data: CommonUploadMutationRequest, config: Partial<RequestConfig<CommonUploadMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  const formData = new FormData()
  if (requestData) {
   Object.keys(requestData).forEach((key) => {
     const value = requestData[key as keyof typeof requestData];
     if (typeof value === 'string' || (value as unknown) instanceof Blob) {
       formData.append(key, value as unknown as string | Blob);
     } else {
       formData.append(key, JSON.stringify(value));
     }
   })
  }  
  const res = await request<CommonUploadMutationResponse, ResponseErrorConfig<Error>, CommonUploadMutationRequest>({ method : "POST", url : `/api/common/upload`, data : formData, ... requestConfig })  
  return res.data
}

export function commonUploadQueryOptions(data: CommonUploadMutationRequest, config: Partial<RequestConfig<CommonUploadMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonUploadQueryKey(data)
  return queryOptions<CommonUploadMutationResponse, ResponseErrorConfig<Error>, CommonUploadMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonUpload(data, config)
   },
  })
}

/**
 * @summary 上传文件
 * {@link /api/common/upload}
 */
export function useCommonUpload<TData = CommonUploadMutationResponse, TQueryData = CommonUploadMutationResponse, TQueryKey extends QueryKey = CommonUploadQueryKey>(data: CommonUploadMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<CommonUploadMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonUploadMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonUploadQueryKey(data)

  const query = useQuery({
   ...commonUploadQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}