/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonAddUserMutationRequest, CommonAddUserMutationResponse } from "../../types/commonTypes/CommonAddUser";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const commonAddUserQueryKey = (data: CommonAddUserMutationRequest) => [{ url: '/api/common/add_user' }, ...(data ? [data] : [])] as const

export type CommonAddUserQueryKey = ReturnType<typeof commonAddUserQueryKey>

/**
 * @summary 添加用户内部使用
 * {@link /api/common/add_user}
 */
export async function commonAddUser(data: CommonAddUserMutationRequest, config: Partial<RequestConfig<CommonAddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonAddUserMutationResponse, ResponseErrorConfig<Error>, CommonAddUserMutationRequest>({ method : "POST", url : `/api/common/add_user`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonAddUserQueryOptions(data: CommonAddUserMutationRequest, config: Partial<RequestConfig<CommonAddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonAddUserQueryKey(data)
  return queryOptions<CommonAddUserMutationResponse, ResponseErrorConfig<Error>, CommonAddUserMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonAddUser(data, config)
   },
  })
}

/**
 * @summary 添加用户内部使用
 * {@link /api/common/add_user}
 */
export function useCommonAddUser<TData = CommonAddUserMutationResponse, TQueryData = CommonAddUserMutationResponse, TQueryKey extends QueryKey = CommonAddUserQueryKey>(data: CommonAddUserMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<CommonAddUserMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonAddUserMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonAddUserQueryKey(data)

  const query = useQuery({
   ...commonAddUserQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}