/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonSignStsMutationRequest, CommonSignStsMutationResponse } from "../../types/commonTypes/CommonSignSts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const commonSignStsSuspenseQueryKey = (data?: CommonSignStsMutationRequest) => [{ url: '/api/common/sign_sts' }, ...(data ? [data] : [])] as const

export type CommonSignStsSuspenseQueryKey = ReturnType<typeof commonSignStsSuspenseQueryKey>

/**
 * @summary 获取STS临时凭证
 * {@link /api/common/sign_sts}
 */
export async function commonSignStsSuspense(data?: CommonSignStsMutationRequest, config: Partial<RequestConfig<CommonSignStsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonSignStsMutationResponse, ResponseErrorConfig<Error>, CommonSignStsMutationRequest>({ method : "POST", url : `/api/common/sign_sts`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonSignStsSuspenseQueryOptions(data?: CommonSignStsMutationRequest, config: Partial<RequestConfig<CommonSignStsMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonSignStsSuspenseQueryKey(data)
  return queryOptions<CommonSignStsMutationResponse, ResponseErrorConfig<Error>, CommonSignStsMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonSignStsSuspense(data, config)
   },
  })
}

/**
 * @summary 获取STS临时凭证
 * {@link /api/common/sign_sts}
 */
export function useCommonSignStsSuspense<TData = CommonSignStsMutationResponse, TQueryKey extends QueryKey = CommonSignStsSuspenseQueryKey>(data?: CommonSignStsMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<CommonSignStsMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonSignStsMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonSignStsSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...commonSignStsSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}