/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonResetDeviceMutationRequest, CommonResetDeviceMutationResponse } from "../../types/commonTypes/CommonResetDevice";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const commonResetDeviceSuspenseQueryKey = (data: CommonResetDeviceMutationRequest) => [{ url: '/api/common/reset_device' }, ...(data ? [data] : [])] as const

export type CommonResetDeviceSuspenseQueryKey = ReturnType<typeof commonResetDeviceSuspenseQueryKey>

/**
 * @summary 重置用户设备内部使用
 * {@link /api/common/reset_device}
 */
export async function commonResetDeviceSuspense(data: CommonResetDeviceMutationRequest, config: Partial<RequestConfig<CommonResetDeviceMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonResetDeviceMutationResponse, ResponseErrorConfig<Error>, CommonResetDeviceMutationRequest>({ method : "POST", url : `/api/common/reset_device`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonResetDeviceSuspenseQueryOptions(data: CommonResetDeviceMutationRequest, config: Partial<RequestConfig<CommonResetDeviceMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonResetDeviceSuspenseQueryKey(data)
  return queryOptions<CommonResetDeviceMutationResponse, ResponseErrorConfig<Error>, CommonResetDeviceMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonResetDeviceSuspense(data, config)
   },
  })
}

/**
 * @summary 重置用户设备内部使用
 * {@link /api/common/reset_device}
 */
export function useCommonResetDeviceSuspense<TData = CommonResetDeviceMutationResponse, TQueryKey extends QueryKey = CommonResetDeviceSuspenseQueryKey>(data: CommonResetDeviceMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<CommonResetDeviceMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonResetDeviceMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonResetDeviceSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...commonResetDeviceSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}