/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonSignStsMutationRequest, CommonSignStsMutationResponse } from "../../types/commonTypes/CommonSignSts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const commonSignStsQueryKey = (data?: CommonSignStsMutationRequest) => [{ url: '/api/common/sign_sts' }, ...(data ? [data] : [])] as const

export type CommonSignStsQueryKey = ReturnType<typeof commonSignStsQueryKey>

/**
 * @summary 获取STS临时凭证
 * {@link /api/common/sign_sts}
 */
export async function commonSignSts(data?: CommonSignStsMutationRequest, config: Partial<RequestConfig<CommonSignStsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonSignStsMutationResponse, ResponseErrorConfig<Error>, CommonSignStsMutationRequest>({ method : "POST", url : `/api/common/sign_sts`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonSignStsQueryOptions(data?: CommonSignStsMutationRequest, config: Partial<RequestConfig<CommonSignStsMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonSignStsQueryKey(data)
  return queryOptions<CommonSignStsMutationResponse, ResponseErrorConfig<Error>, CommonSignStsMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonSignSts(data, config)
   },
  })
}

/**
 * @summary 获取STS临时凭证
 * {@link /api/common/sign_sts}
 */
export function useCommonSignSts<TData = CommonSignStsMutationResponse, TQueryData = CommonSignStsMutationResponse, TQueryKey extends QueryKey = CommonSignStsQueryKey>(data?: CommonSignStsMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<CommonSignStsMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonSignStsMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonSignStsQueryKey(data)

  const query = useQuery({
   ...commonSignStsQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}