/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonBatchAddUserMutationRequest, CommonBatchAddUserMutationResponse } from "../../types/commonTypes/CommonBatchAddUser";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const commonBatchAddUserSuspenseQueryKey = (data: CommonBatchAddUserMutationRequest) => [{ url: '/api/common/batch_add_user' }, ...(data ? [data] : [])] as const

export type CommonBatchAddUserSuspenseQueryKey = ReturnType<typeof commonBatchAddUserSuspenseQueryKey>

/**
 * @summary 批量添加用户内部使用
 * {@link /api/common/batch_add_user}
 */
export async function commonBatchAddUserSuspense(data: CommonBatchAddUserMutationRequest, config: Partial<RequestConfig<CommonBatchAddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonBatchAddUserMutationResponse, ResponseErrorConfig<Error>, CommonBatchAddUserMutationRequest>({ method : "POST", url : `/api/common/batch_add_user`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonBatchAddUserSuspenseQueryOptions(data: CommonBatchAddUserMutationRequest, config: Partial<RequestConfig<CommonBatchAddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonBatchAddUserSuspenseQueryKey(data)
  return queryOptions<CommonBatchAddUserMutationResponse, ResponseErrorConfig<Error>, CommonBatchAddUserMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonBatchAddUserSuspense(data, config)
   },
  })
}

/**
 * @summary 批量添加用户内部使用
 * {@link /api/common/batch_add_user}
 */
export function useCommonBatchAddUserSuspense<TData = CommonBatchAddUserMutationResponse, TQueryKey extends QueryKey = CommonBatchAddUserSuspenseQueryKey>(data: CommonBatchAddUserMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<CommonBatchAddUserMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonBatchAddUserMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonBatchAddUserSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...commonBatchAddUserSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}