/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonAddUserMutationRequest, CommonAddUserMutationResponse } from "../../types/commonTypes/CommonAddUser";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const commonAddUserSuspenseQueryKey = (data: CommonAddUserMutationRequest) => [{ url: '/api/common/add_user' }, ...(data ? [data] : [])] as const

export type CommonAddUserSuspenseQueryKey = ReturnType<typeof commonAddUserSuspenseQueryKey>

/**
 * @summary 添加用户内部使用
 * {@link /api/common/add_user}
 */
export async function commonAddUserSuspense(data: CommonAddUserMutationRequest, config: Partial<RequestConfig<CommonAddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonAddUserMutationResponse, ResponseErrorConfig<Error>, CommonAddUserMutationRequest>({ method : "POST", url : `/api/common/add_user`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonAddUserSuspenseQueryOptions(data: CommonAddUserMutationRequest, config: Partial<RequestConfig<CommonAddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonAddUserSuspenseQueryKey(data)
  return queryOptions<CommonAddUserMutationResponse, ResponseErrorConfig<Error>, CommonAddUserMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonAddUserSuspense(data, config)
   },
  })
}

/**
 * @summary 添加用户内部使用
 * {@link /api/common/add_user}
 */
export function useCommonAddUserSuspense<TData = CommonAddUserMutationResponse, TQueryKey extends QueryKey = CommonAddUserSuspenseQueryKey>(data: CommonAddUserMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<CommonAddUserMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonAddUserMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonAddUserSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...commonAddUserSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}