/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonResetPasswordMutationRequest, CommonResetPasswordMutationResponse } from "../../types/commonTypes/CommonResetPassword";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const commonResetPasswordQueryKey = (data: CommonResetPasswordMutationRequest) => [{ url: '/api/common/reset_password' }, ...(data ? [data] : [])] as const

export type CommonResetPasswordQueryKey = ReturnType<typeof commonResetPasswordQueryKey>

/**
 * @summary 重置用户密码内部使用
 * {@link /api/common/reset_password}
 */
export async function commonResetPassword(data: CommonResetPasswordMutationRequest, config: Partial<RequestConfig<CommonResetPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonResetPasswordMutationResponse, ResponseErrorConfig<Error>, CommonResetPasswordMutationRequest>({ method : "POST", url : `/api/common/reset_password`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonResetPasswordQueryOptions(data: CommonResetPasswordMutationRequest, config: Partial<RequestConfig<CommonResetPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonResetPasswordQueryKey(data)
  return queryOptions<CommonResetPasswordMutationResponse, ResponseErrorConfig<Error>, CommonResetPasswordMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonResetPassword(data, config)
   },
  })
}

/**
 * @summary 重置用户密码内部使用
 * {@link /api/common/reset_password}
 */
export function useCommonResetPassword<TData = CommonResetPasswordMutationResponse, TQueryData = CommonResetPasswordMutationResponse, TQueryKey extends QueryKey = CommonResetPasswordQueryKey>(data: CommonResetPasswordMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<CommonResetPasswordMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonResetPasswordMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonResetPasswordQueryKey(data)

  const query = useQuery({
   ...commonResetPasswordQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}