/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonResetPasswordMutationRequest, CommonResetPasswordMutationResponse } from "../../types/commonTypes/CommonResetPassword";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const commonResetPasswordSuspenseQueryKey = (data: CommonResetPasswordMutationRequest) => [{ url: '/api/common/reset_password' }, ...(data ? [data] : [])] as const

export type CommonResetPasswordSuspenseQueryKey = ReturnType<typeof commonResetPasswordSuspenseQueryKey>

/**
 * @summary 重置用户密码内部使用
 * {@link /api/common/reset_password}
 */
export async function commonResetPasswordSuspense(data: CommonResetPasswordMutationRequest, config: Partial<RequestConfig<CommonResetPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonResetPasswordMutationResponse, ResponseErrorConfig<Error>, CommonResetPasswordMutationRequest>({ method : "POST", url : `/api/common/reset_password`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonResetPasswordSuspenseQueryOptions(data: CommonResetPasswordMutationRequest, config: Partial<RequestConfig<CommonResetPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonResetPasswordSuspenseQueryKey(data)
  return queryOptions<CommonResetPasswordMutationResponse, ResponseErrorConfig<Error>, CommonResetPasswordMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonResetPasswordSuspense(data, config)
   },
  })
}

/**
 * @summary 重置用户密码内部使用
 * {@link /api/common/reset_password}
 */
export function useCommonResetPasswordSuspense<TData = CommonResetPasswordMutationResponse, TQueryKey extends QueryKey = CommonResetPasswordSuspenseQueryKey>(data: CommonResetPasswordMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<CommonResetPasswordMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonResetPasswordMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonResetPasswordSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...commonResetPasswordSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}