/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonResetDeviceMutationRequest, CommonResetDeviceMutationResponse } from "../../types/commonTypes/CommonResetDevice";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const commonResetDeviceQueryKey = (data: CommonResetDeviceMutationRequest) => [{ url: '/api/common/reset_device' }, ...(data ? [data] : [])] as const

export type CommonResetDeviceQueryKey = ReturnType<typeof commonResetDeviceQueryKey>

/**
 * @summary 重置用户设备内部使用
 * {@link /api/common/reset_device}
 */
export async function commonResetDevice(data: CommonResetDeviceMutationRequest, config: Partial<RequestConfig<CommonResetDeviceMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonResetDeviceMutationResponse, ResponseErrorConfig<Error>, CommonResetDeviceMutationRequest>({ method : "POST", url : `/api/common/reset_device`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonResetDeviceQueryOptions(data: CommonResetDeviceMutationRequest, config: Partial<RequestConfig<CommonResetDeviceMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonResetDeviceQueryKey(data)
  return queryOptions<CommonResetDeviceMutationResponse, ResponseErrorConfig<Error>, CommonResetDeviceMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonResetDevice(data, config)
   },
  })
}

/**
 * @summary 重置用户设备内部使用
 * {@link /api/common/reset_device}
 */
export function useCommonResetDevice<TData = CommonResetDeviceMutationResponse, TQueryData = CommonResetDeviceMutationResponse, TQueryKey extends QueryKey = CommonResetDeviceQueryKey>(data: CommonResetDeviceMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<CommonResetDeviceMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonResetDeviceMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonResetDeviceQueryKey(data)

  const query = useQuery({
   ...commonResetDeviceQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}