/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { CommonBatchAddUserMutationRequest, CommonBatchAddUserMutationResponse } from "../../types/commonTypes/CommonBatchAddUser";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const commonBatchAddUserQueryKey = (data: CommonBatchAddUserMutationRequest) => [{ url: '/api/common/batch_add_user' }, ...(data ? [data] : [])] as const

export type CommonBatchAddUserQueryKey = ReturnType<typeof commonBatchAddUserQueryKey>

/**
 * @summary 批量添加用户内部使用
 * {@link /api/common/batch_add_user}
 */
export async function commonBatchAddUser(data: CommonBatchAddUserMutationRequest, config: Partial<RequestConfig<CommonBatchAddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CommonBatchAddUserMutationResponse, ResponseErrorConfig<Error>, CommonBatchAddUserMutationRequest>({ method : "POST", url : `/api/common/batch_add_user`, data : requestData, ... requestConfig })  
  return res.data
}

export function commonBatchAddUserQueryOptions(data: CommonBatchAddUserMutationRequest, config: Partial<RequestConfig<CommonBatchAddUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = commonBatchAddUserQueryKey(data)
  return queryOptions<CommonBatchAddUserMutationResponse, ResponseErrorConfig<Error>, CommonBatchAddUserMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return commonBatchAddUser(data, config)
   },
  })
}

/**
 * @summary 批量添加用户内部使用
 * {@link /api/common/batch_add_user}
 */
export function useCommonBatchAddUser<TData = CommonBatchAddUserMutationResponse, TQueryData = CommonBatchAddUserMutationResponse, TQueryKey extends QueryKey = CommonBatchAddUserQueryKey>(data: CommonBatchAddUserMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<CommonBatchAddUserMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommonBatchAddUserMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? commonBatchAddUserQueryKey(data)

  const query = useQuery({
   ...commonBatchAddUserQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}