/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1NotificationMarkReadReq } from "../v1/NotificationMarkReadReq";
import type { V1NotificationMarkReadRes } from "../v1/NotificationMarkReadRes";

export type NotificationMarkRead200 = V1NotificationMarkReadRes;

export type NotificationMarkReadMutationRequest = V1NotificationMarkReadReq;

export type NotificationMarkReadMutationResponse = NotificationMarkRead200;

export type NotificationMarkReadMutation = {
    Response: NotificationMarkRead200;
    Request: NotificationMarkReadMutationRequest;
    Errors: any;
};