/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1NotificationListReq } from "../v1/NotificationListReq";
import type { V1NotificationListRes } from "../v1/NotificationListRes";

export type NotificationList200 = V1NotificationListRes;

export type NotificationListMutationRequest = V1NotificationListReq;

export type NotificationListMutationResponse = NotificationList200;

export type NotificationListMutation = {
    Response: NotificationList200;
    Request: NotificationListMutationRequest;
    Errors: any;
};