/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GuideReport200, GuideReportMutationRequest, GuideReportMutationResponse } from "../../types/guideTypes/GuideReport";
import { v1GuideReportReqSchema } from "../v1/guideReportReqSchema";
import { v1GuideReportResSchema } from "../v1/guideReportResSchema";
import { z } from "zod/v4";

export const guideReport200Schema = v1GuideReportResSchema as unknown as z.ZodType<GuideReport200>

export const guideReportMutationRequestSchema = v1GuideReportReqSchema as unknown as z.ZodType<GuideReportMutationRequest>

export const guideReportMutationResponseSchema = guideReport200Schema as unknown as z.ZodType<GuideReportMutationResponse>