/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PointsFindAccountPointAndLevel200, PointsFindAccountPointAndLevelMutationRequest, PointsFindAccountPointAndLevelMutationResponse } from "../../types/pointsTypes/PointsFindAccountPointAndLevel";
import { v1PointsFindAccountPointAndLevelReqSchema } from "../v1/pointsFindAccountPointAndLevelReqSchema";
import { v1PointsFindAccountPointAndLevelResSchema } from "../v1/pointsFindAccountPointAndLevelResSchema";
import { z } from "zod/v4";

export const pointsFindAccountPointAndLevel200Schema = v1PointsFindAccountPointAndLevelResSchema as unknown as z.ZodType<PointsFindAccountPointAndLevel200>

export const pointsFindAccountPointAndLevelMutationRequestSchema = v1PointsFindAccountPointAndLevelReqSchema as unknown as z.ZodType<PointsFindAccountPointAndLevelMutationRequest>

export const pointsFindAccountPointAndLevelMutationResponseSchema = pointsFindAccountPointAndLevel200Schema as unknown as z.ZodType<PointsFindAccountPointAndLevelMutationResponse>