/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PointsCreateLevelType200, PointsCreateLevelTypeMutationRequest, PointsCreateLevelTypeMutationResponse } from "../../types/pointsTypes/PointsCreateLevelType";
import { v1PointsCreateLevelTypeReqSchema } from "../v1/pointsCreateLevelTypeReqSchema";
import { v1PointsCreateLevelTypeResSchema } from "../v1/pointsCreateLevelTypeResSchema";
import { z } from "zod/v4";

export const pointsCreateLevelType200Schema = v1PointsCreateLevelTypeResSchema as unknown as z.ZodType<PointsCreateLevelType200>

export const pointsCreateLevelTypeMutationRequestSchema = v1PointsCreateLevelTypeReqSchema as unknown as z.ZodType<PointsCreateLevelTypeMutationRequest>

export const pointsCreateLevelTypeMutationResponseSchema = pointsCreateLevelType200Schema as unknown as z.ZodType<PointsCreateLevelTypeMutationResponse>