/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PointsCreatePointType200, PointsCreatePointTypeMutationRequest, PointsCreatePointTypeMutationResponse } from "../../types/pointsTypes/PointsCreatePointType";
import { v1PointsCreatePointTypeReqSchema } from "../v1/pointsCreatePointTypeReqSchema";
import { v1PointsCreatePointTypeResSchema } from "../v1/pointsCreatePointTypeResSchema";
import { z } from "zod/v4";

export const pointsCreatePointType200Schema = v1PointsCreatePointTypeResSchema as unknown as z.ZodType<PointsCreatePointType200>

export const pointsCreatePointTypeMutationRequestSchema = v1PointsCreatePointTypeReqSchema as unknown as z.ZodType<PointsCreatePointTypeMutationRequest>

export const pointsCreatePointTypeMutationResponseSchema = pointsCreatePointType200Schema as unknown as z.ZodType<PointsCreatePointTypeMutationResponse>