/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PointsCreatePointDetail200, PointsCreatePointDetailMutationRequest, PointsCreatePointDetailMutationResponse } from "../../types/pointsTypes/PointsCreatePointDetail";
import { v1PointsCreatePointDetailReqSchema } from "../v1/pointsCreatePointDetailReqSchema";
import { v1PointsCreatePointDetailResSchema } from "../v1/pointsCreatePointDetailResSchema";
import { z } from "zod/v4";

export const pointsCreatePointDetail200Schema = v1PointsCreatePointDetailResSchema as unknown as z.ZodType<PointsCreatePointDetail200>

export const pointsCreatePointDetailMutationRequestSchema = v1PointsCreatePointDetailReqSchema as unknown as z.ZodType<PointsCreatePointDetailMutationRequest>

export const pointsCreatePointDetailMutationResponseSchema = pointsCreatePointDetail200Schema as unknown as z.ZodType<PointsCreatePointDetailMutationResponse>