/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TopicLikeLike200, TopicLikeLikeMutationRequest, TopicLikeLikeMutationResponse } from "../../types/topic_likeTypes/TopicLikeLike";
import { v1TopicLikeLikeReqSchema } from "../v1/topicLikeLikeReqSchema";
import { v1TopicLikeLikeResSchema } from "../v1/topicLikeLikeResSchema";
import { z } from "zod/v4";

export const topicLikeLike200Schema = v1TopicLikeLikeResSchema as unknown as z.ZodType<TopicLikeLike200>

export const topicLikeLikeMutationRequestSchema = v1TopicLikeLikeReqSchema as unknown as z.ZodType<TopicLikeLikeMutationRequest>

export const topicLikeLikeMutationResponseSchema = topicLikeLike200Schema as unknown as z.ZodType<TopicLikeLikeMutationResponse>