/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionCreateReq } from "../v1/SessionCreateReq";
import type { V1SessionCreateRes } from "../v1/SessionCreateRes";

export type SessionCreate200 = V1SessionCreateRes;

export type SessionCreateMutationRequest = V1SessionCreateReq;

export type SessionCreateMutationResponse = SessionCreate200;

export type SessionCreateMutation = {
    Response: SessionCreate200;
    Request: SessionCreateMutationRequest;
    Errors: any;
};