/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionDetailReq } from "../v1/SessionDetailReq";
import type { V1SessionDetailRes } from "../v1/SessionDetailRes";

export type SessionDetail200 = V1SessionDetailRes;

export type SessionDetailMutationRequest = V1SessionDetailReq;

export type SessionDetailMutationResponse = SessionDetail200;

export type SessionDetailMutation = {
    Response: SessionDetail200;
    Request: SessionDetailMutationRequest;
    Errors: any;
};