/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionDeleteReq } from "../v1/SessionDeleteReq";
import type { V1SessionDeleteRes } from "../v1/SessionDeleteRes";

export type SessionDelete200 = V1SessionDeleteRes;

export type SessionDeleteMutationRequest = V1SessionDeleteReq;

export type SessionDeleteMutationResponse = SessionDelete200;

export type SessionDeleteMutation = {
    Response: SessionDelete200;
    Request: SessionDeleteMutationRequest;
    Errors: any;
};