/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskListMutationRequest, TaskListMutationResponse } from "../../types/taskTypes/TaskList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskListQueryKey = (data?: TaskListMutationRequest) => [{ url: '/api/task/list' }, ...(data ? [data] : [])] as const

export type TaskListQueryKey = ReturnType<typeof taskListQueryKey>

/**
 * @summary 任务列表
 * {@link /api/task/list}
 */
export async function taskList(data?: TaskListMutationRequest, config: Partial<RequestConfig<TaskListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskListMutationResponse, ResponseErrorConfig<Error>, TaskListMutationRequest>({ method : "POST", url : `/api/task/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskListQueryOptions(data?: TaskListMutationRequest, config: Partial<RequestConfig<TaskListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskListQueryKey(data)
  return queryOptions<TaskListMutationResponse, ResponseErrorConfig<Error>, TaskListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskList(data, config)
   },
  })
}

/**
 * @summary 任务列表
 * {@link /api/task/list}
 */
export function useTaskList<TData = TaskListMutationResponse, TQueryData = TaskListMutationResponse, TQueryKey extends QueryKey = TaskListQueryKey>(data?: TaskListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskListQueryKey(data)

  const query = useQuery({
   ...taskListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}