/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskListMutationRequest, TaskListMutationResponse } from "../../types/taskTypes/TaskList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskListSuspenseQueryKey = (data?: TaskListMutationRequest) => [{ url: '/api/task/list' }, ...(data ? [data] : [])] as const

export type TaskListSuspenseQueryKey = ReturnType<typeof taskListSuspenseQueryKey>

/**
 * @summary 任务列表
 * {@link /api/task/list}
 */
export async function taskListSuspense(data?: TaskListMutationRequest, config: Partial<RequestConfig<TaskListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskListMutationResponse, ResponseErrorConfig<Error>, TaskListMutationRequest>({ method : "POST", url : `/api/task/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskListSuspenseQueryOptions(data?: TaskListMutationRequest, config: Partial<RequestConfig<TaskListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskListSuspenseQueryKey(data)
  return queryOptions<TaskListMutationResponse, ResponseErrorConfig<Error>, TaskListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskListSuspense(data, config)
   },
  })
}

/**
 * @summary 任务列表
 * {@link /api/task/list}
 */
export function useTaskListSuspense<TData = TaskListMutationResponse, TQueryKey extends QueryKey = TaskListSuspenseQueryKey>(data?: TaskListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}