/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TopicCommentAdd200, TopicCommentAddMutationRequest, TopicCommentAddMutationResponse } from "../../types/topic_commentTypes/TopicCommentAdd";
import { v1TopicCommentAddReqSchema } from "../v1/topicCommentAddReqSchema";
import { v1TopicCommentAddResSchema } from "../v1/topicCommentAddResSchema";
import { z } from "zod/v4";

export const topicCommentAdd200Schema = v1TopicCommentAddResSchema as unknown as z.ZodType<TopicCommentAdd200>

export const topicCommentAddMutationRequestSchema = v1TopicCommentAddReqSchema as unknown as z.ZodType<TopicCommentAddMutationRequest>

export const topicCommentAddMutationResponseSchema = topicCommentAdd200Schema as unknown as z.ZodType<TopicCommentAddMutationResponse>