/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SessionList200, SessionListMutationRequest, SessionListMutationResponse } from "../../types/sessionTypes/SessionList";
import { v1SessionListReqSchema } from "../v1/sessionListReqSchema";
import { v1SessionListResSchema } from "../v1/sessionListResSchema";
import { z } from "zod/v4";

export const sessionList200Schema = v1SessionListResSchema as unknown as z.ZodType<SessionList200>

export const sessionListMutationRequestSchema = v1SessionListReqSchema as unknown as z.ZodType<SessionListMutationRequest>

export const sessionListMutationResponseSchema = sessionList200Schema as unknown as z.ZodType<SessionListMutationResponse>