/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SessionRename200, SessionRenameMutationRequest, SessionRenameMutationResponse } from "../../types/sessionTypes/SessionRename";
import { v1SessionRenameReqSchema } from "../v1/sessionRenameReqSchema";
import { v1SessionRenameResSchema } from "../v1/sessionRenameResSchema";
import { z } from "zod/v4";

export const sessionRename200Schema = v1SessionRenameResSchema as unknown as z.ZodType<SessionRename200>

export const sessionRenameMutationRequestSchema = v1SessionRenameReqSchema as unknown as z.ZodType<SessionRenameMutationRequest>

export const sessionRenameMutationResponseSchema = sessionRename200Schema as unknown as z.ZodType<SessionRenameMutationResponse>