/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CommentLikeLike200, CommentLikeLikeMutationRequest, CommentLikeLikeMutationResponse } from "../../types/comment_likeTypes/CommentLikeLike";
import { v1CommentLikeLikeReqSchema } from "../v1/commentLikeLikeReqSchema";
import { v1CommentLikeLikeResSchema } from "../v1/commentLikeLikeResSchema";
import { z } from "zod/v4";

export const commentLikeLike200Schema = v1CommentLikeLikeResSchema as unknown as z.ZodType<CommentLikeLike200>

export const commentLikeLikeMutationRequestSchema = v1CommentLikeLikeReqSchema as unknown as z.ZodType<CommentLikeLikeMutationRequest>

export const commentLikeLikeMutationResponseSchema = commentLikeLike200Schema as unknown as z.ZodType<CommentLikeLikeMutationResponse>