/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountChangePasswordReq } from "../../types/v1/AccountChangePasswordReq";
import { z } from "zod/v4";

export const v1AccountChangePasswordReqSchema = z.object({
    "old_password": z.string(),
"new_password": z.string()
    }) as unknown as z.ZodType<V1AccountChangePasswordReq>