/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountAvatarRes } from "../../types/v1/AccountAvatarRes";
import { z } from "zod/v4";

export const v1AccountAvatarResSchema = z.object({
    "avatar": z.string()
    }) as unknown as z.ZodType<V1AccountAvatarRes>