/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountDeviceListRes } from "../../types/v1/AccountDeviceListRes";
import { v1DeviceInfoSchema } from "./deviceInfoSchema";
import { z } from "zod/v4";

export const v1AccountDeviceListResSchema = z.object({
    get "list"(){
                return z.array(v1DeviceInfoSchema)
              }
    }) as unknown as z.ZodType<V1AccountDeviceListRes>