/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountChangePasswordRes } from "../../types/v1/AccountChangePasswordRes";
import { z } from "zod/v4";

export const v1AccountChangePasswordResSchema = z.object({
    
    }) as unknown as z.ZodType<V1AccountChangePasswordRes>