/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountLoginReq } from "../../types/v1/AccountLoginReq";
import { z } from "zod/v4";

export const v1AccountLoginReqSchema = z.object({
    "account": z.string(),
"password": z.string(),
"device": z.string()
    }) as unknown as z.ZodType<V1AccountLoginReq>