/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountTopicListRes } from "../../types/v1/AccountTopicListRes";
import { v1TopicInfoSchema } from "./topicInfoSchema";
import { z } from "zod/v4";

export const v1AccountTopicListResSchema = z.object({
    "total": z.int(),
"page": z.int(),
"size": z.int(),
get "list"(){
                return z.array(v1TopicInfoSchema)
              }
    }) as unknown as z.ZodType<V1AccountTopicListRes>