/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatTokenLimitStatusReq } from "../../types/v1/ChatTokenLimitStatusReq";
import { z } from "zod/v4";

export const v1ChatTokenLimitStatusReqSchema = z.object({
    
    }) as unknown as z.ZodType<V1ChatTokenLimitStatusReq>