/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatCompletionsRes } from "../../types/v1/ChatCompletionsRes";
import { v1ChoicesInfoSchema } from "./choicesInfoSchema";
import { v1UsageInfoSchema } from "./usageInfoSchema";
import { z } from "zod/v4";

export const v1ChatCompletionsResSchema = z.object({
    "id": z.string(),
"object": z.string(),
"created": z.int(),
"model": z.string(),
"system_fingerprint": z.string(),
get "choices"(){
                return z.array(v1ChoicesInfoSchema)
              },
get "usage"(){
                return v1UsageInfoSchema
              }
    }) as unknown as z.ZodType<V1ChatCompletionsRes>