/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatImageLimitStatusReq } from "../../types/v1/ChatImageLimitStatusReq";
import { z } from "zod/v4";

export const v1ChatImageLimitStatusReqSchema = z.object({
    
    }) as unknown as z.ZodType<V1ChatImageLimitStatusReq>