/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatListReq } from "../../types/v1/ChatListReq";
import { z } from "zod/v4";

export const v1ChatListReqSchema = z.object({
    "session_id": z.string(),
"reference_id": z.optional(z.int()),
"page": z.int(),
"size": z.int()
    }) as unknown as z.ZodType<V1ChatListReq>