/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatStopRes } from "../../types/v1/ChatStopRes";
import { z } from "zod/v4";

export const v1ChatStopResSchema = z.object({
    
    }) as unknown as z.ZodType<V1ChatStopRes>