/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatSynchronizeTokenRes } from "../../types/v1/ChatSynchronizeTokenRes";
import { z } from "zod/v4";

export const v1ChatSynchronizeTokenResSchema = z.object({
    
    }) as unknown as z.ZodType<V1ChatSynchronizeTokenRes>