/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatSearchLimitStatusReq } from "../../types/v1/ChatSearchLimitStatusReq";
import { z } from "zod/v4";

export const v1ChatSearchLimitStatusReqSchema = z.object({
    
    }) as unknown as z.ZodType<V1ChatSearchLimitStatusReq>