/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChatTokenLimitStatusRes } from "../../types/v1/ChatTokenLimitStatusRes";
import { z } from "zod/v4";

export const v1ChatTokenLimitStatusResSchema = z.object({
    "status": z.boolean()
    }) as unknown as z.ZodType<V1ChatTokenLimitStatusRes>