/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChoicesInfo } from "../../types/v1/ChoicesInfo";
import { v1MessageInfoSchema } from "./messageInfoSchema";
import { z } from "zod/v4";

export const v1ChoicesInfoSchema = z.object({
    "index": z.int(),
get "message"(){
                return v1MessageInfoSchema
              },
"logprobs": z.string(),
"finish_reason": z.string()
    }) as unknown as z.ZodType<V1ChoicesInfo>