/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommonUploadReq } from "../../types/v1/CommonUploadReq";
import { z } from "zod/v4";

export const v1CommonUploadReqSchema = z.object({
    "files": z.array(z.instanceof(File))
    }) as unknown as z.ZodType<V1CommonUploadReq>