/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommentLikeUnLikeReq } from "../../types/v1/CommentLikeUnLikeReq";
import { z } from "zod/v4";

export const v1CommentLikeUnLikeReqSchema = z.object({
    "comment_id": z.int()
    }) as unknown as z.ZodType<V1CommentLikeUnLikeReq>