/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommonResetPasswordReq } from "../../types/v1/CommonResetPasswordReq";
import { z } from "zod/v4";

export const v1CommonResetPasswordReqSchema = z.object({
    "code": z.string(),
"user_list": z.array(z.string())
    }) as unknown as z.ZodType<V1CommonResetPasswordReq>