/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommonBatchAddUserRes } from "../../types/v1/CommonBatchAddUserRes";
import { z } from "zod/v4";

export const v1CommonBatchAddUserResSchema = z.object({
    
    }) as unknown as z.ZodType<V1CommonBatchAddUserRes>