/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommonUploadRes } from "../../types/v1/CommonUploadRes";
import { z } from "zod/v4";

export const v1CommonUploadResSchema = z.object({
    "filename": z.array(z.array(z.string()))
    }) as unknown as z.ZodType<V1CommonUploadRes>