/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommonSignStsRes } from "../../types/v1/CommonSignStsRes";
import { z } from "zod/v4";

export const v1CommonSignStsResSchema = z.object({
    "accessKeyId": z.string().describe("AccessKeyId"),
"accessKeySecret": z.string().describe("AccessKeySecret"),
"stsToken": z.string().describe("STS临时凭证"),
"expiration": z.string().describe("凭证过期时间"),
"bucket": z.string().describe("存储桶名称"),
"region": z.string().describe("地域"),
"secure": z.boolean().describe("是否使用HTTPS"),
"OSSRegionEndPoint": z.string().describe("存储服务的访问域名")
    }) as unknown as z.ZodType<V1CommonSignStsRes>