/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1DeviceInfo } from "../../types/v1/DeviceInfo";
import { z } from "zod/v4";

export const v1DeviceInfoSchema = z.object({
    "id": z.int(),
"device": z.string(),
"created_at": z.string()
    }) as unknown as z.ZodType<V1DeviceInfo>