/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1GuideReportRes } from "../../types/v1/GuideReportRes";
import { z } from "zod/v4";

export const v1GuideReportResSchema = z.object({
    
    }) as unknown as z.ZodType<V1GuideReportRes>