/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1GuideInfo } from "../../types/v1/GuideInfo";
import { z } from "zod/v4";

export const v1GuideInfoSchema = z.object({
    "step": z.int(),
"name": z.string(),
"content": z.string()
    }) as unknown as z.ZodType<V1GuideInfo>