/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1GuideReportReq } from "../../types/v1/GuideReportReq";
import { z } from "zod/v4";

export const v1GuideReportReqSchema = z.object({
    "step": z.int()
    }) as unknown as z.ZodType<V1GuideReportReq>