/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1MessageHistoryInfo } from "../../types/v1/MessageHistoryInfo";
import { v1MessageInfoSchema } from "./messageInfoSchema";
import { z } from "zod/v4";

export const v1MessageHistoryInfoSchema = z.object({
    "id": z.int(),
"index": z.int(),
get "message"(){
                return v1MessageInfoSchema
              },
"status": z.string(),
"model": z.string(),
"chat_time": z.string()
    }) as unknown as z.ZodType<V1MessageHistoryInfo>