/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ModelInfo } from "../../types/v1/ModelInfo";
import { z } from "zod/v4";

export const v1ModelInfoSchema = z.object({
    "platform_id": z.int(),
"platform": z.string(),
"model_id": z.int(),
"model": z.string(),
"platform_status": z.string(),
"platform_description": z.string(),
"series": z.string(),
"tag": z.string()
    }) as unknown as z.ZodType<V1ModelInfo>