/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ModelListRes } from "../../types/v1/ModelListRes";
import { v1ModelInfoSchema } from "./modelInfoSchema";
import { z } from "zod/v4";

export const v1ModelListResSchema = z.object({
    get "list"(){
                return z.array(v1ModelInfoSchema)
              }
    }) as unknown as z.ZodType<V1ModelListRes>