/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1NotificationListRes } from "../../types/v1/NotificationListRes";
import { v1NotificationInfoSchema } from "./notificationInfoSchema";
import { z } from "zod/v4";

export const v1NotificationListResSchema = z.object({
    "total": z.int(),
"page": z.int(),
"size": z.int(),
"unread_count": z.int(),
get "list"(){
                return z.array(v1NotificationInfoSchema)
              }
    }) as unknown as z.ZodType<V1NotificationListRes>