/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1NotificationMarkReadRes } from "../../types/v1/NotificationMarkReadRes";
import { z } from "zod/v4";

export const v1NotificationMarkReadResSchema = z.object({
    "read_count": z.int(),
"unread_count": z.int()
    }) as unknown as z.ZodType<V1NotificationMarkReadRes>