/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1NotificationMarkReadReq } from "../../types/v1/NotificationMarkReadReq";
import { z } from "zod/v4";

export const v1NotificationMarkReadReqSchema = z.object({
    "notification_id_list": z.array(z.int()),
"mark_all": z.boolean()
    }) as unknown as z.ZodType<V1NotificationMarkReadReq>