/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1OuterAccountExistRes } from "../../types/v1/OuterAccountExistRes";
import { z } from "zod/v4";

export const v1OuterAccountExistResSchema = z.object({
    "is_exist": z.boolean()
    }) as unknown as z.ZodType<V1OuterAccountExistRes>