/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1OuterExportReq } from "../../types/v1/OuterExportReq";
import { z } from "zod/v4";

export const v1OuterExportReqSchema = z.object({
    "code": z.string()
    }) as unknown as z.ZodType<V1OuterExportReq>