/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsFindPointTypeListReq } from "../../types/v1/PointsFindPointTypeListReq";
import { z } from "zod/v4";

export const v1PointsFindPointTypeListReqSchema = z.object({
    "type": z.optional(z.int()),
"value": z.optional(z.int()),
"remarks": z.optional(z.string())
    }) as unknown as z.ZodType<V1PointsFindPointTypeListReq>