/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsFindPointTypeListItem } from "../../types/v1/PointsFindPointTypeListItem";
import { z } from "zod/v4";

export const v1PointsFindPointTypeListItemSchema = z.object({
    "id": z.int(),
"type": z.int(),
"value": z.int(),
"remarks": z.string(),
"createdAt": z.string()
    }) as unknown as z.ZodType<V1PointsFindPointTypeListItem>