/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsFindAccountPointAndLevelReq } from "../../types/v1/PointsFindAccountPointAndLevelReq";
import { z } from "zod/v4";

export const v1PointsFindAccountPointAndLevelReqSchema = z.object({
    "accountId": z.optional(z.int())
    }) as unknown as z.ZodType<V1PointsFindAccountPointAndLevelReq>