/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsCreatePointTypeRes } from "../../types/v1/PointsCreatePointTypeRes";
import { z } from "zod/v4";

export const v1PointsCreatePointTypeResSchema = z.object({
    
    }) as unknown as z.ZodType<V1PointsCreatePointTypeRes>