/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsCreatePointDetailReq } from "../../types/v1/PointsCreatePointDetailReq";
import { z } from "zod/v4";

export const v1PointsCreatePointDetailReqSchema = z.object({
    "type": z.optional(z.int()),
"accountId": z.optional(z.int())
    }) as unknown as z.ZodType<V1PointsCreatePointDetailReq>