/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsFindLevelTypeListReq } from "../../types/v1/PointsFindLevelTypeListReq";
import { z } from "zod/v4";

export const v1PointsFindLevelTypeListReqSchema = z.object({
    
    }) as unknown as z.ZodType<V1PointsFindLevelTypeListReq>