/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ResultInfo } from "../../types/v1/ResultInfo";
import { z } from "zod/v4";

export const v1ResultInfoSchema = z.object({
    "title": z.string(),
"url": z.string(),
"content": z.string(),
"parsed_url": z.string(),
"engines": z.array(z.string()),
"score": z.number(),
"category": z.string(),
"published_date": z.string()
    }) as unknown as z.ZodType<V1ResultInfo>