/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionInfo } from "../../types/v1/SessionInfo";
import { z } from "zod/v4";

export const v1SessionInfoSchema = z.object({
    "session_id": z.string(),
"name": z.string(),
"created_at": z.string(),
"last_chat_time": z.string()
    }) as unknown as z.ZodType<V1SessionInfo>