/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionListReq } from "../../types/v1/SessionListReq";
import { z } from "zod/v4";

export const v1SessionListReqSchema = z.object({
    "page": z.int(),
"size": z.int()
    }) as unknown as z.ZodType<V1SessionListReq>