/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionListRes } from "../../types/v1/SessionListRes";
import { v1SessionInfoSchema } from "./sessionInfoSchema";
import { z } from "zod/v4";

export const v1SessionListResSchema = z.object({
    "total": z.int(),
"page": z.int(),
"size": z.int(),
get "list"(){
                return z.array(v1SessionInfoSchema)
              }
    }) as unknown as z.ZodType<V1SessionListRes>