/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionRenameReq } from "../../types/v1/SessionRenameReq";
import { z } from "zod/v4";

export const v1SessionRenameReqSchema = z.object({
    "session_id": z.string(),
"name": z.string()
    }) as unknown as z.ZodType<V1SessionRenameReq>