/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionCreateRes } from "../../types/v1/SessionCreateRes";
import { z } from "zod/v4";

export const v1SessionCreateResSchema = z.object({
    "session_id": z.string()
    }) as unknown as z.ZodType<V1SessionCreateRes>