/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionCreateReq } from "../../types/v1/SessionCreateReq";
import { z } from "zod/v4";

export const v1SessionCreateReqSchema = z.object({
    "name": z.optional(z.string())
    }) as unknown as z.ZodType<V1SessionCreateReq>