/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1Stats } from "../../types/v1/Stats";
import { z } from "zod/v4";

export const v1StatsSchema = z.object({
    "topic_count": z.int(),
"replay_count": z.int(),
"like_count": z.int()
    }) as unknown as z.ZodType<V1Stats>