/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskTopicDetailReq } from "../../types/v1/TaskTopicDetailReq";
import { z } from "zod/v4";

export const v1TaskTopicDetailReqSchema = z.object({
    "id": z.int()
    }) as unknown as z.ZodType<V1TaskTopicDetailReq>