/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskListReq } from "../../types/v1/TaskListReq";
import { z } from "zod/v4";

export const v1TaskListReqSchema = z.object({
    
    }) as unknown as z.ZodType<V1TaskListReq>