/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskTopicExtra } from "../../types/v1/TaskTopicExtra";
import { z } from "zod/v4";

export const v1TaskTopicExtraSchema = z.object({
    "like_count": z.int(),
"comment_count": z.int()
    }) as unknown as z.ZodType<V1TaskTopicExtra>