/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskUserCompleteCheckReq } from "../../types/v1/TaskUserCompleteCheckReq";
import { z } from "zod/v4";

export const v1TaskUserCompleteCheckReqSchema = z.object({
    "task_index_list": z.array(z.int())
    }) as unknown as z.ZodType<V1TaskUserCompleteCheckReq>