/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskTopicListRes } from "../../types/v1/TaskTopicListRes";
import { v1TaskTopicInfoSchema } from "./taskTopicInfoSchema";
import { z } from "zod/v4";

export const v1TaskTopicListResSchema = z.object({
    "total": z.int(),
"page": z.int(),
"size": z.int(),
get "list"(){
                return z.array(v1TaskTopicInfoSchema)
              }
    }) as unknown as z.ZodType<V1TaskTopicListRes>