/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskTopicDeleteRes } from "../../types/v1/TaskTopicDeleteRes";
import { z } from "zod/v4";

export const v1TaskTopicDeleteResSchema = z.object({
    
    }) as unknown as z.ZodType<V1TaskTopicDeleteRes>