/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TopicLikeLikeReq } from "../../types/v1/TopicLikeLikeReq";
import { z } from "zod/v4";

export const v1TopicLikeLikeReqSchema = z.object({
    "topic_id": z.int()
    }) as unknown as z.ZodType<V1TopicLikeLikeReq>