/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TopicCommentSubInfo } from "../../types/v1/TopicCommentSubInfo";
import { v1CommentExtraAccountSchema } from "./commentExtraAccountSchema";
import { v1CommentExtraSchema } from "./commentExtraSchema";
import { z } from "zod/v4";

export const v1TopicCommentSubInfoSchema = z.object({
    "id": z.int(),
"task_id": z.int(),
"task_title": z.string(),
"topic_id": z.int(),
"root_comment_id": z.int(),
"comment_id": z.int(),
"account_id": z.int(),
"content": z.string(),
"material": z.string(),
"created_at": z.string(),
"account": z.string(),
"nickname": z.string(),
get "extra"(){
                return v1CommentExtraSchema
              },
get "extra_account"(){
                return v1CommentExtraAccountSchema
              },
"avatar": z.string()
    }) as unknown as z.ZodType<V1TopicCommentSubInfo>