/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TopicCommentListRes } from "../../types/v1/TopicCommentListRes";
import { v1TopicCommentInfoSchema } from "./topicCommentInfoSchema";
import { z } from "zod/v4";

export const v1TopicCommentListResSchema = z.object({
    "total": z.int(),
"page": z.int(),
"size": z.int(),
get "list"(){
                return z.array(v1TopicCommentInfoSchema)
              }
    }) as unknown as z.ZodType<V1TopicCommentListRes>