/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TopicCommentAddReq } from "../../types/v1/TopicCommentAddReq";
import { z } from "zod/v4";

export const v1TopicCommentAddReqSchema = z.object({
    "topic_id": z.int(),
"root_comment_id": z.int(),
"comment_id": z.int(),
"content": z.string(),
"material": z.optional(z.string())
    }) as unknown as z.ZodType<V1TopicCommentAddReq>