/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TopicCommentSubListReq } from "../../types/v1/TopicCommentSubListReq";
import { z } from "zod/v4";

export const v1TopicCommentSubListReqSchema = z.object({
    "topic_id": z.int(),
"root_comment_id": z.int(),
"page": z.int(),
"size": z.int()
    }) as unknown as z.ZodType<V1TopicCommentSubListReq>