/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TrainInfo } from "../../types/v1/TrainInfo";
import { z } from "zod/v4";

export const v1TrainInfoSchema = z.object({
    "id": z.int(),
"train_name": z.string(),
"account_id": z.int(),
"train_attribute_epochs": z.int(),
"train_attribute_batch_size": z.int(),
"train_attribute_learning_rate": z.number(),
"train_type": z.enum(["audio", "image", "pose"]),
"train_status": z.string(),
"train_model": z.string(),
"bin_path": z.string(),
"json_path": z.string(),
"file_dir": z.string(),
"train_structure": z.string(),
"k-value": z.int(),
"filter_coefficients": z.number(),
"distance_threshold": z.number()
    }) as unknown as z.ZodType<V1TrainInfo>