/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TrainResultRes } from "../../types/v1/TrainResultRes";
import { z } from "zod/v4";

export const v1TrainResultResSchema = z.object({
    "train_status": z.string(),
"result_status": z.string(),
"train_model": z.string()
    }) as unknown as z.ZodType<V1TrainResultRes>