/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TrainListRes } from "../../types/v1/TrainListRes";
import { v1TrainInfoSchema } from "./trainInfoSchema";
import { z } from "zod/v4";

export const v1TrainListResSchema = z.object({
    get "list"(){
                return z.array(v1TrainInfoSchema)
              }
    }) as unknown as z.ZodType<V1TrainListRes>