/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TrainDetailReq } from "../../types/v1/TrainDetailReq";
import { z } from "zod/v4";

export const v1TrainDetailReqSchema = z.object({
    "train_id": z.int()
    }) as unknown as z.ZodType<V1TrainDetailReq>