/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TrainCreateReq } from "../../types/v1/TrainCreateReq";
import { z } from "zod/v4";

export const v1TrainCreateReqSchema = z.object({
    "train_type": z.string()
    }) as unknown as z.ZodType<V1TrainCreateReq>