/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { GuideListMutationRequest, GuideListMutationResponse } from "../../types/guideTypes/GuideList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const guideListSuspenseQueryKey = (data?: GuideListMutationRequest) => [{ url: '/api/guide/list' }, ...(data ? [data] : [])] as const

export type GuideListSuspenseQueryKey = ReturnType<typeof guideListSuspenseQueryKey>

/**
 * @summary 列表
 * {@link /api/guide/list}
 */
export async function guideListSuspense(data?: GuideListMutationRequest, config: Partial<RequestConfig<GuideListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<GuideListMutationResponse, ResponseErrorConfig<Error>, GuideListMutationRequest>({ method : "POST", url : `/api/guide/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function guideListSuspenseQueryOptions(data?: GuideListMutationRequest, config: Partial<RequestConfig<GuideListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = guideListSuspenseQueryKey(data)
  return queryOptions<GuideListMutationResponse, ResponseErrorConfig<Error>, GuideListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return guideListSuspense(data, config)
   },
  })
}

/**
 * @summary 列表
 * {@link /api/guide/list}
 */
export function useGuideListSuspense<TData = GuideListMutationResponse, TQueryKey extends QueryKey = GuideListSuspenseQueryKey>(data?: GuideListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GuideListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GuideListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? guideListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...guideListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}