/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { GuideReportMutationRequest, GuideReportMutationResponse } from "../../types/guideTypes/GuideReport";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const guideReportSuspenseQueryKey = (data: GuideReportMutationRequest) => [{ url: '/api/guide/report' }, ...(data ? [data] : [])] as const

export type GuideReportSuspenseQueryKey = ReturnType<typeof guideReportSuspenseQueryKey>

/**
 * @summary 更新状态
 * {@link /api/guide/report}
 */
export async function guideReportSuspense(data: GuideReportMutationRequest, config: Partial<RequestConfig<GuideReportMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<GuideReportMutationResponse, ResponseErrorConfig<Error>, GuideReportMutationRequest>({ method : "POST", url : `/api/guide/report`, data : requestData, ... requestConfig })  
  return res.data
}

export function guideReportSuspenseQueryOptions(data: GuideReportMutationRequest, config: Partial<RequestConfig<GuideReportMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = guideReportSuspenseQueryKey(data)
  return queryOptions<GuideReportMutationResponse, ResponseErrorConfig<Error>, GuideReportMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return guideReportSuspense(data, config)
   },
  })
}

/**
 * @summary 更新状态
 * {@link /api/guide/report}
 */
export function useGuideReportSuspense<TData = GuideReportMutationResponse, TQueryKey extends QueryKey = GuideReportSuspenseQueryKey>(data: GuideReportMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GuideReportMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GuideReportMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? guideReportSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...guideReportSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}