/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { GuideListMutationRequest, GuideListMutationResponse } from "../../types/guideTypes/GuideList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const guideListQueryKey = (data?: GuideListMutationRequest) => [{ url: '/api/guide/list' }, ...(data ? [data] : [])] as const

export type GuideListQueryKey = ReturnType<typeof guideListQueryKey>

/**
 * @summary 列表
 * {@link /api/guide/list}
 */
export async function guideList(data?: GuideListMutationRequest, config: Partial<RequestConfig<GuideListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<GuideListMutationResponse, ResponseErrorConfig<Error>, GuideListMutationRequest>({ method : "POST", url : `/api/guide/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function guideListQueryOptions(data?: GuideListMutationRequest, config: Partial<RequestConfig<GuideListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = guideListQueryKey(data)
  return queryOptions<GuideListMutationResponse, ResponseErrorConfig<Error>, GuideListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return guideList(data, config)
   },
  })
}

/**
 * @summary 列表
 * {@link /api/guide/list}
 */
export function useGuideList<TData = GuideListMutationResponse, TQueryData = GuideListMutationResponse, TQueryKey extends QueryKey = GuideListQueryKey>(data?: GuideListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<GuideListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<GuideListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? guideListQueryKey(data)

  const query = useQuery({
   ...guideListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}