/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskUserDoneMutationRequest, TaskUserDoneMutationResponse } from "../../types/task_userTypes/TaskUserDone";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskUserDoneSuspenseQueryKey = (data: TaskUserDoneMutationRequest) => [{ url: '/api/task_user/done' }, ...(data ? [data] : [])] as const

export type TaskUserDoneSuspenseQueryKey = ReturnType<typeof taskUserDoneSuspenseQueryKey>

/**
 * @summary 将任务设置为完成状态
 * {@link /api/task_user/done}
 */
export async function taskUserDoneSuspense(data: TaskUserDoneMutationRequest, config: Partial<RequestConfig<TaskUserDoneMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskUserDoneMutationResponse, ResponseErrorConfig<Error>, TaskUserDoneMutationRequest>({ method : "POST", url : `/api/task_user/done`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskUserDoneSuspenseQueryOptions(data: TaskUserDoneMutationRequest, config: Partial<RequestConfig<TaskUserDoneMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskUserDoneSuspenseQueryKey(data)
  return queryOptions<TaskUserDoneMutationResponse, ResponseErrorConfig<Error>, TaskUserDoneMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskUserDoneSuspense(data, config)
   },
  })
}

/**
 * @summary 将任务设置为完成状态
 * {@link /api/task_user/done}
 */
export function useTaskUserDoneSuspense<TData = TaskUserDoneMutationResponse, TQueryKey extends QueryKey = TaskUserDoneSuspenseQueryKey>(data: TaskUserDoneMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskUserDoneMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskUserDoneMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskUserDoneSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskUserDoneSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}