/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskUserUndoneMutationRequest, TaskUserUndoneMutationResponse } from "../../types/task_userTypes/TaskUserUndone";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskUserUndoneSuspenseQueryKey = (data?: TaskUserUndoneMutationRequest) => [{ url: '/api/task_user/undone' }, ...(data ? [data] : [])] as const

export type TaskUserUndoneSuspenseQueryKey = ReturnType<typeof taskUserUndoneSuspenseQueryKey>

/**
 * @summary 未做的任务
 * {@link /api/task_user/undone}
 */
export async function taskUserUndoneSuspense(data?: TaskUserUndoneMutationRequest, config: Partial<RequestConfig<TaskUserUndoneMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskUserUndoneMutationResponse, ResponseErrorConfig<Error>, TaskUserUndoneMutationRequest>({ method : "POST", url : `/api/task_user/undone`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskUserUndoneSuspenseQueryOptions(data?: TaskUserUndoneMutationRequest, config: Partial<RequestConfig<TaskUserUndoneMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskUserUndoneSuspenseQueryKey(data)
  return queryOptions<TaskUserUndoneMutationResponse, ResponseErrorConfig<Error>, TaskUserUndoneMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskUserUndoneSuspense(data, config)
   },
  })
}

/**
 * @summary 未做的任务
 * {@link /api/task_user/undone}
 */
export function useTaskUserUndoneSuspense<TData = TaskUserUndoneMutationResponse, TQueryKey extends QueryKey = TaskUserUndoneSuspenseQueryKey>(data?: TaskUserUndoneMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskUserUndoneMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskUserUndoneMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskUserUndoneSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskUserUndoneSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}