/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskUserListMutationRequest, TaskUserListMutationResponse } from "../../types/task_userTypes/TaskUserList";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskUserListQueryKey = (data?: TaskUserListMutationRequest) => [{ url: '/api/task_user/list' }, ...(data ? [data] : [])] as const

export type TaskUserListQueryKey = ReturnType<typeof taskUserListQueryKey>

/**
 * @summary 我的任务列表
 * {@link /api/task_user/list}
 */
export async function taskUserList(data?: TaskUserListMutationRequest, config: Partial<RequestConfig<TaskUserListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskUserListMutationResponse, ResponseErrorConfig<Error>, TaskUserListMutationRequest>({ method : "POST", url : `/api/task_user/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskUserListQueryOptions(data?: TaskUserListMutationRequest, config: Partial<RequestConfig<TaskUserListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskUserListQueryKey(data)
  return queryOptions<TaskUserListMutationResponse, ResponseErrorConfig<Error>, TaskUserListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskUserList(data, config)
   },
  })
}

/**
 * @summary 我的任务列表
 * {@link /api/task_user/list}
 */
export function useTaskUserList<TData = TaskUserListMutationResponse, TQueryData = TaskUserListMutationResponse, TQueryKey extends QueryKey = TaskUserListQueryKey>(data?: TaskUserListMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskUserListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskUserListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskUserListQueryKey(data)

  const query = useQuery({
   ...taskUserListQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}