/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskUserCompleteCheckMutationRequest, TaskUserCompleteCheckMutationResponse } from "../../types/task_userTypes/TaskUserCompleteCheck";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskUserCompleteCheckSuspenseQueryKey = (data: TaskUserCompleteCheckMutationRequest) => [{ url: '/api/task_user/complete_check' }, ...(data ? [data] : [])] as const

export type TaskUserCompleteCheckSuspenseQueryKey = ReturnType<typeof taskUserCompleteCheckSuspenseQueryKey>

/**
 * @summary 任务完成检查
 * {@link /api/task_user/complete_check}
 */
export async function taskUserCompleteCheckSuspense(data: TaskUserCompleteCheckMutationRequest, config: Partial<RequestConfig<TaskUserCompleteCheckMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskUserCompleteCheckMutationResponse, ResponseErrorConfig<Error>, TaskUserCompleteCheckMutationRequest>({ method : "POST", url : `/api/task_user/complete_check`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskUserCompleteCheckSuspenseQueryOptions(data: TaskUserCompleteCheckMutationRequest, config: Partial<RequestConfig<TaskUserCompleteCheckMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskUserCompleteCheckSuspenseQueryKey(data)
  return queryOptions<TaskUserCompleteCheckMutationResponse, ResponseErrorConfig<Error>, TaskUserCompleteCheckMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskUserCompleteCheckSuspense(data, config)
   },
  })
}

/**
 * @summary 任务完成检查
 * {@link /api/task_user/complete_check}
 */
export function useTaskUserCompleteCheckSuspense<TData = TaskUserCompleteCheckMutationResponse, TQueryKey extends QueryKey = TaskUserCompleteCheckSuspenseQueryKey>(data: TaskUserCompleteCheckMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskUserCompleteCheckMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskUserCompleteCheckMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskUserCompleteCheckSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskUserCompleteCheckSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}