/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskUserDoneMutationRequest, TaskUserDoneMutationResponse } from "../../types/task_userTypes/TaskUserDone";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskUserDoneQueryKey = (data: TaskUserDoneMutationRequest) => [{ url: '/api/task_user/done' }, ...(data ? [data] : [])] as const

export type TaskUserDoneQueryKey = ReturnType<typeof taskUserDoneQueryKey>

/**
 * @summary 将任务设置为完成状态
 * {@link /api/task_user/done}
 */
export async function taskUserDone(data: TaskUserDoneMutationRequest, config: Partial<RequestConfig<TaskUserDoneMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskUserDoneMutationResponse, ResponseErrorConfig<Error>, TaskUserDoneMutationRequest>({ method : "POST", url : `/api/task_user/done`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskUserDoneQueryOptions(data: TaskUserDoneMutationRequest, config: Partial<RequestConfig<TaskUserDoneMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskUserDoneQueryKey(data)
  return queryOptions<TaskUserDoneMutationResponse, ResponseErrorConfig<Error>, TaskUserDoneMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskUserDone(data, config)
   },
  })
}

/**
 * @summary 将任务设置为完成状态
 * {@link /api/task_user/done}
 */
export function useTaskUserDone<TData = TaskUserDoneMutationResponse, TQueryData = TaskUserDoneMutationResponse, TQueryKey extends QueryKey = TaskUserDoneQueryKey>(data: TaskUserDoneMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskUserDoneMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskUserDoneMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskUserDoneQueryKey(data)

  const query = useQuery({
   ...taskUserDoneQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}