/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskUserCompleteCheckMutationRequest, TaskUserCompleteCheckMutationResponse } from "../../types/task_userTypes/TaskUserCompleteCheck";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskUserCompleteCheckQueryKey = (data: TaskUserCompleteCheckMutationRequest) => [{ url: '/api/task_user/complete_check' }, ...(data ? [data] : [])] as const

export type TaskUserCompleteCheckQueryKey = ReturnType<typeof taskUserCompleteCheckQueryKey>

/**
 * @summary 任务完成检查
 * {@link /api/task_user/complete_check}
 */
export async function taskUserCompleteCheck(data: TaskUserCompleteCheckMutationRequest, config: Partial<RequestConfig<TaskUserCompleteCheckMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskUserCompleteCheckMutationResponse, ResponseErrorConfig<Error>, TaskUserCompleteCheckMutationRequest>({ method : "POST", url : `/api/task_user/complete_check`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskUserCompleteCheckQueryOptions(data: TaskUserCompleteCheckMutationRequest, config: Partial<RequestConfig<TaskUserCompleteCheckMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskUserCompleteCheckQueryKey(data)
  return queryOptions<TaskUserCompleteCheckMutationResponse, ResponseErrorConfig<Error>, TaskUserCompleteCheckMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskUserCompleteCheck(data, config)
   },
  })
}

/**
 * @summary 任务完成检查
 * {@link /api/task_user/complete_check}
 */
export function useTaskUserCompleteCheck<TData = TaskUserCompleteCheckMutationResponse, TQueryData = TaskUserCompleteCheckMutationResponse, TQueryKey extends QueryKey = TaskUserCompleteCheckQueryKey>(data: TaskUserCompleteCheckMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TaskUserCompleteCheckMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskUserCompleteCheckMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskUserCompleteCheckQueryKey(data)

  const query = useQuery({
   ...taskUserCompleteCheckQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}