/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TaskUserListMutationRequest, TaskUserListMutationResponse } from "../../types/task_userTypes/TaskUserList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskUserListSuspenseQueryKey = (data?: TaskUserListMutationRequest) => [{ url: '/api/task_user/list' }, ...(data ? [data] : [])] as const

export type TaskUserListSuspenseQueryKey = ReturnType<typeof taskUserListSuspenseQueryKey>

/**
 * @summary 我的任务列表
 * {@link /api/task_user/list}
 */
export async function taskUserListSuspense(data?: TaskUserListMutationRequest, config: Partial<RequestConfig<TaskUserListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskUserListMutationResponse, ResponseErrorConfig<Error>, TaskUserListMutationRequest>({ method : "POST", url : `/api/task_user/list`, data : requestData, ... requestConfig })  
  return res.data
}

export function taskUserListSuspenseQueryOptions(data?: TaskUserListMutationRequest, config: Partial<RequestConfig<TaskUserListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = taskUserListSuspenseQueryKey(data)
  return queryOptions<TaskUserListMutationResponse, ResponseErrorConfig<Error>, TaskUserListMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskUserListSuspense(data, config)
   },
  })
}

/**
 * @summary 我的任务列表
 * {@link /api/task_user/list}
 */
export function useTaskUserListSuspense<TData = TaskUserListMutationResponse, TQueryKey extends QueryKey = TaskUserListSuspenseQueryKey>(data?: TaskUserListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskUserListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskUserListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskUserListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...taskUserListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}