/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { OuterExport200, OuterExportMutationRequest, OuterExportMutationResponse } from "../../types/outerTypes/OuterExport";
import { v1OuterExportReqSchema } from "../v1/outerExportReqSchema";
import { v1OuterExportResSchema } from "../v1/outerExportResSchema";
import { z } from "zod/v4";

export const outerExport200Schema = v1OuterExportResSchema as unknown as z.ZodType<OuterExport200>

export const outerExportMutationRequestSchema = v1OuterExportReqSchema as unknown as z.ZodType<OuterExportMutationRequest>

export const outerExportMutationResponseSchema = outerExport200Schema as unknown as z.ZodType<OuterExportMutationResponse>