/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TopicCommentSubListMutationRequest, TopicCommentSubListMutationResponse } from "../../types/topic_commentTypes/TopicCommentSubList";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const topicCommentSubListSuspenseQueryKey = (data: TopicCommentSubListMutationRequest) => [{ url: '/api/topic_comment/sub_list' }, ...(data ? [data] : [])] as const

export type TopicCommentSubListSuspenseQueryKey = ReturnType<typeof topicCommentSubListSuspenseQueryKey>

/**
 * @summary 主题子评论列表
 * {@link /api/topic_comment/sub_list}
 */
export async function topicCommentSubListSuspense(data: TopicCommentSubListMutationRequest, config: Partial<RequestConfig<TopicCommentSubListMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TopicCommentSubListMutationResponse, ResponseErrorConfig<Error>, TopicCommentSubListMutationRequest>({ method : "POST", url : `/api/topic_comment/sub_list`, data : requestData, ... requestConfig })  
  return res.data
}

export function topicCommentSubListSuspenseQueryOptions(data: TopicCommentSubListMutationRequest, config: Partial<RequestConfig<TopicCommentSubListMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = topicCommentSubListSuspenseQueryKey(data)
  return queryOptions<TopicCommentSubListMutationResponse, ResponseErrorConfig<Error>, TopicCommentSubListMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return topicCommentSubListSuspense(data, config)
   },
  })
}

/**
 * @summary 主题子评论列表
 * {@link /api/topic_comment/sub_list}
 */
export function useTopicCommentSubListSuspense<TData = TopicCommentSubListMutationResponse, TQueryKey extends QueryKey = TopicCommentSubListSuspenseQueryKey>(data: TopicCommentSubListMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TopicCommentSubListMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TopicCommentSubListMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? topicCommentSubListSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...topicCommentSubListSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}