/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TopicCommentAddMutationRequest, TopicCommentAddMutationResponse } from "../../types/topic_commentTypes/TopicCommentAdd";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const topicCommentAddSuspenseQueryKey = (data: TopicCommentAddMutationRequest) => [{ url: '/api/topic_comment/add' }, ...(data ? [data] : [])] as const

export type TopicCommentAddSuspenseQueryKey = ReturnType<typeof topicCommentAddSuspenseQueryKey>

/**
 * @summary 发布主题评论
 * {@link /api/topic_comment/add}
 */
export async function topicCommentAddSuspense(data: TopicCommentAddMutationRequest, config: Partial<RequestConfig<TopicCommentAddMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TopicCommentAddMutationResponse, ResponseErrorConfig<Error>, TopicCommentAddMutationRequest>({ method : "POST", url : `/api/topic_comment/add`, data : requestData, ... requestConfig })  
  return res.data
}

export function topicCommentAddSuspenseQueryOptions(data: TopicCommentAddMutationRequest, config: Partial<RequestConfig<TopicCommentAddMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = topicCommentAddSuspenseQueryKey(data)
  return queryOptions<TopicCommentAddMutationResponse, ResponseErrorConfig<Error>, TopicCommentAddMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return topicCommentAddSuspense(data, config)
   },
  })
}

/**
 * @summary 发布主题评论
 * {@link /api/topic_comment/add}
 */
export function useTopicCommentAddSuspense<TData = TopicCommentAddMutationResponse, TQueryKey extends QueryKey = TopicCommentAddSuspenseQueryKey>(data: TopicCommentAddMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<TopicCommentAddMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TopicCommentAddMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? topicCommentAddSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...topicCommentAddSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}