/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { TopicCommentAddMutationRequest, TopicCommentAddMutationResponse } from "../../types/topic_commentTypes/TopicCommentAdd";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const topicCommentAddQueryKey = (data: TopicCommentAddMutationRequest) => [{ url: '/api/topic_comment/add' }, ...(data ? [data] : [])] as const

export type TopicCommentAddQueryKey = ReturnType<typeof topicCommentAddQueryKey>

/**
 * @summary 发布主题评论
 * {@link /api/topic_comment/add}
 */
export async function topicCommentAdd(data: TopicCommentAddMutationRequest, config: Partial<RequestConfig<TopicCommentAddMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TopicCommentAddMutationResponse, ResponseErrorConfig<Error>, TopicCommentAddMutationRequest>({ method : "POST", url : `/api/topic_comment/add`, data : requestData, ... requestConfig })  
  return res.data
}

export function topicCommentAddQueryOptions(data: TopicCommentAddMutationRequest, config: Partial<RequestConfig<TopicCommentAddMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = topicCommentAddQueryKey(data)
  return queryOptions<TopicCommentAddMutationResponse, ResponseErrorConfig<Error>, TopicCommentAddMutationResponse, typeof queryKey>({
   enabled: !!(data),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return topicCommentAdd(data, config)
   },
  })
}

/**
 * @summary 发布主题评论
 * {@link /api/topic_comment/add}
 */
export function useTopicCommentAdd<TData = TopicCommentAddMutationResponse, TQueryData = TopicCommentAddMutationResponse, TQueryKey extends QueryKey = TopicCommentAddQueryKey>(data: TopicCommentAddMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<TopicCommentAddMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<TopicCommentAddMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? topicCommentAddQueryKey(data)

  const query = useQuery({
   ...topicCommentAddQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}