/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountProfileReq } from "../v1/AccountProfileReq";
import type { V1AccountProfileRes } from "../v1/AccountProfileRes";

export type AccountProfile200 = V1AccountProfileRes;

export type AccountProfileMutationRequest = V1AccountProfileReq;

export type AccountProfileMutationResponse = AccountProfile200;

export type AccountProfileMutation = {
    Response: AccountProfile200;
    Request: AccountProfileMutationRequest;
    Errors: any;
};