/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountGetPermissionsRes } from "../v1/AccountGetPermissionsRes";

export type AccountGetPermissions200 = V1AccountGetPermissionsRes;

export type AccountGetPermissionsQueryResponse = AccountGetPermissions200;

export type AccountGetPermissionsQuery = {
    Response: AccountGetPermissions200;
    Errors: any;
};