/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountLoginReq } from "../v1/AccountLoginReq";
import type { V1AccountLoginRes } from "../v1/AccountLoginRes";

export type AccountLogin200 = V1AccountLoginRes;

export type AccountLoginMutationRequest = V1AccountLoginReq;

export type AccountLoginMutationResponse = AccountLogin200;

export type AccountLoginMutation = {
    Response: AccountLogin200;
    Request: AccountLoginMutationRequest;
    Errors: any;
};