/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountInfoRes } from "../v1/AccountInfoRes";

export type AccountInfo200 = V1AccountInfoRes;

export type AccountInfoQueryResponse = AccountInfo200;

export type AccountInfoQuery = {
    Response: AccountInfo200;
    Errors: any;
};