/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { UserPurchaseDetailMutationRequest, UserPurchaseDetailMutationResponse } from "../../types/user_purchaseTypes/UserPurchaseDetail";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const userPurchaseDetailSuspenseQueryKey = (data?: UserPurchaseDetailMutationRequest) => [{ url: '/api/user_purchase/detail' }, ...(data ? [data] : [])] as const

export type UserPurchaseDetailSuspenseQueryKey = ReturnType<typeof userPurchaseDetailSuspenseQueryKey>

/**
 * @summary 获取用户购买详情
 * {@link /api/user_purchase/detail}
 */
export async function userPurchaseDetailSuspense(data?: UserPurchaseDetailMutationRequest, config: Partial<RequestConfig<UserPurchaseDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UserPurchaseDetailMutationResponse, ResponseErrorConfig<Error>, UserPurchaseDetailMutationRequest>({ method : "POST", url : `/api/user_purchase/detail`, data : requestData, ... requestConfig })  
  return res.data
}

export function userPurchaseDetailSuspenseQueryOptions(data?: UserPurchaseDetailMutationRequest, config: Partial<RequestConfig<UserPurchaseDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = userPurchaseDetailSuspenseQueryKey(data)
  return queryOptions<UserPurchaseDetailMutationResponse, ResponseErrorConfig<Error>, UserPurchaseDetailMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return userPurchaseDetailSuspense(data, config)
   },
  })
}

/**
 * @summary 获取用户购买详情
 * {@link /api/user_purchase/detail}
 */
export function useUserPurchaseDetailSuspense<TData = UserPurchaseDetailMutationResponse, TQueryKey extends QueryKey = UserPurchaseDetailSuspenseQueryKey>(data?: UserPurchaseDetailMutationRequest, options: 
{
  query?: Partial<UseSuspenseQueryOptions<UserPurchaseDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<UserPurchaseDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? userPurchaseDetailSuspenseQueryKey(data)

  const query = useSuspenseQuery({
   ...userPurchaseDetailSuspenseQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}