/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../.kubb/fetcher";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/fetcher";
import type { UserPurchaseDetailMutationRequest, UserPurchaseDetailMutationResponse } from "../../types/user_purchaseTypes/UserPurchaseDetail";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const userPurchaseDetailQueryKey = (data?: UserPurchaseDetailMutationRequest) => [{ url: '/api/user_purchase/detail' }, ...(data ? [data] : [])] as const

export type UserPurchaseDetailQueryKey = ReturnType<typeof userPurchaseDetailQueryKey>

/**
 * @summary 获取用户购买详情
 * {@link /api/user_purchase/detail}
 */
export async function userPurchaseDetail(data?: UserPurchaseDetailMutationRequest, config: Partial<RequestConfig<UserPurchaseDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UserPurchaseDetailMutationResponse, ResponseErrorConfig<Error>, UserPurchaseDetailMutationRequest>({ method : "POST", url : `/api/user_purchase/detail`, data : requestData, ... requestConfig })  
  return res.data
}

export function userPurchaseDetailQueryOptions(data?: UserPurchaseDetailMutationRequest, config: Partial<RequestConfig<UserPurchaseDetailMutationRequest>> & { client?: typeof fetch } = {}) {
  const queryKey = userPurchaseDetailQueryKey(data)
  return queryOptions<UserPurchaseDetailMutationResponse, ResponseErrorConfig<Error>, UserPurchaseDetailMutationResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return userPurchaseDetail(data, config)
   },
  })
}

/**
 * @summary 获取用户购买详情
 * {@link /api/user_purchase/detail}
 */
export function useUserPurchaseDetail<TData = UserPurchaseDetailMutationResponse, TQueryData = UserPurchaseDetailMutationResponse, TQueryKey extends QueryKey = UserPurchaseDetailQueryKey>(data?: UserPurchaseDetailMutationRequest, options: 
{
  query?: Partial<QueryObserverOptions<UserPurchaseDetailMutationResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig<UserPurchaseDetailMutationRequest>> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? userPurchaseDetailQueryKey(data)

  const query = useQuery({
   ...userPurchaseDetailQueryOptions(data, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}