/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1DeviceInfo } from "./DeviceInfo";

export type V1AccountDeviceListRes = {
    /**
     * @type array, []*v1.DeviceInfo
    */
    list: V1DeviceInfo[];
};