/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1AccountInfo = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type string, string
    */
    nickname: string;
    /**
     * @type string, string
    */
    avatar: string;
};