/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1AccountChangePasswordReq = {
    /**
     * @type string, string
    */
    old_password: string;
    /**
     * @type string, string
    */
    new_password: string;
};