/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1AccountTopicListReq = {
    /**
     * @type string | undefined, consts.TopicStatus
    */
    status?: string | undefined;
    /**
     * @type integer, int
    */
    page: number;
    /**
     * @type integer, int
    */
    size: number;
};