/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1Stats } from "./Stats";

export type V1AccountProfileRes = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type string, string
    */
    account: string;
    /**
     * @type string, string
    */
    nickname: string;
    /**
     * @type string, string
    */
    avatar: string;
    /**
     * @type string, string
    */
    register_time: string;
    /**
     * @type string, string
    */
    last_login_time: string;
    /**
     * @type object
    */
    stats: V1Stats;
    /**
     * @type boolean, bool
    */
    change_password: boolean;
    /**
     * @type string, string
    */
    tag: string;
};