/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1AccountAvatarRes = {
    /**
     * @type string, string
    */
    avatar: string;
};