/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ChoicesInfo } from "./ChoicesInfo";
import type { V1UsageInfo } from "./UsageInfo";

export type V1ChatCompletionsRes = {
    /**
     * @type string, string
    */
    id: string;
    /**
     * @type string, string
    */
    object: string;
    /**
     * @type integer, int64
    */
    created: number;
    /**
     * @type string, string
    */
    model: string;
    /**
     * @type string, string
    */
    system_fingerprint: string;
    /**
     * @type array, []*v1.ChoicesInfo
    */
    choices: V1ChoicesInfo[];
    /**
     * @type object
    */
    usage: V1UsageInfo;
};