/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1Usage } from "./Usage";

export type V1ChatSynchronizeTokenReq = {
    /**
     * @type string | undefined, string
    */
    model?: string | undefined;
    /**
     * @type array, []*v1.Usage
    */
    usage: V1Usage[];
};