/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1MessageHistoryInfo } from "./MessageHistoryInfo";

export type V1ChatListRes = {
    /**
     * @type integer, int
    */
    total: number;
    /**
     * @type integer, int
    */
    page: number;
    /**
     * @type integer, int
    */
    size: number;
    /**
     * @type integer, int64
    */
    reference_id: number;
    /**
     * @type array, []*v1.MessageHistoryInfo
    */
    list: V1MessageHistoryInfo[];
};