/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1MessageInfo } from "./MessageInfo";

export type V1ChatCompletionsReq = {
    /**
     * @type string | undefined, string
    */
    session_id?: string | undefined;
    /**
     * @type string | undefined, string
    */
    model?: string | undefined;
    /**
     * @type array, []*v1.MessageInfo
    */
    messages: V1MessageInfo[];
    /**
     * @type object | undefined
    */
    message?: V1MessageInfo | undefined;
    /**
     * @type number | undefined, float64
    */
    temperature?: number | undefined;
    /**
     * @type integer | undefined, int
    */
    maxTokens?: number | undefined;
    /**
     * @type boolean | undefined, bool
    */
    search_model?: boolean | undefined;
    /**
     * @type boolean | undefined, bool
    */
    image_model?: boolean | undefined;
};