/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1MessageInfo } from "./MessageInfo";

export type V1ChoicesInfo = {
    /**
     * @type integer, int
    */
    index: number;
    /**
     * @type object
    */
    message: V1MessageInfo;
    /**
     * @type string, string
    */
    logprobs: string;
    /**
     * @type string, string
    */
    finish_reason: string;
};