/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1CommonSignStsRes = {
    /**
     * @description AccessKeyId
     * @type string, string
    */
    accessKeyId: string;
    /**
     * @description AccessKeySecret
     * @type string, string
    */
    accessKeySecret: string;
    /**
     * @description STS临时凭证
     * @type string, string
    */
    stsToken: string;
    /**
     * @description 凭证过期时间
     * @type string, string
    */
    expiration: string;
    /**
     * @description 存储桶名称
     * @type string, string
    */
    bucket: string;
    /**
     * @description 地域
     * @type string, string
    */
    region: string;
    /**
     * @description 是否使用HTTPS
     * @type boolean, bool
    */
    secure: boolean;
    /**
     * @description 存储服务的访问域名
     * @type string, string
    */
    OSSRegionEndPoint: string;
};