/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TopicCommentSubInfo } from "./TopicCommentSubInfo";

export type V1CommentLikeLikeRes = {
    /**
     * @type object
    */
    info: V1TopicCommentSubInfo;
};