/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1GuideInfo } from "./GuideInfo";

export type V1GuideListRes = {
    /**
     * @type array, []*v1.GuideInfo
    */
    list: V1GuideInfo[];
};