/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1MessageInfo = {
    /**
     * @type string, string
    */
    role: string;
    /**
     * @type string, string
    */
    content: string;
};