/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1MessageInfo } from "./MessageInfo";

export type V1MessageHistoryInfo = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type integer, int
    */
    index: number;
    /**
     * @type object
    */
    message: V1MessageInfo;
    /**
     * @type string, string
    */
    status: string;
    /**
     * @type string, string
    */
    model: string;
    /**
     * @type string, string
    */
    chat_time: string;
};