/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1ModelInfo } from "./ModelInfo";

export type V1ModelListRes = {
    /**
     * @type array, []*v1.ModelInfo
    */
    list: V1ModelInfo[];
};