/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AccountInfo } from "./AccountInfo";

export type V1NotificationInfo = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type string, consts.NotificationType
    */
    type: string;
    /**
     * @type integer, int64
    */
    related_id: number;
    /**
     * @type string, string
    */
    title: string;
    /**
     * @type string, string
    */
    content: string;
    /**
     * @type string, consts.NotificationStatus
    */
    status: string;
    /**
     * @type string, string
    */
    created_at: string;
    /**
     * @type object
    */
    from_user: V1AccountInfo;
};