/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1NotificationMarkReadRes = {
    /**
     * @type integer, int
    */
    read_count: number;
    /**
     * @type integer, int
    */
    unread_count: number;
};