/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1NotificationListReq = {
    /**
     * @type integer, int
    */
    page: number;
    /**
     * @type integer, int
    */
    size: number;
    /**
     * @type string | undefined, consts.NotificationType
    */
    type?: string | undefined;
    /**
     * @type string | undefined, consts.NotificationStatus
    */
    status?: string | undefined;
};