/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1NotificationInfo } from "./NotificationInfo";

export type V1NotificationListRes = {
    /**
     * @type integer, int
    */
    total: number;
    /**
     * @type integer, int
    */
    page: number;
    /**
     * @type integer, int
    */
    size: number;
    /**
     * @type integer, int
    */
    unread_count: number;
    /**
     * @type array, []*v1.NotificationInfo
    */
    list: V1NotificationInfo[];
};