/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1PointsFindPointTypeListItem } from "./PointsFindPointTypeListItem";

export type V1PointsFindPointTypeListRes = {
    /**
     * @type array, []*v1.PointsFindPointTypeListItem
    */
    List: V1PointsFindPointTypeListItem[];
};