/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1PointsCreateLevelTypeReq = {
    /**
     * @type integer | undefined, int64
    */
    level?: number | undefined;
    /**
     * @type integer | undefined, int64
    */
    levelUpPoints?: number | undefined;
};