/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1PointsFindPointDetailListItem = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type integer, int64
    */
    type: number;
    /**
     * @type integer, int64
    */
    value: number;
    /**
     * @type integer, int64
    */
    accountId: number;
    /**
     * @type string, string
    */
    createdAt: string;
};