/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1ResultInfo = {
    /**
     * @type string, string
    */
    title: string;
    /**
     * @type string, string
    */
    url: string;
    /**
     * @type string, string
    */
    content: string;
    /**
     * @type string, string
    */
    parsed_url: string;
    /**
     * @type array, []string
    */
    engines: string[];
    /**
     * @type number, float64
    */
    score: number;
    /**
     * @type string, string
    */
    category: string;
    /**
     * @type string, string
    */
    published_date: string;
};