/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1SessionInfo } from "./SessionInfo";

export type V1SessionListRes = {
    /**
     * @type integer, int
    */
    total: number;
    /**
     * @type integer, int
    */
    page: number;
    /**
     * @type integer, int
    */
    size: number;
    /**
     * @type array, []*v1.SessionInfo
    */
    list: V1SessionInfo[];
};