/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1SessionDeleteRes = {
    /**
     * @type string, string
    */
    session_id: string;
};