/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1Stats = {
    /**
     * @type integer, int
    */
    topic_count: number;
    /**
     * @type integer, int
    */
    replay_count: number;
    /**
     * @type integer, int
    */
    like_count: number;
};