/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TaskTopicInfo } from "./TaskTopicInfo";

export type V1TaskTopicDetailRes = {
    /**
     * @type object
    */
    info: V1TaskTopicInfo;
};