/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1TaskTopicAddReq = {
    /**
     * @type integer | undefined, int64
    */
    task_id?: number | undefined;
    /**
     * @type string | undefined, string
    */
    title?: string | undefined;
    /**
     * @type string | undefined, consts.TopicStatus
    */
    status?: string | undefined;
    /**
     * @type string, string
    */
    content: string;
};