/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1TaskTopicEditReq = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type string | undefined, string
    */
    title?: string | undefined;
    /**
     * @type string | undefined, consts.TopicStatus
    */
    status?: string | undefined;
    /**
     * @type string | undefined, string
    */
    content?: string | undefined;
};