/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1TopicInfo = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type string, string
    */
    title: string;
    /**
     * @type string, string
    */
    content: string;
    /**
     * @type string, string
    */
    status: string;
    /**
     * @type string, string
    */
    created_at: string;
    /**
     * @type string, string
    */
    updated_at: string;
    /**
     * @type integer, int
    */
    reply_count: number;
    /**
     * @type integer, int
    */
    like_count: number;
};