/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1TopicCommentAddReq = {
    /**
     * @type integer, int64
    */
    topic_id: number;
    /**
     * @type integer, int64
    */
    root_comment_id: number;
    /**
     * @type integer, int64
    */
    comment_id: number;
    /**
     * @type string, string
    */
    content: string;
    /**
     * @type string | undefined, string
    */
    material?: string | undefined;
};