/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1TopicCommentSubListReq = {
    /**
     * @type integer, int64
    */
    topic_id: number;
    /**
     * @type integer, int64
    */
    root_comment_id: number;
    /**
     * @type integer, int
    */
    page: number;
    /**
     * @type integer, int
    */
    size: number;
};