/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1CommentExtra } from "./CommentExtra";
import type { V1CommentExtraAccount } from "./CommentExtraAccount";

export type V1TopicCommentSubInfo = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type integer, int64
    */
    task_id: number;
    /**
     * @type string, string
    */
    task_title: string;
    /**
     * @type integer, int64
    */
    topic_id: number;
    /**
     * @type integer, int64
    */
    root_comment_id: number;
    /**
     * @type integer, int64
    */
    comment_id: number;
    /**
     * @type integer, int64
    */
    account_id: number;
    /**
     * @type string, string
    */
    content: string;
    /**
     * @type string, string
    */
    material: string;
    /**
     * @type string, string
    */
    created_at: string;
    /**
     * @type string, string
    */
    account: string;
    /**
     * @type string, string
    */
    nickname: string;
    /**
     * @type object
    */
    extra: V1CommentExtra;
    /**
     * @type object
    */
    extra_account: V1CommentExtraAccount;
    /**
     * @type string, string
    */
    avatar: string;
};