/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TrainInfo } from "./TrainInfo";

export type V1TrainListRes = {
    /**
     * @type array, []*v1.TrainInfo
    */
    list: V1TrainInfo[];
};