/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const v1TrainInfoTrainTypeEnum = {
    "audio": "audio",
    "image": "image",
    "pose": "pose"
} as const;

export type V1TrainInfoTrainTypeEnumKey = (typeof v1TrainInfoTrainTypeEnum)[keyof typeof v1TrainInfoTrainTypeEnum];

export type V1TrainInfo = {
    /**
     * @type integer, int64
    */
    id: number;
    /**
     * @type string, string
    */
    train_name: string;
    /**
     * @type integer, int64
    */
    account_id: number;
    /**
     * @type integer, int
    */
    train_attribute_epochs: number;
    /**
     * @type integer, int
    */
    train_attribute_batch_size: number;
    /**
     * @type number, float64
    */
    train_attribute_learning_rate: number;
    /**
     * @type string, consts.TrainType
    */
    train_type: V1TrainInfoTrainTypeEnumKey;
    /**
     * @type string, string
    */
    train_status: string;
    /**
     * @type string, string
    */
    train_model: string;
    /**
     * @type string, string
    */
    bin_path: string;
    /**
     * @type string, string
    */
    json_path: string;
    /**
     * @type string, string
    */
    file_dir: string;
    /**
     * @type string, string
    */
    train_structure: string;
    /**
     * @type integer, int
    */
    "k-value": number;
    /**
     * @type number, float64
    */
    filter_coefficients: number;
    /**
     * @type number, float64
    */
    distance_threshold: number;
};