/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1TrainInfo } from "./TrainInfo";

export type V1TrainDetailRes = {
    /**
     * @type object
    */
    info: V1TrainInfo;
};