/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const v1TrainSaveReqTrainTypeEnum = {
    "audio": "audio",
    "image": "image",
    "pose": "pose"
} as const;

export type V1TrainSaveReqTrainTypeEnumKey = (typeof v1TrainSaveReqTrainTypeEnum)[keyof typeof v1TrainSaveReqTrainTypeEnum];

export type V1TrainSaveReq = {
    /**
     * @type string | undefined, string
    */
    train_name?: string | undefined;
    /**
     * @type integer | undefined, int64
    */
    train_id?: number | undefined;
    /**
     * @type integer | undefined, int
    */
    epochs?: number | undefined;
    /**
     * @type integer | undefined, int
    */
    batch_size?: number | undefined;
    /**
     * @type number | undefined, float64
    */
    learning_rate?: number | undefined;
    /**
     * @type string, string
    */
    file_dir: string;
    /**
     * @type string, string
    */
    train_structure: string;
    /**
     * @type string | undefined, string
    */
    bin_path?: string | undefined;
    /**
     * @type string | undefined, string
    */
    json_path?: string | undefined;
    /**
     * @type integer | undefined, int
    */
    "k-value"?: number | undefined;
    /**
     * @type number | undefined, float64
    */
    filter_coefficients?: number | undefined;
    /**
     * @type number | undefined, float64
    */
    distance_threshold?: number | undefined;
    /**
     * @type string, consts.TrainType
    */
    train_type: V1TrainSaveReqTrainTypeEnumKey;
};