/* eslint-disable @typescript-eslint/no-explicit-any */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type V1TrainResultReq = {
    /**
     * @type integer, int64
    */
    train_id: number;
};